import os, sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from check import request, check, expect_error, ok

r = request("GET", "/notes")
check(r.status == 200 and r.json() == [], "empty list at start")
r = request("POST", "/notes", {"title": "first", "body": "hello"})
check(r.status == 201, "create: status %d" % r.status)
check(r.json() == {"id": 1, "title": "first", "body": "hello"}, "create body %r" % r.json())
r = request("POST", "/notes", {"title": "second", "body": ""})
check(r.status == 201 and r.json()["id"] == 2, "second id is 2, empty body allowed")
j = expect_error(request("POST", "/notes", {"title": "", "body": "x"}), 400, "invalid", "empty title")
check("title" in j["error"]["message"], "message names the field")
expect_error(request("POST", "/notes", {"title": "t" * 101, "body": "x"}), 400, "invalid", "101-char title")
expect_error(request("POST", "/notes", {"title": 5, "body": "x"}), 400, "invalid", "title not a string")
expect_error(request("POST", "/notes", {"title": "ok"}), 400, "invalid", "missing body")
expect_error(request("POST", "/notes", raw=b"{nope", headers={"Content-Type": "application/json"}),
             400, "invalid", "malformed JSON")
r = request("GET", "/notes")
check([n["id"] for n in r.json()] == [1, 2], "list in creation order")
check(request("GET", "/notes/2").json()["title"] == "second", "get one")
expect_error(request("GET", "/notes/99"), 404, "not_found", "get missing")
r = request("PUT", "/notes/1", {"title": "renamed", "body": "b"})
check(r.status == 200 and r.json() == {"id": 1, "title": "renamed", "body": "b"}, "update")
expect_error(request("PUT", "/notes/1", {"title": "", "body": "b"}), 400, "invalid", "update validates")
expect_error(request("PUT", "/notes/99", {"title": "x", "body": "b"}), 404, "not_found", "update missing")
r = request("DELETE", "/notes/1")
check(r.status == 204 and r.body == b"", "delete: 204, no body")
expect_error(request("DELETE", "/notes/1"), 404, "not_found", "delete twice")
r = request("POST", "/notes", {"title": "third", "body": ""})
check(r.json()["id"] == 3, "ids are never reused")
ok("notes")
