-- heavy/api dataset. See bench/SPEC.md. Run as the benchmark role.
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id          bigint PRIMARY KEY,
    email       text        NOT NULL,
    name        text        NOT NULL,
    country     char(2)     NOT NULL,
    created_at  timestamptz NOT NULL
);

CREATE TABLE orders (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     bigint      NOT NULL,
    sku         text        NOT NULL,
    qty         int         NOT NULL,
    price_cents bigint      NOT NULL,
    status      text        NOT NULL,
    created_at  timestamptz NOT NULL
);
