/* Split out of the original monolithic codegen.c -- see
 * internal.h for the shared CG state and cross-file API. */

#include "../internal.h"


/* ---- native 'net' package runtime (emitted on demand) ----
 * TCP built on bytes + fixed-width ints. Every fallible operation
 * returns result[T, str]; recv reports \"would block\" on a
 * non-blocking socket with no data available. */

const char *NET_RUNTIME[] = {
    "#include <errno.h>",
    "#include <unistd.h>",
    "#include <fcntl.h>",
    "#include <sys/socket.h>",
    "#include <netinet/in.h>",
    "#include <arpa/inet.h>",
    "#include <netdb.h>",
    "",
    "/* ---- net: blocking & non-blocking TCP over bytes + fixed ints ---- */",
    "",
    "static sl_res_i32_str *sl_net_ok_i32(int32_t v) {",
    "    sl_res_i32_str *r = (sl_res_i32_str *)sl_gc_alloc(",
    "        sizeof(sl_res_i32_str), sl_gc_trace_sl_res_i32_str);",
    "    r->ok = true;",
    "    r->v = v;",
    "    return r;",
    "}",
    "",
    "static sl_res_i32_str *sl_net_err_i32(const char *msg) {",
    "    sl_res_i32_str *r = (sl_res_i32_str *)sl_gc_alloc(",
    "        sizeof(sl_res_i32_str), sl_gc_trace_sl_res_i32_str);",
    "    r->ok = false;",
    "    r->e = sl_strdup(msg);",
    "    return r;",
    "}",
    "",
    "static sl_res_bytes_str *sl_net_ok_bytes(sl_bytes *b) {",
    "    sl_res_bytes_str *r = (sl_res_bytes_str *)sl_gc_alloc(",
    "        sizeof(sl_res_bytes_str), sl_gc_trace_sl_res_bytes_str);",
    "    r->ok = true;",
    "    r->v = b;",
    "    return r;",
    "}",
    "",
    "static sl_res_bytes_str *sl_net_err_bytes(const char *msg) {",
    "    sl_res_bytes_str *r = (sl_res_bytes_str *)sl_gc_alloc(",
    "        sizeof(sl_res_bytes_str), sl_gc_trace_sl_res_bytes_str);",
    "    r->ok = false;",
    "    r->e = sl_strdup(msg);",
    "    return r;",
    "}",
    "",
    "static sl_res_bool_str *sl_net_ok_bool(bool v) {",
    "    sl_res_bool_str *r = (sl_res_bool_str *)sl_gc_alloc(",
    "        sizeof(sl_res_bool_str), sl_gc_trace_sl_res_bool_str);",
    "    r->ok = true;",
    "    r->v = v;",
    "    return r;",
    "}",
    "",
    "static sl_res_bool_str *sl_net_err_bool(const char *msg) {",
    "    sl_res_bool_str *r = (sl_res_bool_str *)sl_gc_alloc(",
    "        sizeof(sl_res_bool_str), sl_gc_trace_sl_res_bool_str);",
    "    r->ok = false;",
    "    r->e = sl_strdup(msg);",
    "    return r;",
    "}",
    "",
    "static sl_res_i32_str *sl_net_listen(int port) {",
    "    int fd = socket(AF_INET, SOCK_STREAM, 0);",
    "    if (fd < 0) return sl_net_err_i32(strerror(errno));",
    "    int one = 1;",
    "    setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, &one, sizeof(one));",
    "    struct sockaddr_in addr;",
    "    memset(&addr, 0, sizeof(addr));",
    "    addr.sin_family = AF_INET;",
    "    addr.sin_addr.s_addr = htonl(INADDR_ANY);",
    "    addr.sin_port = htons((uint16_t)port);",
    "    if (bind(fd, (struct sockaddr *)&addr, sizeof(addr)) != 0) {",
    "        int e = errno; close(fd); return sl_net_err_i32(strerror(e));",
    "    }",
    "    if (listen(fd, 1024) != 0) {",
    "        int e = errno; close(fd); return sl_net_err_i32(strerror(e));",
    "    }",
    "    return sl_net_ok_i32((int32_t)fd);",
    "}",
    "",
    "static sl_res_i32_str *sl_net_port(int lfd) {",
    "    struct sockaddr_in addr;",
    "    socklen_t n = sizeof(addr);",
    "    if (getsockname(lfd, (struct sockaddr *)&addr, &n) != 0)",
    "        return sl_net_err_i32(strerror(errno));",
    "    return sl_net_ok_i32((int32_t)ntohs(addr.sin_port));",
    "}",
    "",
    "/* An accepted socket's blocking mode is platform-defined -- on",
    " * some systems (macOS included) it inherits O_NONBLOCK from a",
    " * non-blocking listening socket, which would otherwise make",
    " * every accepted connection non-blocking too just because the",
    " * *listener* was switched to non-blocking (e.g. to poll accept()",
    " * for a shutdown flag). Force it back to blocking explicitly so",
    " * accept()'s mode is never contagious to the connections it",
    " * hands back; best-effort, since there's nothing sensible to do",
    " * if fcntl itself fails here. */",
    "static void sl_net_ensure_blocking(int fd) {",
    "    int fl = fcntl(fd, F_GETFL, 0);",
    "    if (fl >= 0) fcntl(fd, F_SETFL, fl & ~O_NONBLOCK);",
    "}",
    "",
    "static sl_res_i32_str *sl_net_accept(int lfd) {",
    "    sl_rt_gc_blocked = 1;",
    "    int cfd = accept(lfd, NULL, NULL);",
    "    sl_rt_gc_blocked = 0;",
    "    sl_rt_gc_checkin();",
    "    if (cfd < 0) return sl_net_err_i32(strerror(errno));",
    "    sl_net_ensure_blocking(cfd);",
    "    return sl_net_ok_i32((int32_t)cfd);",
    "}",
    "",
    "static sl_res_i32_str *sl_net_dial(const char *host, int port) {",
    "    char portstr[16];",
    "    snprintf(portstr, sizeof(portstr), \"%d\", port);",
    "    struct addrinfo hints, *res = NULL;",
    "    memset(&hints, 0, sizeof(hints));",
    "    hints.ai_family = AF_INET;",
    "    hints.ai_socktype = SOCK_STREAM;",
    "    int rc = getaddrinfo(host, portstr, &hints, &res);",
    "    if (rc != 0 || !res) return sl_net_err_i32(gai_strerror(rc));",
    "    int fd = socket(res->ai_family, res->ai_socktype, res->ai_protocol);",
    "    if (fd < 0) { freeaddrinfo(res); return sl_net_err_i32(strerror(errno)); }",
    "    sl_rt_gc_blocked = 1;",
    "    int cres = connect(fd, res->ai_addr, res->ai_addrlen);",
    "    sl_rt_gc_blocked = 0;",
    "    sl_rt_gc_checkin();",
    "    if (cres != 0) {",
    "        int e = errno; freeaddrinfo(res); close(fd);",
    "        return sl_net_err_i32(strerror(e));",
    "    }",
    "    freeaddrinfo(res);",
    "    return sl_net_ok_i32((int32_t)fd);",
    "}",
    "",
    "static sl_res_i32_str *sl_net_send(int fd, sl_bytes *data) {",
    "    long long off = 0;",
    "    while (off < data->len) {",
    "        sl_rt_gc_blocked = 1;",
    "        ssize_t n = send(fd, data->ptr + off,",
    "                         (size_t)(data->len - off), 0);",
    "        sl_rt_gc_blocked = 0;",
    "        sl_rt_gc_checkin();",
    "        if (n < 0) {",
    "            if (errno == EINTR) continue;",
    "            return sl_net_err_i32(strerror(errno));",
    "        }",
    "        off += n;",
    "    }",
    "    return sl_net_ok_i32((int32_t)data->len);",
    "}",
    "",
    "/* Tier 10: b is allocated, then recv() (which can block, possibly",
    " * for a long time waiting on the socket) is called before b is",
    " * returned anywhere reachable. A blocked thread is deliberately",
    " * exempt from other threads' collection waits -- but that means a",
    " * collection CAN run concurrently while this thread sits inside",
    " * recv(), and b, sitting only in this C local with no caller-side",
    " * bracket protecting it (this is a hand-written runtime function,",
    " * not codegen output -- the caller's own bracket was built before",
    " * b even existed), would be swept out from under this function.",
    " * sl_rt_safepoint_enter/exit are ordinary C functions, usable from",
    " * hand-written runtime code exactly like codegen-generated",
    " * brackets use them -- this one roots b explicitly around the",
    " * blocking call specifically. */",
    "static sl_res_bytes_str *sl_net_recv(int fd, int max) {",
    "    if (max <= 0) max = 4096;",
    "    sl_bytes *b = (sl_bytes *)sl_gc_alloc(sizeof(sl_bytes), sl_gc_trace_bytes);",
    "    b->len = 0;",
    "    b->ptr = (unsigned char *)sl_gc_alloc((size_t)max, NULL);",
    "    void *_sl_rcv_roots[] = { (void *)b };",
    "    sl_safepoint _sl_rcv_sp;",
    "    sl_rt_safepoint_enter(&_sl_rcv_sp, _sl_rcv_roots, 1);",
    "    sl_rt_gc_blocked = 1;",
    "    ssize_t n = recv(fd, b->ptr, (size_t)max, 0);",
    "    sl_rt_gc_blocked = 0;",
    "    sl_rt_gc_checkin();",
    "    sl_rt_safepoint_exit();",
    "    if (n < 0) {",
    "        if (errno == EAGAIN || errno == EWOULDBLOCK)",
    "            return sl_net_err_bytes(\"would block\");",
    "        return sl_net_err_bytes(strerror(errno));",
    "    }",
    "    b->len = (long long)n;",
    "    return sl_net_ok_bytes(b);",
    "}",
    "",
    "static void sl_net_close(int fd) { close(fd); }",
    "",
    "static sl_res_bool_str *sl_net_nonblock(int fd) {",
    "    int fl = fcntl(fd, F_GETFL, 0);",
    "    if (fl < 0) return sl_net_err_bool(strerror(errno));",
    "    if (fcntl(fd, F_SETFL, fl | O_NONBLOCK) != 0)",
    "        return sl_net_err_bool(strerror(errno));",
    "    return sl_net_ok_bool(true);",
    "}",
    "",
};

const int NET_RUNTIME_LEN = sizeof(NET_RUNTIME) / sizeof(NET_RUNTIME[0]);
