/* Split out of the original monolithic codegen.c -- see
 * internal.h for the shared CG state and cross-file API. */

#include "../internal.h"


/* Blocking mode only, matching net's own blocking-by-default design:
 * a spawned OS thread just blocks inside SSL_read/SSL_write like it
 * already blocks inside recv()/send(), so nothing here needs
 * non-blocking/retry handling. Client verification is strict by
 * default (SSL_VERIFY_PEER + SSL_set1_host for hostname checking --
 * the part that's easy to silently omit and end up with a TLS
 * connection that validates the certificate chain but not that it
 * belongs to the host you asked for). */
const char *TLS_RUNTIME[] = {
    "#include <openssl/err.h>",
    "#include <openssl/ssl.h>",
    "",
    "/* ---- net: TLS listener/dialer built on OpenSSL ---- */",
    "",
    "static sl_res_rawptr_str *sl_net_ok_rawptr(void *v) {",
    "    sl_res_rawptr_str *r =",
    "        (sl_res_rawptr_str *)GC_malloc(sizeof(sl_res_rawptr_str));",
    "    r->ok = true;",
    "    r->v = v;",
    "    return r;",
    "}",
    "",
    "static sl_res_rawptr_str *sl_net_err_rawptr(const char *msg) {",
    "    sl_res_rawptr_str *r =",
    "        (sl_res_rawptr_str *)GC_malloc(sizeof(sl_res_rawptr_str));",
    "    r->ok = false;",
    "    r->e = sl_strdup(msg);",
    "    return r;",
    "}",
    "",
    "static char *sl_tls_last_error(void) {",
    "    unsigned long e = ERR_get_error();",
    "    char buf[256];",
    "    if (e == 0)",
    "        snprintf(buf, sizeof(buf), \"unknown TLS error\");",
    "    else",
    "        ERR_error_string_n(e, buf, sizeof(buf));",
    "    return sl_strdup(buf);",
    "}",
    "",
    "static sl_res_rawptr_str *sl_net_tls_server_ctx(const char *cert_path,",
    "                                                const char *key_path) {",
    "    SSL_CTX *ctx = SSL_CTX_new(TLS_server_method());",
    "    if (!ctx) return sl_net_err_rawptr(sl_tls_last_error());",
    "    if (SSL_CTX_use_certificate_file(ctx, cert_path, SSL_FILETYPE_PEM) != 1) {",
    "        char *m = sl_tls_last_error();",
    "        SSL_CTX_free(ctx);",
    "        return sl_net_err_rawptr(m);",
    "    }",
    "    if (SSL_CTX_use_PrivateKey_file(ctx, key_path, SSL_FILETYPE_PEM) != 1) {",
    "        char *m = sl_tls_last_error();",
    "        SSL_CTX_free(ctx);",
    "        return sl_net_err_rawptr(m);",
    "    }",
    "    if (SSL_CTX_check_private_key(ctx) != 1) {",
    "        SSL_CTX_free(ctx);",
    "        return sl_net_err_rawptr(\"certificate/key mismatch\");",
    "    }",
    "    return sl_net_ok_rawptr(ctx);",
    "}",
    "",
    "static sl_res_rawptr_str *sl_net_tls_client_ctx(const char *ca_path) {",
    "    SSL_CTX *ctx = SSL_CTX_new(TLS_client_method());",
    "    if (!ctx) return sl_net_err_rawptr(sl_tls_last_error());",
    "    SSL_CTX_set_verify(ctx, SSL_VERIFY_PEER, NULL);",
    "    if (ca_path[0] != '\\0') {",
    "        if (SSL_CTX_load_verify_locations(ctx, ca_path, NULL) != 1) {",
    "            char *m = sl_tls_last_error();",
    "            SSL_CTX_free(ctx);",
    "            return sl_net_err_rawptr(m);",
    "        }",
    "    } else {",
    "        SSL_CTX_set_default_verify_paths(ctx);",
    "    }",
    "    return sl_net_ok_rawptr(ctx);",
    "}",
    "",
    "static sl_res_rawptr_str *sl_net_tls_accept(int lfd, void *ctxv) {",
    "    int cfd = accept(lfd, NULL, NULL);",
    "    if (cfd < 0) return sl_net_err_rawptr(strerror(errno));",
    "    SSL *ssl = SSL_new((SSL_CTX *)ctxv);",
    "    if (!ssl) {",
    "        close(cfd);",
    "        return sl_net_err_rawptr(sl_tls_last_error());",
    "    }",
    "    SSL_set_fd(ssl, cfd);",
    "    if (SSL_accept(ssl) != 1) {",
    "        char *m = sl_tls_last_error();",
    "        SSL_free(ssl);",
    "        close(cfd);",
    "        return sl_net_err_rawptr(m);",
    "    }",
    "    return sl_net_ok_rawptr(ssl);",
    "}",
    "",
    "static sl_res_rawptr_str *sl_net_tls_dial(const char *host, int port,",
    "                                          void *ctxv) {",
    "    char portstr[16];",
    "    snprintf(portstr, sizeof(portstr), \"%d\", port);",
    "    struct addrinfo hints, *res = NULL;",
    "    memset(&hints, 0, sizeof(hints));",
    "    hints.ai_family = AF_INET;",
    "    hints.ai_socktype = SOCK_STREAM;",
    "    int rc = getaddrinfo(host, portstr, &hints, &res);",
    "    if (rc != 0 || !res) return sl_net_err_rawptr(gai_strerror(rc));",
    "    int fd = socket(res->ai_family, res->ai_socktype, res->ai_protocol);",
    "    if (fd < 0) {",
    "        freeaddrinfo(res);",
    "        return sl_net_err_rawptr(strerror(errno));",
    "    }",
    "    if (connect(fd, res->ai_addr, res->ai_addrlen) != 0) {",
    "        int e = errno;",
    "        freeaddrinfo(res);",
    "        close(fd);",
    "        return sl_net_err_rawptr(strerror(e));",
    "    }",
    "    freeaddrinfo(res);",
    "    SSL *ssl = SSL_new((SSL_CTX *)ctxv);",
    "    if (!ssl) {",
    "        close(fd);",
    "        return sl_net_err_rawptr(sl_tls_last_error());",
    "    }",
    "    SSL_set_fd(ssl, fd);",
    "    SSL_set1_host(ssl, host);",
    "    SSL_set_tlsext_host_name(ssl, host);",
    "    if (SSL_connect(ssl) != 1 || SSL_get_verify_result(ssl) != X509_V_OK) {",
    "        char *m = sl_tls_last_error();",
    "        SSL_free(ssl);",
    "        close(fd);",
    "        return sl_net_err_rawptr(m);",
    "    }",
    "    return sl_net_ok_rawptr(ssl);",
    "}",
    "",
    "static sl_res_i32_str *sl_net_tls_send(void *sslv, sl_bytes *data) {",
    "    SSL *ssl = (SSL *)sslv;",
    "    long long off = 0;",
    "    while (off < data->len) {",
    "        int n = SSL_write(ssl, data->ptr + off, (int)(data->len - off));",
    "        if (n <= 0) return sl_net_err_i32(sl_tls_last_error());",
    "        off += n;",
    "    }",
    "    return sl_net_ok_i32((int32_t)data->len);",
    "}",
    "",
    "static sl_res_bytes_str *sl_net_tls_recv(void *sslv, int max) {",
    "    if (max <= 0) max = 4096;",
    "    SSL *ssl = (SSL *)sslv;",
    "    sl_bytes *b = (sl_bytes *)GC_malloc(sizeof(sl_bytes));",
    "    b->ptr = (unsigned char *)GC_malloc((size_t)max);",
    "    int n = SSL_read(ssl, b->ptr, max);",
    "    if (n <= 0) {",
    "        if (SSL_get_error(ssl, n) == SSL_ERROR_ZERO_RETURN) {",
    "            b->len = 0;",
    "            return sl_net_ok_bytes(b);",
    "        }",
    "        return sl_net_err_bytes(sl_tls_last_error());",
    "    }",
    "    b->len = n;",
    "    return sl_net_ok_bytes(b);",
    "}",
    "",
    "static void sl_net_tls_close(void *sslv) {",
    "    SSL *ssl = (SSL *)sslv;",
    "    int fd = SSL_get_fd(ssl);",
    "    SSL_shutdown(ssl);",
    "    SSL_free(ssl);",
    "    if (fd >= 0) close(fd);",
    "}",
    "",
};

const int TLS_RUNTIME_LEN = sizeof(TLS_RUNTIME) / sizeof(TLS_RUNTIME[0]);
