/* Tier 10: the precise, non-moving, stop-the-world mark-sweep collector
 * that replaces Boehm. Emitted right after RUNTIME[]'s sl_task/sl_runq
 * definitions (runtime_core.c) -- sl_gc_thread.task_slot points at a
 * thread's own sl_rt_current_task, and the queue-rooting walk in
 * sl_gc_collect reads sl_global_runq directly, so this file depends on
 * both already being defined, but is otherwise self-contained. See
 * todo.md's Tier 10 entry and the Tier 11 plan for the full protocol
 * writeup, including the five concurrency bugs a standalone multi-
 * threaded spike found and fixed before this file was first written,
 * and the seven more a later review pass found before the task_slot/
 * run-queue-rooting fix landed. */

#include "internal.h"

const char *RUNTIME_GC[] = {
    "#include <sched.h>",
    "",
    "/* ---- precise mark-sweep collector (replaces Boehm) ---- */",
    "",
    "typedef struct sl_gc_obj {",
    "    struct sl_gc_obj *next;",
    "    size_t size;",
    "    void (*trace)(void *payload, void (*mark)(void *ptr));",
    "    unsigned char marked;",
    "} sl_gc_obj;",
    "",
    "static sl_gc_obj *sl_gc_all = NULL;",
    "static pthread_mutex_t sl_gc_mu = PTHREAD_MUTEX_INITIALIZER;",
    "static size_t sl_gc_bytes_since_collect = 0;",
    "static size_t sl_gc_threshold = 8 * 1024 * 1024;",
    "",
    "/* A root array can legitimately hold a pointer that was never",
    " * sl_gc_alloc'd at all: every str-typed value is type_is_gc_ptr-true",
    " * and gets rooted like any other GC pointer, but a slang string",
    " * LITERAL compiles directly to a C string literal (c_string_literal,",
    " * core.c) -- a raw pointer into .rodata, not a heap allocation.",
    " * Treating it as one (reading the sl_gc_obj header presumed to sit",
    " * just before it) is undefined behavior -- caught by ASan as a",
    " * global-buffer-overflow the first time a real collection actually",
    " * ran against a program using string literals (which is effectively",
    " * all of them). This hash set of every currently-live sl_gc_alloc'd",
    " * payload address lets sl_gc_mark tell 'one of mine' from 'the type",
    " * system says pointer, but this specific value isn't a heap",
    " * allocation' before ever computing ptr - 1, instead of assuming",
    " * every non-NULL pointer handed to it is safe to treat as a header.",
    " * Maintained incrementally on alloc (insert), rebuilt wholesale at",
    " * the end of every sweep (cheap relative to the sweep itself, which",
    " * already walks every survivor) rather than needing a delete path.",
    " */",
    "static void **sl_gc_set = NULL;",
    "static size_t sl_gc_set_cap = 0;",
    "static size_t sl_gc_set_count = 0;",
    "",
    "static size_t sl_gc_ptrhash(void *p) {",
    "    uintptr_t x = (uintptr_t)p;",
    "    x ^= x >> 33; x *= 0xff51afd7ed558ccdULL; x ^= x >> 33;",
    "    x *= 0xc4ceb9fe1a85ec53ULL; x ^= x >> 33;",
    "    return (size_t)x;",
    "}",
    "",
    "/* linear-probing insert into a fixed-capacity table -- caller",
    " * (sl_gc_set_insert) guarantees the table has already been grown to",
    " * keep the load factor bounded before calling this. */",
    "static void sl_gc_set_raw_insert(void **tbl, size_t cap, void *p) {",
    "    size_t i = sl_gc_ptrhash(p) & (cap - 1);",
    "    while (tbl[i]) i = (i + 1) & (cap - 1);",
    "    tbl[i] = p;",
    "}",
    "",
    "static void sl_gc_set_grow(size_t min_cap) {",
    "    size_t newcap = sl_gc_set_cap ? sl_gc_set_cap : 1024;",
    "    while (newcap < min_cap) newcap *= 2;",
    "    void **nt = (void **)calloc(newcap, sizeof(void *));",
    "    if (!nt) { fprintf(stderr, \"slang: out of memory\\n\"); exit(1); }",
    "    for (size_t i = 0; i < sl_gc_set_cap; i++)",
    "        if (sl_gc_set[i]) sl_gc_set_raw_insert(nt, newcap, sl_gc_set[i]);",
    "    free(sl_gc_set);",
    "    sl_gc_set = nt;",
    "    sl_gc_set_cap = newcap;",
    "}",
    "",
    "static void sl_gc_set_insert(void *p) {",
    "    if ((sl_gc_set_count + 1) * 2 >= sl_gc_set_cap)",
    "        sl_gc_set_grow(sl_gc_set_cap ? sl_gc_set_cap * 2 : 1024);",
    "    sl_gc_set_raw_insert(sl_gc_set, sl_gc_set_cap, p);",
    "    sl_gc_set_count++;",
    "}",
    "",
    "static int sl_gc_set_contains(void *p) {",
    "    if (!sl_gc_set_cap) return 0;",
    "    size_t i = sl_gc_ptrhash(p) & (sl_gc_set_cap - 1);",
    "    for (;;) {",
    "        if (!sl_gc_set[i]) return 0;",
    "        if (sl_gc_set[i] == p) return 1;",
    "        i = (i + 1) & (sl_gc_set_cap - 1);",
    "    }",
    "}",
    "",
    "/* rebuild from scratch against the (already-swept) survivor list --",
    " * simpler and just as cheap as a delete-capable table would be,",
    " * since sweep already visits every survivor once. */",
    "static void sl_gc_set_rebuild(size_t live_count) {",
    "    size_t newcap = 1024;",
    "    while (newcap < live_count * 2) newcap *= 2;",
    "    free(sl_gc_set);",
    "    sl_gc_set = (void **)calloc(newcap, sizeof(void *));",
    "    if (!sl_gc_set) { fprintf(stderr, \"slang: out of memory\\n\"); exit(1); }",
    "    sl_gc_set_cap = newcap;",
    "    sl_gc_set_count = 0;",
    "    for (sl_gc_obj *h = sl_gc_all; h; h = h->next) {",
    "        sl_gc_set_raw_insert(sl_gc_set, sl_gc_set_cap, (void *)(h + 1));",
    "        sl_gc_set_count++;",
    "    }",
    "}",
    "",
    "/* one entry per registered thread, pointing at that thread's own",
    " * _Thread_local storage -- valid as long as the thread lives, since",
    " * each thread publishes the address of its own TLS vars at",
    " * registration time (a standard, portable technique: the address of",
    " * a _Thread_local variable is stable for the lifetime of the owning",
    " * thread). Guarded by sl_gc_mu. */",
    "typedef struct sl_gc_thread {",
    "    struct sl_gc_thread *next;",
    "    sl_task **task_slot; /* &sl_rt_current_task for this OS thread --",
    "        NOT &sl_rt_current_task->safepoint_top. The latter (this",
    "        field's shape before Tier 11's second slice) is a single",
    "        dereference cached at registration time: correct as long as",
    "        sl_rt_current_task never changes for the thread's whole life",
    "        (true before a worker pool exists, since one task lives and",
    "        dies with its OS thread), but stale the instant a pooled",
    "        worker gets reassigned to a new task -- the collector would",
    "        keep reading whichever task's safepoint_top field happened",
    "        to be current AT REGISTRATION, not the task actually running",
    "        now. task_slot fixes this by pointing at the STABLE",
    "        _Thread_local variable itself; sl_gc_collect's mark phase",
    "        below dereferences it twice instead of once, always landing",
    "        on whichever task is current at SCAN time. */",
    "    _Atomic int *blocked_ptr;",
    "    _Atomic unsigned long *acked_cycle_ptr;",
    "} sl_gc_thread;",
    "static sl_gc_thread *sl_gc_threads = NULL;",
    "static _Atomic int sl_gc_stop_requested = 0;",
    "static _Atomic unsigned long sl_gc_cycle = 0;",
    "static _Atomic int sl_gc_collect_pending = 0;",
    "static _Atomic int sl_gc_collecting = 0;",
    "",
    "static _Thread_local sl_gc_thread sl_rt_gc_reg;",
    "static _Thread_local _Atomic int sl_rt_gc_blocked = 0;",
    "static _Thread_local _Atomic unsigned long sl_rt_gc_acked_cycle = 0;",
    "",
    "static void sl_gc_collect(void);",
    "",
    "static void sl_gc_register_thread(void) {",
    "    /* Tier 11: this OS thread's chain lives in a per-thread sl_task",
    "     * (sl_rt_current_task, runtime_core.c) rather than a bare",
    "     * _Thread_local safepoint pointer -- see task_slot's own field",
    "     * comment above for why this must be &sl_rt_current_task itself,",
    "     * not &sl_rt_current_task->safepoint_top. Still true today (one",
    "     * task per OS thread, no scheduler running yet) that",
    "     * sl_rt_current_task never actually changes after this point --",
    "     * task_slot's extra indirection costs nothing observable now and",
    "     * is exactly what makes it safe for a future worker pool to",
    "     * reassign sl_rt_current_task freely. */",
    "    memset(&sl_rt_task_storage, 0, sizeof(sl_rt_task_storage));",
    "    sl_rt_current_task = &sl_rt_task_storage;",
    "    sl_rt_gc_reg.task_slot = &sl_rt_current_task;",
    "    sl_rt_gc_reg.blocked_ptr = &sl_rt_gc_blocked;",
    "    sl_rt_gc_reg.acked_cycle_ptr = &sl_rt_gc_acked_cycle;",
    "    pthread_mutex_lock(&sl_gc_mu);",
    "    sl_rt_gc_reg.next = sl_gc_threads;",
    "    sl_gc_threads = &sl_rt_gc_reg;",
    "    pthread_mutex_unlock(&sl_gc_mu);",
    "}",
    "",
    "/* ack the current STW cycle and wait for it to end. A loop tracking",
    " * the actual cycle number, not a single ack-then-spin-on-a-boolean:",
    " * sl_gc_stop_requested is one flag reused across every cycle, and a",
    " * thread parked on 'while (stop_requested) yield' can miss a brief",
    " * 0-then-1 transition entirely if two collections happen back to",
    " * back -- it keeps seeing 1 straight through the boundary, having",
    " * already acked the older cycle, and never re-acks the newer one.",
    " * Re-checking the cycle number on every spin and re-acking the",
    " * instant it moves closes that gap: a newer cycle number is itself",
    " * proof the one this thread acked already finished (only one",
    " * collection is ever in flight, via the sl_gc_collecting exchange",
    " * below), so there's nothing lost by no longer waiting for a clean",
    " * 0 observation on the shared flag. */",
    "static inline void sl_gc_ack_and_wait(void) {",
    "    unsigned long cyc = atomic_load_explicit(&sl_gc_cycle,",
    "                                              memory_order_acquire);",
    "    atomic_store_explicit(&sl_rt_gc_acked_cycle, cyc,",
    "                           memory_order_release);",
    "    while (atomic_load_explicit(&sl_gc_stop_requested,",
    "                                 memory_order_acquire)) {",
    "        sched_yield();",
    "        unsigned long now = atomic_load_explicit(&sl_gc_cycle,",
    "                                                  memory_order_acquire);",
    "        if (now != cyc) {",
    "            cyc = now;",
    "            atomic_store_explicit(&sl_rt_gc_acked_cycle, cyc,",
    "                                   memory_order_release);",
    "        }",
    "    }",
    "}",
    "",
    "/* This can't be 'checkin, then separately unlink' -- there is a real",
    " * gap between 'I last checked in and saw nothing pending' and 'I",
    " * actually removed myself from sl_gc_threads', and a brand new",
    " * collection can start in exactly that gap, snapshot the registry",
    " * while this thread is still in it, and then have this thread finish",
    " * unregistering and return -- tearing down its own TLS while the",
    " * collector still holds a pointer into it. Re-checking",
    " * stop_requested *inside the same lock* that does the unlink closes",
    " * this: sl_gc_collect() also needs sl_gc_mu for its snapshot, and",
    " * always sets stop_requested before acquiring it, so mutex ordering",
    " * guarantees either this thread unlinks before any snapshot can see",
    " * it, or the snapshot (and the store, strictly earlier) already",
    " * happened, in which case this thread's own load inside the lock is",
    " * guaranteed to observe it. */",
    "static void sl_gc_unregister_thread(void) {",
    "    for (;;) {",
    "        pthread_mutex_lock(&sl_gc_mu);",
    "        if (atomic_load_explicit(&sl_gc_stop_requested,",
    "                                  memory_order_acquire)) {",
    "            pthread_mutex_unlock(&sl_gc_mu);",
    "            sl_gc_ack_and_wait();",
    "            continue;",
    "        }",
    "        sl_gc_thread **pp = &sl_gc_threads;",
    "        while (*pp) {",
    "            if (*pp == &sl_rt_gc_reg) { *pp = sl_rt_gc_reg.next; break; }",
    "            pp = &(*pp)->next;",
    "        }",
    "        pthread_mutex_unlock(&sl_gc_mu);",
    "        return;",
    "    }",
    "}",
    "",
    "/* called from sl_rt_safepoint_enter, and around each of the six",
    " * blocking runtime calls. A loop, not a one-shot check: there is a",
    " * real window between another thread's atomic_exchange on",
    " * sl_gc_collecting succeeding and its first line inside",
    " * sl_gc_collect() actually storing stop_requested = 1. A thread",
    " * whose own stop_requested load happens in that window sees 0 *and*",
    " * loses the collecting exchange -- a one-shot version then returns",
    " * having done nothing at all, no ack, no wait. Looping back to",
    " * re-check stop_requested instead closes the window: the winner is",
    " * at most a few instructions from its own store. */",
    "static inline void sl_rt_gc_checkin(void) {",
    "    for (;;) {",
    "        if (atomic_load_explicit(&sl_gc_stop_requested,",
    "                                  memory_order_acquire)) {",
    "            sl_gc_ack_and_wait();",
    "            return;",
    "        }",
    "        if (!atomic_load_explicit(&sl_gc_collect_pending,",
    "                                   memory_order_acquire))",
    "            return;",
    "        if (!atomic_exchange_explicit(&sl_gc_collecting, 1,",
    "                                       memory_order_acq_rel)) {",
    "            sl_gc_collect();",
    "            return;",
    "        }",
    "        sched_yield();",
    "    }",
    "}",
    "",
    "/* zero-filled, like GC_malloc's documented guarantee -- no existing",
    " * call site relying on that needs auditing. Collection is never",
    " * triggered synchronously from here: several hand-written runtime",
    " * helpers (sl_bytes_new, sl_chan_new, sl_map_new/grow) do more than",
    " * one allocation before returning a single logical object, with no",
    " * safepoint bracket of their own around the intermediate steps -- an",
    " * in-place collection could sweep the first allocation before the",
    " * second one is even made. Crossing the threshold only sets a",
    " * pending flag; the actual mark+sweep is deferred to the next",
    " * sl_rt_gc_checkin(), which by construction only ever fires at a",
    " * call-site or loop-back-edge bracket boundary, exactly where",
    " * everything currently live is already registered in the chain and",
    " * no hand-written helper is mid-flight. This makes the threshold",
    " * soft, not exact -- acceptable, matching the 'not a pause-time",
    " * optimization' stance for this collector's first version. */",
    "static void *sl_gc_alloc(size_t n,",
    "                          void (*trace)(void *, void (*)(void *))) {",
    "    sl_gc_obj *h = (sl_gc_obj *)malloc(sizeof(sl_gc_obj) + n);",
    "    if (!h) { fprintf(stderr, \"slang: out of memory\\n\"); exit(1); }",
    "    memset(h + 1, 0, n);",
    "    h->size = n;",
    "    h->trace = trace;",
    "    h->marked = 0;",
    "    pthread_mutex_lock(&sl_gc_mu);",
    "    h->next = sl_gc_all;",
    "    sl_gc_all = h;",
    "    sl_gc_set_insert((void *)(h + 1));",
    "    sl_gc_bytes_since_collect += n;",
    "    if (sl_gc_bytes_since_collect >= sl_gc_threshold)",
    "        atomic_store_explicit(&sl_gc_collect_pending, 1,",
    "                               memory_order_release);",
    "    pthread_mutex_unlock(&sl_gc_mu);",
    "    return (void *)(h + 1);",
    "}",
    "",
    "/* true drop-in for GC_realloc(p, n): old size/trace read from p's",
    " * own header, so no call site needs to track them separately (one",
    " * real site, pkg_json's sl_utf8_append, overwrites its tracked",
    " * capacity variable before the realloc call, so the old size",
    " * wouldn't even be available there under a signature that needed",
    " * it passed in). Never grows in place -- allocates fresh, copies,",
    " * and lets the old block go unreachable for the next sweep; a real",
    " * collector makes an orphaned block garbage, not a leak. */",
    "static void *sl_gc_realloc(void *old, size_t newn) {",
    "    if (!old) return sl_gc_alloc(newn, NULL);",
    "    sl_gc_obj *oh = (sl_gc_obj *)old - 1;",
    "    void *nw = sl_gc_alloc(newn, oh->trace);",
    "    size_t copy = oh->size < newn ? oh->size : newn;",
    "    memcpy(nw, old, copy);",
    "    return nw;",
    "}",
    "",
    "/* growable worklist for the mark phase's breadth-first walk -- an",
    " * explicit stack, not C recursion, so a long chain of live objects",
    " * (e.g. a long list) can't overflow the collecting thread's own",
    " * stack. */",
    "static void **sl_gc_wl = NULL;",
    "static size_t sl_gc_wl_cap = 0;",
    "static size_t sl_gc_wl_n = 0;",
    "",
    "static void sl_gc_mark(void *ptr) {",
    "    if (!ptr) return;",
    "    if (!sl_gc_set_contains(ptr)) return; /* not one of ours -- e.g. a",
    "        string literal (.rodata, never sl_gc_alloc'd); unsafe to",
    "        treat ptr - 1 as a header, see sl_gc_set's own comment */",
    "    sl_gc_obj *h = (sl_gc_obj *)ptr - 1;",
    "    if (h->marked) return;",
    "    h->marked = 1;",
    "    if (sl_gc_wl_n == sl_gc_wl_cap) {",
    "        sl_gc_wl_cap = sl_gc_wl_cap ? sl_gc_wl_cap * 2 : 256;",
    "        sl_gc_wl = (void **)realloc(sl_gc_wl,",
    "                                     sl_gc_wl_cap * sizeof(void *));",
    "        if (!sl_gc_wl) { fprintf(stderr, \"slang: out of memory\\n\"); exit(1); }",
    "    }",
    "    sl_gc_wl[sl_gc_wl_n++] = ptr;",
    "}",
    "",
    "/* the actual STW mark+sweep. Called only from sl_rt_gc_checkin,",
    " * never synchronously from sl_gc_alloc (see the comment there).",
    " * sl_gc_stop_requested and sl_gc_cycle are set *before* sl_gc_mu is",
    " * ever taken here, and the registry is only read into a private",
    " * snapshot under a brief lock, released before the quiescence wait",
    " * -- both load-bearing: holding sl_gc_mu across the whole wait would",
    " * deadlock against a mutator that needs the same mutex to finish an",
    " * in-flight sl_gc_alloc before it can reach its own next checkin;",
    " * reading the live list without the lock for the whole wait would",
    " * race a concurrent sl_gc_register_thread(). */",
    "static void sl_gc_collect(void) {",
    "    atomic_store_explicit(&sl_gc_stop_requested, 1, memory_order_release);",
    "    unsigned long cyc = atomic_fetch_add_explicit(&sl_gc_cycle, 1,",
    "                                    memory_order_release) + 1;",
    "",
    "    sl_gc_thread **snap = NULL;",
    "    int nsnap = 0, snap_cap = 0;",
    "    pthread_mutex_lock(&sl_gc_mu);",
    "    for (sl_gc_thread *t = sl_gc_threads; t; t = t->next) {",
    "        if (nsnap == snap_cap) {",
    "            snap_cap = snap_cap ? snap_cap * 2 : 16;",
    "            snap = (sl_gc_thread **)realloc(snap,",
    "                                    (size_t)snap_cap * sizeof(*snap));",
    "        }",
    "        snap[nsnap++] = t;",
    "    }",
    "    pthread_mutex_unlock(&sl_gc_mu);",
    "",
    "    for (;;) {",
    "        int all_ready = 1;",
    "        for (int i = 0; i < nsnap; i++) {",
    "            sl_gc_thread *t = snap[i];",
    "            if (t == &sl_rt_gc_reg) continue;",
    "            if (atomic_load_explicit(t->blocked_ptr, memory_order_acquire))",
    "                continue;",
    "            if (atomic_load_explicit(t->acked_cycle_ptr,",
    "                                      memory_order_acquire) == cyc)",
    "                continue;",
    "            all_ready = 0;",
    "            break;",
    "        }",
    "        if (all_ready) break;",
    "        sched_yield();",
    "    }",
    "",
    "    pthread_mutex_lock(&sl_gc_mu);",
    "",
    "    sl_gc_wl_n = 0;",
    "    for (int i = 0; i < nsnap; i++) {",
    "        sl_task *sl_gc_scan_task = *snap[i]->task_slot; /* see",
    "            task_slot's own field comment above: this reads whichever",
    "            task is current AT SCAN TIME, not a value cached at",
    "            registration -- the load-bearing fix for worker reuse. */",
    "        sl_gc_mark(sl_gc_scan_task->entry_arg); /* Tier 11 third-slice",
    "            review finding: root the CURRENTLY-RUNNING task's own",
    "            entry_arg directly too, not just a queued task's (below).",
    "            %s_entry's own generated body builds no safepoint bracket",
    "            around its args struct before reading its fields, so",
    "            nothing else protects it once the task starts running --",
    "            confirmed by a dedicated dequeue-window stress spike",
    "            (see the Tier 11 plan) that reproduced entry_arg",
    "            corruption without this line. */",
    "        for (sl_safepoint *sp = sl_gc_scan_task->safepoint_top; sp;",
    "             sp = sp->prev)",
    "            for (int j = 0; j < sp->nroots; j++)",
    "                sl_gc_mark(sp->roots[j]);",
    "    }",
    "    /* A queued (not-yet-started) task's own safepoint chain is empty",
    "     * -- nothing about it is reachable through the loop above -- but",
    "     * its entry_arg is a live root all the same (for real spawn,",
    "     * always a real sl_gc_alloc'd struct). Root it directly by",
    "     * walking the run queue here, while already holding sl_gc_mu:",
    "     * lock order is always sl_gc_mu-then-runq-mu, consistently, and",
    "     * sl_runq_push/pop_blocking (runtime_pool.c) never hold the",
    "     * queue's own mutex while touching sl_gc_mu, so this can't",
    "     * deadlock against them. sl_global_runq itself is declared in",
    "     * RUNTIME[] (runtime_core.c), not here or in runtime_pool.c --",
    "     * same ordering reason as sl_task: this function needs the",
    "     * complete sl_runq type and the variable both visible at its own",
    "     * definition site, which is well before RUNTIME_POOL is",
    "     * emitted. */",
    "    pthread_mutex_lock(&sl_global_runq.mu);",
    "    for (sl_task *sl_gc_qt = sl_global_runq.head; sl_gc_qt;",
    "         sl_gc_qt = sl_gc_qt->next)",
    "        sl_gc_mark(sl_gc_qt->entry_arg);",
    "    pthread_mutex_unlock(&sl_global_runq.mu);",
    "    /* Tier 11 fourth slice: a PARKED task (chan_send/recv, this slice)",
    "     * is reachable from neither a registered thread's task_slot (the",
    "     * worker that parked it reassigns that back to its own idle",
    "     * sentinel before fetching the next task) nor the run queue walk",
    "     * just above (it's on some primitive's own wait list instead,",
    "     * e.g. a channel's send/recv_waiters) -- sl_parked_tasks",
    "     * (runtime_core.c) is the dedicated registry every parking",
    "     * primitive must register into for exactly this reason. Unlike a",
    "     * queued task, a parked task's safepoint chain is NOT empty (it",
    "     * parked mid-execution, not before starting), so both entry_arg",
    "     * and the chain need marking here, same as the per-thread walk",
    "     * above. Already holding sl_gc_mu -- sl_parked_tasks is guarded",
    "     * by the same lock, so no extra locking needed to walk it. */",
    "    for (sl_task *sl_gc_pt = sl_parked_tasks; sl_gc_pt;",
    "         sl_gc_pt = sl_gc_pt->parked_next) {",
    "        sl_gc_mark(sl_gc_pt->entry_arg);",
    "        for (sl_safepoint *sp = sl_gc_pt->safepoint_top; sp; sp = sp->prev)",
    "            for (int j = 0; j < sp->nroots; j++)",
    "                sl_gc_mark(sp->roots[j]);",
    "    }",
    "    while (sl_gc_wl_n > 0) {",
    "        void *p = sl_gc_wl[--sl_gc_wl_n];",
    "        sl_gc_obj *h = (sl_gc_obj *)p - 1;",
    "        if (h->trace) h->trace(p, sl_gc_mark);",
    "    }",
    "",
    "    sl_gc_obj **pp = &sl_gc_all;",
    "    size_t live_count = 0;",
    "    while (*pp) {",
    "        sl_gc_obj *h = *pp;",
    "        if (!h->marked) {",
    "            *pp = h->next;",
    "            free(h);",
    "        } else {",
    "            h->marked = 0;",
    "            pp = &h->next;",
    "            live_count++;",
    "        }",
    "    }",
    "    sl_gc_set_rebuild(live_count);",
    "    free(snap);",
    "",
    "    sl_gc_bytes_since_collect = 0;",
    "    atomic_store_explicit(&sl_gc_collect_pending, 0, memory_order_release);",
    "    atomic_store_explicit(&sl_gc_stop_requested, 0, memory_order_release);",
    "    atomic_store_explicit(&sl_gc_collecting, 0, memory_order_release);",
    "    pthread_mutex_unlock(&sl_gc_mu);",
    "}",
    "",
};

const int RUNTIME_GC_LEN = sizeof(RUNTIME_GC) / sizeof(RUNTIME_GC[0]);
