/* Tier 11, second slice: the scheduler's own foundation -- a shared
 * run queue plus a small worker pool of OS threads pulling sl_task off
 * it, using the already-landed sl_ctx_switch/sl_task_stack_init
 * mechanism (runtime_sched.c) to actually run them. Third slice: wired
 * for real -- stmt.c's ST_SPAWN now calls sl_task_submit instead of
 * pthread_create, and main() (program.c) calls sl_pool_start once,
 * before any user code runs. Validated standalone first (scratchpad
 * spike: TSan-clean, UBSan-clean, tests targeting every review-found
 * bug, including two found only empirically by a dedicated stress
 * test, not by review) before landing any of it; see the Tier 11 plan
 * for the full writeup of every finding. */

#include "internal.h"

const char *RUNTIME_POOL[] = {
"/* Tier 11: run queue + worker pool. The registry fix (top_ptr ->",
" * task_slot double indirection) this design depends on for",
" * correctness under worker reuse is a separate change to",
" * sl_gc_thread/sl_gc_collect (runtime_gc.c); see that file's own",
" * comments. */",
"",
"/* sl_runq and sl_global_runq are defined earlier, in RUNTIME[]",
" * (runtime_core.c) -- sl_gc_collect needs the complete type and the",
" * variable itself at its own definition site, well before this file",
" * is emitted. See the comment there for the full reasoning;",
" * everything below just uses them, it doesn't redefine them. One",
" * global queue (not a per-caller parameter) matches the plan's own",
" * design and the validated spike exactly. sl_global_runq is statically",
" * initialized there (PTHREAD_MUTEX_INITIALIZER/PTHREAD_COND_INITIALIZER,",
" * matching sl_gc_mu's own style) -- no separate init call needed. */",
"",
"static void sl_runq_push(sl_runq *q, sl_task *t) {",
"    pthread_mutex_lock(&q->mu);",
"    t->next = NULL;",
"    if (q->tail) q->tail->next = t; else q->head = t;",
"    q->tail = t;",
"    pthread_cond_signal(&q->not_empty);",
"    pthread_mutex_unlock(&q->mu);",
"}",
"",
"static sl_task *sl_runq_pop_blocking(sl_runq *q) {",
"    pthread_mutex_lock(&q->mu);",
"    while (!q->head && !q->shutdown) {",
"        /* An idle worker is the pool's own steady state -- it must",
"         * tell the collector it's safe to scan around while parked",
"         * here, exactly like sl_chan_send/recv already do (",
"         * runtime_core.c), or a collection landing while the pool is",
"         * idle hangs forever (sl_gc_collect's quiescence wait requires",
"         * every registered thread to be either blocked or acked). */",
"        atomic_store_explicit(&sl_rt_gc_blocked, 1, memory_order_release);",
"        pthread_cond_wait(&q->not_empty, &q->mu);",
"        atomic_store_explicit(&sl_rt_gc_blocked, 0, memory_order_release);",
"        /* Waking here (something was pushed, or shutdown) does NOT mean",
"         * it's safe to act on q->head yet. This thread's OWN quiescence",
"         * requirement was satisfied while it sat blocked=1, but a",
"         * collector that already scanned this thread's (idle) task_slot",
"         * during its per-task mark loop has no reason to scan it again",
"         * this cycle -- reproduced directly (spike stress test, Tier 11",
"         * plan) as: a worker wakes, dequeues, and assigns a task",
"         * WITHOUT re-checking stop_requested, landing that task in a",
"         * slot a collection's mark phase already passed, while the",
"         * task is simultaneously no longer visible via the run-queue",
"         * walk either (it was just pulled out from under it). Checking",
"         * in HERE -- after waking, before touching q->head again, with",
"         * q->mu released so this can't deadlock against a collection",
"         * that needs it -- correctly acks (or ack-and-waits out a",
"         * still-in-flight collection) before this thread may dequeue.",
"         * The task stays safely queued (protected by the run-queue",
"         * walk) for the entire time this might block. */",
"        pthread_mutex_unlock(&q->mu);",
"        sl_rt_gc_checkin();",
"        pthread_mutex_lock(&q->mu);",
"    }",
"    sl_task *t = q->head;",
"    if (t) { q->head = t->next; if (!q->head) q->tail = NULL; }",
"    pthread_mutex_unlock(&q->mu);",
"    /* No checkin here anymore: it used to run right after this unlock,",
"     * which left t unrooted (popped off the queue, but not yet assigned",
"     * to sl_rt_current_task by the caller) for the duration of that",
"     * checkin call. Moved to sl_worker_loop, after the assignment,",
"     * closing the window instead of narrowing it -- see there. */",
"    return t;",
"}",
"",
"/* Not called from anywhere yet -- program.c's own main() emission",
" * always ends by calling exit() directly (sl_main_task_entry), which",
" * tears down every OS thread, pool workers included, without needing",
" * a graceful queue shutdown first. A real caller belongs to the",
" * deferred signal-handling redesign, not improvised here; kept",
" * (rather than deleted) since the pool's own tests already depend on",
" * it directly and it isn't dead in the sense sl_gc_cleanup_handler",
" * was -- there IS a real future caller, just not yet. */",
"__attribute__((unused))",
"static void sl_runq_shutdown(sl_runq *q) {",
"    pthread_mutex_lock(&q->mu);",
"    q->shutdown = 1;",
"    /* broadcast, not signal -- a signal wakes exactly one worker, the",
"     * rest sleep forever and pthread_join hangs. Setting the flag",
"     * under the same lock pop_blocking checks it under closes the",
"     * standard lost-wakeup window. Does not drain: any task still",
"     * queued when shutdown is called is simply never run -- a real",
"     * drain policy belongs to the deferred signal-handling redesign,",
"     * not improvised here. */",
"    pthread_cond_broadcast(&q->not_empty);",
"    pthread_mutex_unlock(&q->mu);",
"}",
"",
"static void sl_task_submit(void (*entry)(void *), void *arg) {",
"    sl_task *t = (sl_task *)malloc(sizeof(sl_task));",
"    /* Direct exit, not sl_rt_error -- the calling thread's own",
"     * sl_rt_current_task is NOT t (t doesn't exist yet), so a panic-",
"     * switch-back here would incorrectly abandon the CALLER's task.",
"     * See sl_task_stack_init's own comment (runtime_sched.c) for the",
"     * full reasoning; matches sl_gc_set_grow's OOM convention. */",
"    if (!t) {",
"        fprintf(stderr, \"slang: out of memory submitting task\\n\");",
"        exit(1);",
"    }",
"    memset(t, 0, sizeof(*t));",
"    sl_task_stack_init(t, entry, arg);",
"    t->entry_arg = arg; /* rooted directly by the collector's run-queue",
"                            walk while queued -- see sl_gc_collect,",
"                            runtime_gc.c */",
"    sl_runq_push(&sl_global_runq, t);",
"}",
"",
"static void *sl_worker_loop(void *arg) {",
"    (void)arg;",
"    sl_gc_register_thread();",
"    for (;;) {",
"        /* checkin BEFORE touching the queue at all -- as long as",
"         * nothing between two checkin calls itself yields a checkin/ack",
"         * opportunity, no collection can reach quiescence (let alone",
"         * mark phase) while this thread is anywhere inside the",
"         * pop+assign stretch below, regardless of what it's doing. This",
"         * makes pop+assign atomic with respect to collections by",
"         * construction, not by narrowing a window -- see",
"         * sl_runq_pop_blocking's own comment for the empirically-found",
"         * race this closes (Tier 11 plan). */",
"        sl_rt_gc_checkin();",
"        sl_task *t = sl_runq_pop_blocking(&sl_global_runq);",
"        if (t) sl_rt_current_task = t;",
"        if (!t) break; /* shutdown */",
"        sl_ctx_switch(&sl_rt_native_rsp, t->rsp);",
"        /* resumes here once t finishes (this slice: only ever",
"           finishes, never parks and resumes elsewhere) */",
"        sl_rt_current_task = &sl_rt_task_storage; /* MUST happen before",
"            the frees below, not after: the registry's task_slot",
"            dereferences through sl_rt_current_task at any time,",
"            including while this worker sits idle in the next",
"            pop_blocking call, so it can never be left pointing at",
"            memory about to be freed. */",
"        void *raw = t->raw_base;",
"        free(raw);",
"        free(t);",
"    }",
"    sl_gc_unregister_thread(); /* this loop can only be left via",
"        shutdown, at which point this OS thread is about to exit for",
"        good -- omitting this would leave a registry node pointing at",
"        TLS about to be torn down. */",
"    return NULL;",
"}",
"",
"/* Fixed-capacity worker array -- generous, not sized to any real",
" * machine's core count; sl_pool_start's own floor/sysconf logic below",
" * is what actually decides how many of these get used. */",
"#define SL_POOL_MAX_WORKERS 256",
"static pthread_t sl_pool_workers[SL_POOL_MAX_WORKERS];",
"",
"/* Called once, from main(), before any user code (which might 'spawn')",
" * starts running -- program.c's own main() emission gates this exactly",
" * like sl_proc_install_signal_handlers() already is. Sizes the pool via",
" * sysconf(_SC_NPROCESSORS_ONLN), floored at 8: tests/proc_shutdown",
" * already has two simultaneously-BLOCKING spawned tasks today, and",
" * chan/net/time still block whichever OS thread calls them until the",
" * deferred parking work lands, so a low floor (sysconf can legitimately",
" * return 1, e.g. in a constrained container) is a live risk to an",
" * existing test, not a hypothetical one. This is an explicit stopgap,",
" * not a real fix -- the real fix is parking itself.",
" *",
" * block_signals mirrors what every per-spawn call site used to do",
" * individually (stmt.c, before this slice): block SIGTERM/SIGINT once,",
" * here, before creating any worker, so every pool worker inherits the",
" * blocked mask at creation time and keeps its own copy forever --",
" * only main()'s own thread can ever observe these signals",
" * (tests/proc_shutdown's own load-bearing requirement), exactly as",
" * before, just blocked/restored once instead of once per spawn. */",
"static void sl_pool_start(int block_signals) {",
"    long n = sysconf(_SC_NPROCESSORS_ONLN);",
"    if (n < 8) n = 8;",
"    if (n > SL_POOL_MAX_WORKERS) n = SL_POOL_MAX_WORKERS;",
"",
"    sigset_t bmask, omask;",
"    if (block_signals) {",
"        sigemptyset(&bmask);",
"        sigaddset(&bmask, SIGTERM);",
"        sigaddset(&bmask, SIGINT);",
"        pthread_sigmask(SIG_BLOCK, &bmask, &omask);",
"    }",
"    for (long i = 0; i < n; i++) {",
"        if (pthread_create(&sl_pool_workers[i], NULL, sl_worker_loop, NULL) != 0) {",
"            fprintf(stderr, \"slang: failed to start worker pool\\n\");",
"            exit(1);",
"        }",
"    }",
"    if (block_signals) pthread_sigmask(SIG_SETMASK, &omask, NULL);",
"}",
"",
};

const int RUNTIME_POOL_LEN = sizeof(RUNTIME_POOL) / sizeof(RUNTIME_POOL[0]);
