/* Tier 11, second slice: the scheduler's own foundation -- a shared
 * run queue plus a small worker pool of OS threads pulling sl_task off
 * it, using the already-landed sl_ctx_switch/sl_task_stack_init
 * mechanism (runtime_sched.c) to actually run them. Third slice: wired
 * for real -- stmt.c's ST_SPAWN now calls sl_task_submit instead of
 * pthread_create, and main() (program.c) calls sl_pool_start once,
 * before any user code runs. Fourth slice: sl_task_park/sl_task_resume
 * and the shared sl_worker_after_switch dispatch let a task give up its
 * OS thread entirely instead of blocking it -- chan_send/chan_recv
 * (runtime_core.c, RUNTIME_CONTAINERS) are the first callers; net/time
 * will reuse the same primitives later. Validated standalone first
 * (scratchpad spike: TSan-clean, UBSan-clean, tests targeting every
 * review-found bug, including several found only empirically by
 * dedicated stress/regression tests, not by review alone) before
 * landing any of it; see the Tier 11 plan for the full writeup of every
 * finding. Seventh slice: cooperative preemption v1 -- sl_task_yield_now
 * lets a task give up its OS thread voluntarily (not just when it
 * blocks) once it's run long enough with someone else waiting, driven
 * by sl_rt_maybe_yield (runtime_core.c) at every loop back-edge and
 * every root-bearing call site. An independent design review caught a
 * real race in the first draft (pushing onto the run queue before
 * sl_ctx_switch had written the task's own rsp -- see
 * sl_task_yield_now's own comment for the full story) before any of it
 * was implemented; see the Tier 11 plan for the complete writeup. */

#include "internal.h"

const char *RUNTIME_POOL[] = {
"/* Tier 11: run queue + worker pool. The registry fix (top_ptr ->",
" * task_slot double indirection) this design depends on for",
" * correctness under worker reuse is a separate change to",
" * sl_gc_thread/sl_gc_collect (runtime_gc.c); see that file's own",
" * comments. */",
"",
"/* sl_runq and sl_global_runq are defined earlier, in RUNTIME[]",
" * (runtime_core.c) -- sl_gc_collect needs the complete type and the",
" * variable itself at its own definition site, well before this file",
" * is emitted. See the comment there for the full reasoning;",
" * everything below just uses them, it doesn't redefine them. One",
" * global queue (not a per-caller parameter) matches the plan's own",
" * design and the validated spike exactly. sl_global_runq is statically",
" * initialized there (PTHREAD_MUTEX_INITIALIZER/PTHREAD_COND_INITIALIZER,",
" * matching sl_gc_mu's own style) -- no separate init call needed. */",
"",
"/* Tier 11 stretch (work-stealing): this thread's own worker-pool slot",
" * index, or -1 -- the same sentinel sl_worker_run_loop's own slot_idx",
" * parameter already uses for 'not a real pool worker.' Needed because",
" * sl_task_submit (below) has no other way to know which local queue",
" * (sl_worker_runq[], runtime_core.c) it should push a freshly-spawned",
" * task onto: unlike sl_worker_after_switch, it's called from arbitrary",
" * generated task-body code with no slot_idx parameter anywhere in its",
" * own call chain. Set exactly once, by sl_worker_loop, alongside its",
" * existing sl_pool_slots[].tid publish -- every OTHER thread (main's",
" * own original OS thread included) keeps the default -1, correctly",
" * falling back to sl_global_runq, matching every other -1-sentinel",
" * consumer in this file. */",
"static _Thread_local long sl_rt_my_slot_idx = -1;",
"",
"/* Tier 11 stretch (work-stealing): the pool's own idle-worker",
" * wakeup channel. Needed because sl_pool_pop_or_steal (below) has no",
" * single queue to sleep on -- it is looking at N+1 of them (its own,",
" * the global overflow queue, and every steal victim), so the",
" * per-queue not_empty condvar sl_runq_pop_blocking sleeps on cannot",
" * by itself tell it that work landed SOMEWHERE. The first version of",
" * this function handled that with a ~1ms bounded poll and no wakeup",
" * signal at all, reasoning that a bounded wait can never strand a",
" * task (worst case is ~1ms of added latency). That reasoning was",
" * correct about CORRECTNESS and wrong about COST, which is only",
" * visible by measuring rather than arguing: a completely idle",
" * 8-worker pool burned 2.78s of CPU per 10s of wall clock (~28% of a",
" * core, permanently, doing nothing) against 0.13s for the single-",
" * global-queue design it replaced, a 21x regression -- 8 workers x",
" * 1000 wakeups/sec x ~6 mutex acquisitions each, and note it is",
" * mostly SYSTEM time (0.71 user / 2.05 sys). Real programs in this",
" * repo idle exactly this way between requests (demo/main.sl,",
" * examples/httpd), so that is a genuine regression, not a synthetic",
" * one.",
" *",
" * Fixed by making the wakeup EVENT-DRIVEN and demoting the timed wait",
" * to a pure safety backstop: every push (sl_runq_push_raw, the single",
" * choke point all four pushers funnel through) signals this condvar",
" * when any worker is idle, so an idle pool is woken immediately",
" * rather than up to a poll-interval late, and the backstop interval",
" * can then be long (50ms) instead of 1ms. Measured back down to 0.20s",
" * per 10s idle against the 0.13s baseline -- i.e. the backstop costs",
" * well under 1% of a core -- while idle-pool wakeup latency stays at",
" * tens of microseconds (24-47us average, 749us worst observed), some",
" * two orders of magnitude below the backstop interval, which is the",
" * direct evidence that the signal and not the timeout is what wakes",
" * an idle worker.",
" *",
" * No lost wakeup is possible, and the argument does NOT rest on the",
" * backstop (that is what makes it safe to lengthen). Two cases, both",
" * closed by sl_pool_pop_or_steal doing its FINAL scan while already",
" * holding sl_pool_idle_mu:",
" *   (a) a pusher acquires sl_pool_idle_mu BEFORE the idle worker",
" *       does: then the push (which completed before that acquire --",
" *       see sl_pool_wake_one's placement, strictly after q->mu is",
" *       released) is already visible to the worker's own subsequent",
" *       under-the-lock scan, which therefore finds the task and never",
" *       sleeps at all.",
" *   (b) a pusher acquires it AFTER: the only way it can, since the",
" *       worker holds sl_pool_idle_mu continuously from before its",
" *       final scan, is once that worker has released the mutex INSIDE",
" *       pthread_cond_timedwait -- i.e. it is genuinely waiting, so the",
" *       signal cannot be lost.",
" * The seq_cst load/store pair on sl_pool_idle_count is what lets the",
" * common case skip sl_pool_idle_mu entirely: if a pusher's load reads",
" * 0, that store is ordered after the load, so the worker's own",
" * post-increment scan is ordered after the push and finds it.",
" *",
" * Lock order: sl_pool_wake_one is deliberately called only AFTER",
" * q->mu is released, so no thread ever holds a queue mutex and",
" * sl_pool_idle_mu at once -- the idle worker takes them in the order",
" * sl_pool_idle_mu -> q->mu (scanning under the lock), and a pusher",
" * takes q->mu and sl_pool_idle_mu strictly one after the other, never",
" * nested, so there is no cycle to deadlock on. Against sl_gc_mu the",
" * established order is unchanged and consistent (sl_gc_mu ->",
" * sl_pool_idle_mu -> q->mu): sl_task_resume already pushes while",
" * holding sl_gc_mu, and the idle worker's own sl_rt_gc_checkin() runs",
" * only after sl_pool_idle_mu is released. */",
"static pthread_mutex_t sl_pool_idle_mu = PTHREAD_MUTEX_INITIALIZER;",
"static pthread_cond_t sl_pool_idle_cv = PTHREAD_COND_INITIALIZER;",
"static _Atomic long sl_pool_idle_count = 0;",
"",
"/* Tier 11 stretch (work-stealing): pool-wide shutdown, replacing the",
" * per-queue sl_runq.shutdown scheme for pool workers specifically.",
" * Needed because a worker no longer sleeps on any one queue's condvar:",
" * it sleeps on sl_pool_idle_cv, so setting sl_runq.shutdown and",
" * broadcasting a QUEUE's not_empty (all sl_runq_shutdown could ever do)",
" * cannot wake it -- every pool worker would sleep through shutdown and",
" * pthread_join would hang. One flag checked once per idle pass, plus",
" * one broadcast on the condvar workers actually wait on, is both",
" * simpler and the only thing that can work across N+1 queues. Main's",
" * own original OS thread (slot_idx == -1) still waits on",
" * sl_global_runq.not_empty via sl_runq_pop_blocking, so",
" * sl_pool_shutdown must wake that queue too -- see there. */",
"static _Atomic int sl_pool_shutdown_flag = 0;",
"",
"/* seq_cst, not relaxed, and NOT merely an optimization: it is half of",
" * the Dekker-shaped pair described above -- pairing with",
" * sl_pool_pop_or_steal's own seq_cst increment is what makes the",
" * no-lost-wakeup argument hold while still letting the overwhelmingly",
" * common case (nobody idle) skip the mutex entirely.",
" *",
" * Called ONLY for a push that takes its queue from empty to",
" * non-empty, and that gate is what makes this affordable rather than",
" * merely correct. Signalling unconditionally puts one extra GLOBAL",
" * mutex acquisition on every push, on the hot path, which the",
" * single-global-queue design it replaced never paid -- and a fan-out",
" * producer pushes once per spawned task. An A/B against a build with",
" * this call stubbed out showed it dominating the difference on",
" * worker_fanout, which is what motivated gating it; the gate is",
" * justified by the soundness argument below independently of that.",
" *",
" * The gate is sound, not a heuristic: a worker only ever sleeps after",
" * observing sl_global_runq_count == 0 under sl_pool_idle_mu, and that",
" * counter is the exact pool-wide total of queued tasks, so a sleeping",
" * worker implies EVERY queue is empty. The next push therefore",
" * necessarily takes some queue from 0 to 1 and does signal. A push",
" * onto an already-non-empty queue cannot be the one a sleeper is",
" * waiting for, because no worker can be asleep while that queue holds",
" * anything. A worker that is merely mid-scan rather than asleep needs",
" * no signal either -- its own under-the-lock sl_global_runq_count",
" * re-check catches the push and sends it back around to rescan.",
" *",
" * Never touches t:",
" * sl_runq_push_raw's own contract is that t may already be running,",
" * finished, and freed by the time this runs. */",
"static void sl_pool_wake_one(void) {",
"    if (atomic_load_explicit(&sl_pool_idle_count, memory_order_seq_cst) <= 0)",
"        return;",
"    pthread_mutex_lock(&sl_pool_idle_mu);",
"    pthread_cond_signal(&sl_pool_idle_cv);",
"    pthread_mutex_unlock(&sl_pool_idle_mu);",
"}",
"",
"/* The push itself, with NO preempt bracket of its own -- see",
" * sl_runq_push just below for who gets the bracket and who must not.",
" * The dangerous instant is pthread_mutex_unlock: the moment it runs, t",
" * is dequeue-able by any idle worker, so t may already be running (and,",
" * if it finishes, already free()d) before this function returns.",
" * Nothing here touches t after the unlock, deliberately. */",
"static void sl_runq_push_raw(sl_runq *q, sl_task *t) {",
"    pthread_mutex_lock(&q->mu);",
"    t->next = NULL;",
"    if (q->tail) q->tail->next = t; else q->head = t;",
"    q->tail = t;",
"    q->count++;",
"    /* was_empty: this push took THIS queue from empty to non-empty, and",
"     * is therefore the only kind of push that can ever need to wake a",
"     * sleeping worker -- see the wake call at the bottom of this",
"     * function. */",
"    int was_empty = (q->count == 1);",
"    /* seq_cst, upgraded from relaxed: this counter is still only a",
"     * heuristic for sl_rt_maybe_yield and the preemption ticker (see",
"     * sl_global_runq_count's own comment, runtime_core.c), but the",
"     * work-stealing idle path now also depends on it for LIVENESS --",
"     * sl_pool_pop_or_steal re-checks it under sl_pool_idle_mu to decide",
"     * whether it is safe to sleep, and that decision is one half of a",
"     * Dekker pair with sl_pool_wake_one's own seq_cst load of",
"     * sl_pool_idle_count. Relaxed here would leave the pusher's",
"     * increment unordered against the sleeper's check, which is exactly",
"     * the ordering the no-lost-wakeup argument rests on. */",
"    atomic_fetch_add_explicit(&sl_global_runq_count, 1, memory_order_seq_cst);",
"    pthread_cond_signal(&q->not_empty);",
"    pthread_mutex_unlock(&q->mu);",
"    /* AFTER the unlock, never before -- see sl_pool_idle_mu's own",
"     * comment for both the lock-order reason and the no-lost-wakeup",
"     * argument that placement is load-bearing for. Still touches",
"     * nothing about t, preserving this function's own contract. */",
"    if (was_empty) sl_pool_wake_one();",
"}",
"",
"/* Bracketed push, for the two callers that are genuinely running a",
" * DIFFERENT task's own code on that task's own stack while they push",
" * (sl_task_submit -- spawn, pushing a brand new task; sl_task_resume --",
" * some other task waking a parked one). Those callers really can be",
" * async-preempted mid-q->mu-hold, freezing the run queue's lock held",
" * while they sit queued, so they really do need the bracket.",
" *",
" * sl_worker_after_switch's own preempted branch must NOT use this, and",
" * calls sl_runq_push_raw directly instead -- the fix for a genuine use-",
" * after-free, root-caused from a full-process deadlock. The bracket",
" * targets whatever sl_rt_current_task names, and in THAT one caller",
" * sl_rt_current_task is deliberately still t itself (kept there across",
" * the push so t is never in zero of the collector's root sources -- see",
" * that branch's own comment). So the bracket's opening increment lands",
" * on t (harmless: t isn't discoverable yet), but its matching",
" * sl_rt_preempt_enable() runs AFTER pthread_mutex_unlock has made t",
" * dequeue-able -- by which point another worker may already have",
" * dispatched t, run it to completion, and free()d it in this very same",
" * function's normal-completion branch. The decrement then lands on freed",
" * memory; worse, sl_task structs are malloc'd and freed constantly here,",
" * so that block is typically already recycled into a DIFFERENT, live",
" * sl_task, whose preempt_disable_depth is silently knocked to -1. Its",
" * next legitimate sl_rt_preempt_disable() then reads 0 instead of 1, and",
" * sl_preempt_handler -- whose whole veto is 'depth != 0' -- happily",
" * async-preempts that task in the middle of a critical section every one",
" * of this slice's brackets exists to protect.",
" *",
" * Caught in the act: concurrent_compute wedged with all nine registered",
" * threads spinning in sl_gc_ack_and_wait, sl_gc_stop_requested == 1 and",
" * sl_gc_collecting == 1, and NO thread anywhere in sl_gc_collect. The",
" * collector had been suspended mid-collection: scanning every queued",
" * task's saved stack for a return address inside sl_gc_collect found it,",
" * one task deep in a 3,870-entry run queue, async_preempted == 1, frame",
" * chain reading ...count_primes_range -> sl_rt_maybe_yield ->",
" * sl_rt_gc_checkin -> sl_gc_collect -> (libSystem) -> the preemption",
" * trampoline. It had been signalled while sl_rt_gc_checkin's own bracket",
" * was open -- only possible if its depth read 0 there, i.e. if it had",
" * been -1 on entry. Nothing would ever dispatch it again (every worker",
" * was spinning waiting for the collection it was carrying), so the",
" * process spun at ~640% CPU forever. The same stray decrement, landing",
" * on a task inside sl_gc_alloc's, sl_map_put's, or malloc's bracket",
" * instead, is a crash rather than a hang -- which is what most of the",
" * remaining intermittent SIGSEGVs were.",
" *",
" * Note the bracket was never doing any USEFUL work in that caller",
" * either: sl_worker_after_switch runs on the worker's own native stack,",
" * and sl_preempt_handler's stack-range veto already rejects any signal",
" * whose sp isn't inside the current task's own buffer. It was pure",
" * hazard. */",
"static void sl_runq_push(sl_runq *q, sl_task *t) {",
"    sl_rt_preempt_disable();",
"    sl_runq_push_raw(q, t);",
"    sl_rt_preempt_enable();",
"}",
"",
"static sl_task *sl_runq_pop_blocking(sl_runq *q) {",
"    /* Tier 11 eighth slice: bracketed entry-to-return, including the",
"     * cond_wait -- harmless while genuinely idle (sl_rt_current_task is",
"     * the thread's own idle sentinel then, never an async-preemption",
"     * target), and correctly protects the lock-held dequeue at the",
"     * bottom either way. */",
"    sl_rt_preempt_disable();",
"    pthread_mutex_lock(&q->mu);",
"    while (!q->head && !q->shutdown) {",
"        /* An idle worker is the pool's own steady state -- it must",
"         * tell the collector it's safe to scan around while parked",
"         * here, exactly like sl_chan_send/recv already do (",
"         * runtime_core.c), or a collection landing while the pool is",
"         * idle hangs forever (sl_gc_collect's quiescence wait requires",
"         * every registered thread to be either blocked or acked). */",
"        atomic_store_explicit(&sl_rt_gc_blocked, 1, memory_order_release);",
"        pthread_cond_wait(&q->not_empty, &q->mu);",
"        atomic_store_explicit(&sl_rt_gc_blocked, 0, memory_order_release);",
"        /* Waking here (something was pushed, or shutdown) does NOT mean",
"         * it's safe to act on q->head yet. This thread's OWN quiescence",
"         * requirement was satisfied while it sat blocked=1, but a",
"         * collector that already scanned this thread's (idle) task_slot",
"         * during its per-task mark loop has no reason to scan it again",
"         * this cycle -- reproduced directly (spike stress test, Tier 11",
"         * plan) as: a worker wakes, dequeues, and assigns a task",
"         * WITHOUT re-checking stop_requested, landing that task in a",
"         * slot a collection's mark phase already passed, while the",
"         * task is simultaneously no longer visible via the run-queue",
"         * walk either (it was just pulled out from under it). Checking",
"         * in HERE -- after waking, before touching q->head again, with",
"         * q->mu released so this can't deadlock against a collection",
"         * that needs it -- correctly acks (or ack-and-waits out a",
"         * still-in-flight collection) before this thread may dequeue.",
"         * The task stays safely queued (protected by the run-queue",
"         * walk) for the entire time this might block. */",
"        pthread_mutex_unlock(&q->mu);",
"        sl_rt_gc_checkin();",
"        pthread_mutex_lock(&q->mu);",
"    }",
"    sl_task *t = q->head;",
"    if (t) {",
"        q->head = t->next;",
"        if (!q->head) q->tail = NULL;",
"        q->count--;",
"        atomic_fetch_sub_explicit(&sl_global_runq_count, 1,",
"                                   memory_order_seq_cst);",
"    }",
"    pthread_mutex_unlock(&q->mu);",
"    sl_rt_preempt_enable();",
"    /* No checkin here anymore: it used to run right after this unlock,",
"     * which left t unrooted (popped off the queue, but not yet assigned",
"     * to sl_rt_current_task by the caller) for the duration of that",
"     * checkin call. Moved to sl_worker_loop, after the assignment,",
"     * closing the window instead of narrowing it -- see there. */",
"    return t;",
"}",
"",
"/* Tier 11 stretch (work-stealing): the non-blocking half of",
" * sl_runq_pop_blocking's own dequeue -- lock, check, maybe unlink,",
" * decrement sl_global_runq_count, unlock, return (NULL if empty).",
" * No wait loop, no checkin: this is the shared primitive",
" * sl_pool_pop_or_steal (below) calls three different ways -- once",
" * against a worker's own queue, once against sl_global_runq, and",
" * zero or more times against OTHER workers' queues (a steal",
" * attempt) -- all three are the exact same operation from this",
" * function's own point of view: 'take whatever is at the head of",
" * THIS queue, if anything, right now.' Bracketed like every other",
" * function that locks a queue mutex -- see sl_rt_preempt_disable's",
" * own comment (runtime_core.c) for why. */",
"static sl_task *sl_runq_try_pop(sl_runq *q) {",
"    sl_rt_preempt_disable();",
"    pthread_mutex_lock(&q->mu);",
"    sl_task *t = q->head;",
"    if (t) {",
"        q->head = t->next;",
"        if (!q->head) q->tail = NULL;",
"        q->count--;",
"        atomic_fetch_sub_explicit(&sl_global_runq_count, 1,",
"                                   memory_order_seq_cst);",
"    }",
"    pthread_mutex_unlock(&q->mu);",
"    sl_rt_preempt_enable();",
"    return t;",
"}",
"",
"/* Tier 11 stretch (work-stealing): the real per-worker dispatch loop",
" * for a genuine pool worker (slot_idx >= 0 -- main's own original OS",
" * thread, slot_idx == -1, has no local queue of its own and keeps",
" * using sl_runq_pop_blocking(&sl_global_runq) directly, unchanged,",
" * at its own one call site in sl_worker_run_loop below; see that",
" * scope note for why this design leaves it that way rather than",
" * inventing a queue for a thread that was never meant to have one).",
" *",
" * Tries, in order: this worker's own local queue, the global",
" * overflow queue, then a bounded rotation of steal attempts against",
" * OTHER workers' own queues (starting one past this worker's own",
" * slot, wrapping around -- a simple, deterministic, PRNG-free choice",
" * of victim, not a randomized one, for the same reason the rest of",
" * this codebase prefers a plain, reproducible mechanism over a",
" * fancier one wherever the fancier one isn't proven necessary).",
" *",
" * If every one of those comes back empty, this parks on the pool's",
" * shared idle condvar (sl_pool_idle_cv) until a pusher wakes it,",
" * with a 50ms timed backstop.",
" *",
" * The first version of this function had no wakeup signal at all --",
" * just a ~1ms bounded poll, on the reasoning that a bounded wait can",
" * never strand a task even if a wakeup is missed, and that this",
" * codebase's own history (chan's park/resume race, the reactor's",
" * registration-vs-kernel-readiness race) has repeatedly found",
" * 'obviously safe' cross-task wakeup reasoning wrong under real",
" * timing. That reasoning was right about correctness and wrong about",
" * cost, which only measuring exposed: an idle 8-worker pool burned",
" * ~28% of a core doing nothing (see sl_pool_idle_mu's own comment for",
" * the numbers). The wakeup signal it avoided is now here, but the",
" * bounded wait it relied on is STILL here too -- kept as a pure",
" * backstop rather than deleted in favour of the signal, precisely",
" * because of that history. The no-lost-wakeup argument is written",
" * out in full at sl_pool_idle_mu and does not depend on the",
" * backstop; the backstop is what makes it safe to be wrong about",
" * that argument. The lost-wakeup-immunity of a bounded wait was",
" * proven, not just argued, by a standalone TSan-driven spike",
" * (scratchpad/poolspike/steal_spike.c) built specifically to try to",
" * break this exact claim with adversarial timing jitter before this",
" * function was ever written for real.",
" *",
" * Checkin discipline, carried over unchanged from",
" * sl_runq_pop_blocking's own (now-retired-for-this-caller) comment:",
" * sl_worker_run_loop's own top-of-loop checkin already covers the",
" * 'pop+assign must be atomic with respect to a collection' case, so",
" * this function's only remaining job is the SEPARATE one",
" * sl_runq_pop_blocking's internal wait-loop used to handle --",
" * telling the collector this thread is safely idle (sl_rt_gc_blocked)",
" * for the span of the idle wait specifically, and checking in",
" * (with no queue mutex held) once per empty pass, not just once per",
" * dispatch, so a collection can never be stalled behind a worker",
" * that's merely searching for work rather than running any. */",
"/* Tier 11 stretch (work-stealing): move up to half of victim's",
" * backlog to this worker's own queue in ONE acquisition of the",
" * victim's mutex, and return the first of those tasks to run",
" * immediately.",
" *",
" * Stealing a single task per acquisition -- the obvious V1 choice, and",
" * what this function replaced -- is not merely slower, it plausibly",
" * makes the whole feature a net regression on the exact workload it",
" * exists for (stress_test/programs/worker_fanout: one spawned root",
" * task fanning N children onto its own local queue, the 'one hot",
" * queue, N-1 idle workers' pathology). The reason is mutex traffic,",
" * not scheduling: with steal-one, every one of the N tasks costs a",
" * separate contended lock/unlock of the producer's own queue mutex,",
" * competing directly with that producer's 2000 pushes -- strictly MORE",
" * traffic concentrated on one mutex than the single global queue ever",
" * had, plus the failed probes of every other queue on top. Taking half",
" * a backlog at a time cuts those acquisitions by the batch factor and",
" * is what makes per-worker queues actually pay for themselves. With",
" * this in place, an interleaved A/B on a quiet machine has the",
" * per-worker-queue build ahead of the single-global-queue baseline at",
" * every granularity of worker_fanout: 25% faster with many small",
" * tasks (medians 998ms vs 1329ms, ranges not even overlapping), 11%",
" * with mid-sized ones (2068ms vs 2333ms), and ~4% -- inside the noise",
" * but not a regression -- with few long ones (12520ms vs 13067ms).",
" *",
" * The batch is capped (SL_STEAL_MAX_BATCH) because the victim's mutex",
" * is held across an O(n) walk to find the split point: uncapped, a",
" * 2000-deep queue would mean a 1000-node walk under a lock the",
" * producer is actively trying to reacquire, trading one pathology for",
" * another.",
" *",
" * sl_global_runq_count is decremented by exactly ONE, not by the batch",
" * size: it counts tasks queued pool-wide, and moving n tasks between",
" * two queues does not change that total -- only the one task this",
" * function dequeues to run right now leaves the queues.",
" *",
" * Lock discipline: victim->mu and mine->mu are acquired strictly one",
" * after the other, never nested, so this introduces no new lock-order",
" * edge between two queue mutexes and cannot deadlock against another",
" * worker stealing in the opposite direction. */",
"#define SL_STEAL_MAX_BATCH 64",
"static sl_task *sl_runq_steal_half(long victim_idx, long my_idx) {",
"    sl_runq *v = &sl_worker_runq[victim_idx];",
"    sl_rt_preempt_disable();",
"    /* GC safety. Between unlinking the batch from v and splicing it",
"     * into m, those tasks are momentarily on NO queue, so",
"     * sl_gc_collect's run-queue walk could not see them and nothing",
"     * else roots them either -- not task_slot (they are not running),",
"     * not sl_parked_tasks (they are not parked). That window is real,",
"     * and it is NOT closed by locking: the collector walks one queue at",
"     * a time, so a batch can leave v after v was scanned and reach m",
"     * after m was scanned, and be missed even though it sat on some",
"     * queue at every instant. Holding both queue mutexes does not help",
"     * for the same reason.",
"     *",
"     * What makes it safe is that this function can never execute while",
"     * a collection is marking, which was verified against",
"     * sl_gc_collect's actual quiescence protocol rather than assumed.",
"     * The collector proceeds to mark only once every registered thread",
"     * is either acked-for-this-cycle or flagged sl_rt_gc_blocked, and",
"     * both states exclude this function:",
"     *   - an acked thread is parked inside sl_gc_ack_and_wait for the",
"     *     duration of the collection, not running anything;",
"     *   - the only place a worker sets sl_rt_gc_blocked is around the",
"     *     idle pthread_cond_timedwait in sl_pool_pop_or_steal, and on",
"     *     waking it clears the flag and calls sl_rt_gc_checkin() (which",
"     *     acks and waits out an in-flight collection) BEFORE it touches",
"     *     any queue again;",
"     *   - a worker already inside this scan has neither acked nor set",
"     *     blocked, so the collector's own all_ready test is false and",
"     *     it has not started marking at all.",
"     * Only sl_worker_run_loop calls this, and only on GC-registered",
"     * threads, so there is no fourth case.",
"     *",
"     * This is the same property that already makes sl_runq_try_pop's",
"     * own pop-then-assign gap safe, so it is a relied-upon invariant",
"     * here, not a new argument invented for this function.",
"     *",
"     * Deliberately NOT taking sl_gc_mu, which an earlier version of",
"     * this function did: sl_gc_mu is a hot global mutex (every",
"     * checkin, park, resume and collection needs it), and serializing",
"     * every steal through it would be paying real contention to close",
"     * a window the quiescence protocol already closes. The",
"     * justification for dropping it is the argument above, not a",
"     * benchmark. Note this is exactly why sl_task_resume",
"     * DOES need sl_gc_mu and this function does not: sl_task_resume is",
"     * also called from the timer and reactor threads, which are not",
"     * GC-registered at all and are therefore invisible to quiescence,",
"     * so nothing stops them running during a mark. Every caller of this",
"     * function is a registered pool worker. */",
"    pthread_mutex_lock(&v->mu);",
"    long n = v->count / 2;",
"    if (n < 1) n = v->count > 0 ? 1 : 0;",
"    if (n > SL_STEAL_MAX_BATCH) n = SL_STEAL_MAX_BATCH;",
"    if (n == 0) {",
"        pthread_mutex_unlock(&v->mu);",
"        sl_rt_preempt_enable();",
"        return NULL;",
"    }",
"    sl_task *first = v->head;",
"    sl_task *last = first;",
"    for (long i = 1; i < n; i++) last = last->next;",
"    v->head = last->next;",
"    if (!v->head) v->tail = NULL;",
"    v->count -= n;",
"    pthread_mutex_unlock(&v->mu);",
"    last->next = NULL;",
"    sl_task *rest = first->next;",
"    first->next = NULL;",
"    if (rest) {",
"        sl_runq *m = &sl_worker_runq[my_idx];",
"        pthread_mutex_lock(&m->mu);",
"        if (m->tail) m->tail->next = rest; else m->head = rest;",
"        m->tail = last;",
"        m->count += (n - 1);",
"        pthread_mutex_unlock(&m->mu);",
"    }",
"    atomic_fetch_sub_explicit(&sl_global_runq_count, 1,",
"                               memory_order_seq_cst);",
"    sl_rt_preempt_enable();",
"    return first;",
"}",
"",
"/* One full search pass: this worker's own local queue, then the",
" * global overflow queue, then a bounded rotation of steal attempts",
" * against other workers' queues. Factored out because",
" * sl_pool_pop_or_steal runs it twice per idle iteration and the two",
" * runs must be identical. Must never be called while holding",
" * sl_pool_idle_mu: it can reach sl_gc_mu via sl_runq_steal_half, and a",
" * pusher already takes sl_pool_idle_mu while holding sl_gc_mu (",
" * sl_task_resume -> sl_runq_push -> sl_pool_wake_one), so doing so",
" * would close a genuine lock cycle. The old second",
" * what closes the lost-wakeup case, and it only closes it if it looks",
" * in exactly the same places the pusher could have pushed to. */",
"static sl_task *sl_pool_scan_all(long slot_idx) {",
"    sl_task *t = sl_runq_try_pop(&sl_worker_runq[slot_idx]);",
"    if (t) return t;",
"    t = sl_runq_try_pop(&sl_global_runq);",
"    if (t) return t;",
"    /* EVERY other worker, not a capped prefix of the rotation. The",
"     * first version of this capped attempts at min(4, others), which",
"     * is a real starvation bug rather than a tuning choice: with the",
"     * victim chosen as (slot_idx + 1 + a), worker j only ever probes",
"     * j+1..j+4, so for a hot queue at slot r only workers r-1..r-4 can",
"     * ever reach it. At the default 8-worker pool that leaves three",
"     * workers structurally unable to steal from r at all -- they sit",
"     * idle no matter how deep r's queue gets. That is precisely the",
"     * fan-out-from-one-worker pathology this whole feature exists to",
"     * fix, so the cap defeated the feature on its own motivating",
"     * workload (stress_test/programs/worker_fanout): only about five",
"     * of eight workers could ever obtain work at all. Note this one is",
"     * arithmetic, not a benchmark result -- j probes exactly j+1..j+4,",
"     * so a hot queue at r is unreachable from three of eight slots no",
"     * matter what any timing run says.",
"     *",
"     * The cap existed to bound the cost of a scan, which mattered when",
"     * an idle worker ran this loop ~1000 times a second. It no longer",
"     * does: since the wakeup became event-driven (see sl_pool_idle_mu),",
"     * an idle worker scans only when a push actually wakes it or the",
"     * 50ms backstop fires, so a full sweep of N-1 uncontended try-locks",
"     * is paid rarely rather than continuously. Correctness of the",
"     * scan's coverage is worth far more here than trimming it. */",
"    for (long a = 1; a < sl_pool_num_workers; a++) {",
"        long victim = (slot_idx + a) % sl_pool_num_workers;",
"        t = sl_runq_steal_half(victim, slot_idx);",
"        if (t) return t;",
"    }",
"    return NULL;",
"}",
"",
"static sl_task *sl_pool_pop_or_steal(long slot_idx) {",
"    for (;;) {",
"        /* Fast path: no sl_pool_idle_mu traffic at all for a worker",
"         * that finds work immediately, which is the whole steady state",
"         * of a busy pool. */",
"        sl_task *t = sl_pool_scan_all(slot_idx);",
"        if (t) return t;",
"        sl_rt_preempt_disable();",
"        /* Announce 'about to sleep' BEFORE the final scan, seq_cst --",
"         * the other half of sl_pool_wake_one's own Dekker pair. */",
"        atomic_fetch_add_explicit(&sl_pool_idle_count, 1, memory_order_seq_cst);",
"        int shutdown = atomic_load_explicit(&sl_pool_shutdown_flag,",
"                                            memory_order_acquire);",
"        pthread_mutex_lock(&sl_pool_idle_mu);",
"        /* The final re-check runs UNDER sl_pool_idle_mu -- that is what",
"         * makes a signal impossible to lose: a pusher can only reach",
"         * the signal by acquiring this same mutex, so it either got",
"         * here first (and this re-check observes its task) or it cannot",
"         * get here until this thread is genuinely inside",
"         * pthread_cond_timedwait. See sl_pool_idle_mu's own comment.",
"         *",
"         * It re-checks sl_global_runq_count -- an O(1) atomic load --",
"         * rather than re-running sl_pool_scan_all's full N+1-queue",
"         * sweep, and that is a correctness-preserving performance fix,",
"         * not a shortcut. The count is maintained by every push and",
"         * every pop across ALL queues (sl_runq_push_raw /",
"         * sl_runq_try_pop / sl_runq_pop_blocking), and each push",
"         * increments it under that queue's own mutex BEFORE the unlock",
"         * that precedes sl_pool_wake_one -- so 'a task exists that this",
"         * thread has not yet seen' implies 'the count is nonzero here',",
"         * which is exactly the property the argument above needs.",
"         *",
"         * Scanning under this lock instead was a real, measured",
"         * regression: every idle worker serialized a full 8-queue sweep",
"         * through this one mutex, and because a pusher must also take",
"         * it to signal, the fan-out producer got throttled behind those",
"         * sweeps -- worker_fanout ran 3.2-5.2s (wildly variable) versus",
"         * ~2.6s for the single-global-queue design. Keeping the",
"         * critical section O(1) keeps the no-lost-wakeup argument",
"         * intact while making it nearly free. A false positive here",
"         * (count nonzero but every queue empty by the time this thread",
"         * looks again) costs one extra scan, never a stranded task. */",
"        if (atomic_load_explicit(&sl_global_runq_count,",
"                                 memory_order_seq_cst) > 0) {",
"            pthread_mutex_unlock(&sl_pool_idle_mu);",
"            atomic_fetch_sub_explicit(&sl_pool_idle_count, 1, memory_order_seq_cst);",
"            sl_rt_preempt_enable();",
"            continue;",
"        }",
"        if (!shutdown) {",
"            /* Tell the collector this thread is safely idle for the",
"             * span of the wait specifically -- exactly the discipline",
"             * sl_runq_pop_blocking's own cond_wait already established,",
"             * or a collection landing while the pool is idle hangs",
"             * waiting for quiescence this thread would never reach. */",
"            atomic_store_explicit(&sl_rt_gc_blocked, 1, memory_order_release);",
"            struct timespec ts;",
"            clock_gettime(CLOCK_REALTIME, &ts);",
"            ts.tv_nsec += 50000000; /* 50ms -- a pure backstop now, not",
"                the wakeup mechanism; sl_pool_wake_one does the real",
"                waking. Long on purpose: at 1ms this cost ~28% of a",
"                core per idle pool, measured. */",
"            if (ts.tv_nsec >= 1000000000L) { ts.tv_sec++; ts.tv_nsec -= 1000000000L; }",
"            pthread_cond_timedwait(&sl_pool_idle_cv, &sl_pool_idle_mu, &ts);",
"            atomic_store_explicit(&sl_rt_gc_blocked, 0, memory_order_release);",
"        }",
"        pthread_mutex_unlock(&sl_pool_idle_mu);",
"        atomic_fetch_sub_explicit(&sl_pool_idle_count, 1, memory_order_seq_cst);",
"        sl_rt_preempt_enable();",
"        /* Checkin with no mutex held -- once per empty pass, not just",
"         * once per dispatch, so a collection is never stalled behind a",
"         * worker that is merely searching for work rather than running",
"         * any. */",
"        sl_rt_gc_checkin();",
"        if (shutdown) return NULL;",
"        /* loop back and retry own -> global -> steal from scratch --",
"           whatever woke this thread (a real push, the backstop timeout,",
"           or nothing at all) is handled identically: just look again */",
"    }",
"}",
"",
"/* Not called from anywhere yet -- program.c's own main() emission",
" * always ends by calling exit() directly (sl_main_task_entry), which",
" * tears down every OS thread, pool workers included, without needing",
" * a graceful queue shutdown first. A real caller belongs to the",
" * deferred signal-handling redesign, not improvised here; kept",
" * (rather than deleted) since the pool's own tests already depend on",
" * it directly and it isn't dead in the sense sl_gc_cleanup_handler",
" * was -- there IS a real future caller, just not yet. */",
"__attribute__((unused))",
"/* Tier 11 stretch (work-stealing): the pool-wide counterpart to",
" * sl_runq_shutdown, and the one a real caller should use -- see",
" * sl_pool_shutdown_flag's own comment for why per-queue shutdown alone",
" * cannot stop a worker that sleeps on sl_pool_idle_cv rather than on",
" * any queue. Sets the flag, then wakes BOTH places a thread in this",
" * pool can be blocked: sl_pool_idle_cv (every real pool worker) and",
" * sl_global_runq.not_empty (main's own original OS thread, slot_idx ==",
" * -1, which still uses sl_runq_pop_blocking). Broadcast, not signal, on",
" * both -- a signal wakes exactly one waiter and the rest sleep through",
" * shutdown forever, the same trap sl_runq_shutdown's own comment",
" * already records. Like sl_runq_shutdown it does not drain: tasks still",
" * queued are simply never run, a real drain policy being the deferred",
" * signal-handling redesign's business, not this function's. Still no",
" * caller today, for the same reason sl_runq_shutdown has none --",
" * generated main() exits via exit(), tearing every thread down without",
" * a graceful pool shutdown -- but unlike before, the machinery a future",
" * caller needs now actually works across all N+1 queues. */",
"__attribute__((unused))",
"static void sl_pool_shutdown(void) {",
"    atomic_store_explicit(&sl_pool_shutdown_flag, 1, memory_order_release);",
"    pthread_mutex_lock(&sl_pool_idle_mu);",
"    pthread_cond_broadcast(&sl_pool_idle_cv);",
"    pthread_mutex_unlock(&sl_pool_idle_mu);",
"    pthread_mutex_lock(&sl_global_runq.mu);",
"    sl_global_runq.shutdown = 1;",
"    pthread_cond_broadcast(&sl_global_runq.not_empty);",
"    pthread_mutex_unlock(&sl_global_runq.mu);",
"}",
"",
"static void sl_runq_shutdown(sl_runq *q) {",
"    pthread_mutex_lock(&q->mu);",
"    q->shutdown = 1;",
"    /* broadcast, not signal -- a signal wakes exactly one worker, the",
"     * rest sleep forever and pthread_join hangs. Setting the flag",
"     * under the same lock pop_blocking checks it under closes the",
"     * standard lost-wakeup window. Does not drain: any task still",
"     * queued when shutdown is called is simply never run -- a real",
"     * drain policy belongs to the deferred signal-handling redesign,",
"     * not improvised here. */",
"    pthread_cond_broadcast(&q->not_empty);",
"    pthread_mutex_unlock(&q->mu);",
"}",
"",
"static void sl_task_submit(void (*entry)(void *), void *arg) {",
"    /* Tier 11 eighth slice: protects the CALLING task across this raw",
"     * malloc -- same class of bug as sl_gc_alloc's own bracket (an",
"     * async-preempted, migrated task abandoning libSystem's own",
"     * thread-affine zone lock mid-hold). sl_task_stack_init/",
"     * sl_runq_push below already bracket themselves. */",
"    sl_rt_preempt_disable();",
"    sl_task *t = (sl_task *)malloc(sizeof(sl_task));",
"    sl_rt_preempt_enable();",
"    /* Direct exit, not sl_rt_error -- the calling thread's own",
"     * sl_rt_current_task is NOT t (t doesn't exist yet), so a panic-",
"     * switch-back here would incorrectly abandon the CALLER's task.",
"     * See sl_task_stack_init's own comment (runtime_sched.c) for the",
"     * full reasoning; matches sl_gc_set_grow's OOM convention. */",
"    if (!t) {",
"        fprintf(stderr, \"slang: out of memory submitting task\\n\");",
"        exit(1);",
"    }",
"    memset(t, 0, sizeof(*t));",
"    sl_task_stack_init(t, entry, arg);",
"    t->entry_arg = arg; /* rooted directly by the collector's run-queue",
"                            walk while queued -- see sl_gc_collect,",
"                            runtime_gc.c */",
"    /* Tier 11 stretch (work-stealing): push to the SPAWNING worker's own",
"     * local queue when there is one, not unconditionally to",
"     * sl_global_runq -- for locality (a newly-spawned task very often",
"     * relates to work the spawning task is already doing, so landing it",
"     * on the same worker's own queue means whichever worker picks it up",
"     * next is either this one, cheaply, once t's own work is ready, or",
"     * another one stealing it, exactly the intended tradeoff). Falls",
"     * back to the shared overflow queue when there is no local queue to",
"     * use (sl_rt_my_slot_idx == -1 -- main's own original OS thread, the",
"     * only caller context that doesn't have one). Root-visibility for",
"     * entry_arg is unaffected either way -- it comes entirely from the",
"     * CALLER's own safepoint bracket around this call (core.c's",
"     * wrap_safepoint), not from which queue t lands in. */",
"    sl_runq_push(sl_rt_my_slot_idx >= 0",
"                     ? &sl_worker_runq[sl_rt_my_slot_idx]",
"                     : &sl_global_runq,",
"                 t);",
"}",
"",
"/* Tier 11 fourth slice: generic park/resume primitives -- the pieces",
" * chan_send/recv (RUNTIME_CONTAINERS) park through, and every future",
" * net/time parking site will too. Caller contract for sl_task_park:",
" * sl_rt_current_task must already be registered wherever it needs to",
" * be found for wakeup (e.g. a channel's own wait list, via its `next`",
" * field) AND the caller must currently hold held_mu -- the SAME lock",
" * protecting that registration. This function does NOT unlock held_mu",
" * itself: a parked task cannot use a plain condvar-style 'unlock, then",
" * block' sequence, since sl_ctx_switch has no equivalent of a condvar",
" * wait's OS-guaranteed atomic unlock-and-block. Unlocking here, before",
" * the switch, would open a lost-wakeup race -- a concurrent",
" * sl_task_resume could find this task on its wait list and try to",
" * switch into t->rsp BEFORE the switch below has actually written it.",
" * held_mu stays locked across the switch instead, and is only unlocked",
" * by sl_worker_after_switch, once, immediately after the switch",
" * safely completes -- on this SAME OS thread (the task's own code",
" * locks it; that same physical thread, now running scheduler code,",
" * unlocks it a few instructions later), so this never violates",
" * POSIX's per-thread mutex-ownership rule despite the task having",
" * logically moved from application code to scheduler code in",
" * between. */",
"static void sl_task_park(pthread_mutex_t *held_mu) {",
"    /* Tier 11 eighth slice: bracketed entry through the switch's own",
"     * resume point, not just the sl_gc_mu-held stretch -- protects the",
"     * whole park-registration-then-switch-out transition, the same",
"     * shape sl_task_yield_now/the async trampoline itself use for the",
"     * identical class of mid-transition hazard. */",
"    sl_rt_preempt_disable();",
"    pthread_mutex_lock(&sl_gc_mu);",
"    sl_rt_current_task->parked_next = sl_parked_tasks;",
"    sl_parked_tasks = sl_rt_current_task;",
"    pthread_mutex_unlock(&sl_gc_mu);",
"    sl_rt_current_task->park_mu = held_mu;",
"    sl_rt_current_task->parked = 1;",
"    sl_ctx_switch(&sl_rt_current_task->rsp, sl_rt_native_rsp);",
"    /* resumes here once re-submitted (sl_task_resume) and re-switched-",
"       into by some worker */",
"    sl_rt_preempt_enable();",
"}",
"",
"/* Called by whoever finds a match (e.g. sl_chan_send finding a waiting",
" * receiver) while still holding the SAME lock that protects the",
" * primitive-specific wait list t was just removed from -- t->next is",
" * free to reuse the moment this is called.",
" *",
" * sl_gc_mu stays locked across BOTH the sl_parked_tasks removal and",
" * the sl_runq_push call below -- unlocking in between (the original,",
" * buggy shape) leaves a real window where t is registered in NONE of",
" * the collector's three root sources (not on sl_parked_tasks anymore,",
" * not yet on sl_global_runq, and not any registered thread's",
" * task_slot either, since t isn't running on any OS thread right",
" * now). A collection landing in that exact window walks all three",
" * sources, finds t nowhere, and never marks t->entry_arg or t's",
" * safepoint chain -- silently collecting whatever GC objects t alone",
" * still references (e.g. a value just received via chan_recv,",
" * sitting in t's own safepoint roots, waiting for t to resume and use",
" * it) out from under it. Reproduced directly via a standalone",
" * chan_recv-parking stress case (many workers pulling off a shared",
" * chan under real GC pressure): a received struct's own fields read",
" * back as changed-in-place moments after receipt, sometimes read as a",
" * heap pointer, sometimes zeroed -- exactly the signature of another",
" * allocation's malloc() call reusing memory this task still legitimately",
" * held live. Extending sl_gc_mu's hold across sl_runq_push closes the",
" * window entirely: t is always in at least one of the three sources.",
" * Safe against deadlock because the established lock order in this",
" * runtime is always sl_gc_mu-then-runq-mu (see sl_gc_collect's own",
" * comment, runtime_gc.c) -- sl_runq_push only ever takes q->mu, never",
" * sl_gc_mu, so acquiring it while already holding sl_gc_mu here",
" * matches the same order, not a new or reversed one.",
" *",
" * Only half the story on its own, though: closing this window makes t",
" * visible to the run-queue walk, and that walk had to start scanning a",
" * queued task's SAFEPOINT CHAIN too before being visible there meant",
" * anything for a resumed task (it used to mark entry_arg only, on the",
" * -- true until this slice -- assumption that a queued task hasn't",
" * started running and so has no chain). Same failure signature, same",
" * repro; see sl_gc_collect's run-queue walk (runtime_gc.c). */",
"static void sl_task_resume(sl_task *t) {",
"    /* Tier 11 eighth slice: protects the CALLING thread's own current",
"     * task (sl_rt_current_task) -- t itself isn't running anywhere",
"     * right now, so it isn't a preemption target; whoever is executing",
"     * this function's own lock manipulation is. sl_runq_push below",
"     * takes its own nested bracket too (harmless, composes). */",
"    sl_rt_preempt_disable();",
"    pthread_mutex_lock(&sl_gc_mu);",
"    sl_task **pp = &sl_parked_tasks;",
"    while (*pp) {",
"        if (*pp == t) { *pp = t->parked_next; break; }",
"        pp = &(*pp)->parked_next;",
"    }",
"    sl_runq_push(&sl_global_runq, t);",
"    pthread_mutex_unlock(&sl_gc_mu);",
"    sl_rt_preempt_enable();",
"}",
"",
"/* Tier 11 seventh slice: cooperative preemption's own yield primitive --",
" * called from sl_rt_maybe_yield (runtime_core.c) once a task decides",
" * it's run long enough, with someone else waiting, to give up its OS",
" * thread voluntarily. Deliberately does NOT push t onto sl_global_runq",
" * itself before switching out -- a design review caught a real,",
" * TSan-would-catch-it race in an earlier draft that did exactly that:",
" * sl_ctx_switch only writes *old_rsp_slot (here, &t->rsp) AFTER saving",
" * this thread's own callee-saved registers, so pushing t first makes it",
" * visible to sl_runq_pop_blocking (and thus dequeue-able by a DIFFERENT",
" * idle worker) while t->rsp still holds a STALE value from t's previous",
" * switch-out -- that worker can then sl_ctx_switch into a stale rsp",
" * while THIS thread is still physically executing on t's stack,",
" * corrupting it (or, for a task on its very first-ever stint, whose rsp",
" * was never yet written by a real switch-out at all, re-entering its",
" * trampoline from the top on a stack this thread is mid-execution on).",
" * Exactly the same hazard sl_task_park's own comment above documents",
" * for held_mu and the parked-task registry -- the fix here is the same",
" * shape: don't make t discoverable until AFTER the switch has safely",
" * completed. sl_worker_after_switch does the push instead, once this",
" * function's sl_ctx_switch call has returned control to some OTHER",
" * thread's worker loop -- at which point t->rsp is guaranteed valid. */",
"static void sl_task_yield_now(void) {",
"    /* Tier 11 eighth slice: bracketed entry through the switch's own",
"     * resume point -- this is the COOPERATIVE yield path (called",
"     * directly from generated code via sl_rt_maybe_yield, never through",
"     * sl_preempt_handler), and it's exactly as vulnerable to a second,",
"     * async signal landing mid-transition as the async path's own",
"     * trampoline is -- nothing about being a voluntary yield makes the",
"     * switch-out/switch-back-in window any safer. */",
"    sl_rt_preempt_disable();",
"    sl_task *t = sl_rt_current_task;",
"    t->preempted = 1;",
"    sl_ctx_switch(&t->rsp, sl_rt_native_rsp);",
"    /* resumes here once some worker's run loop dispatches this task",
"       again -- run_start_ns is reset fresh by that dispatch (see",
"       sl_worker_run_loop below), so the next sample-interval check",
"       starts counting from zero, not from this task's pre-yield start",
"       time. */",
"    sl_rt_preempt_enable();",
"}",
"",
"/* Shared post-switch dispatch: must run identically after ANY",
" * sl_ctx_switch call that could return either a finished OR a parked",
" * task -- not just the ones sl_worker_run_loop's own iteration makes.",
" * main()'s own one-off switch-in (program.c) uses this too, since",
" * main's top-level task can now park exactly like any spawned task",
" * can. */",
"/* Tier 11 stretch (work-stealing): slot_idx parameter added -- the",
" * preempted branch below needs it to know which local queue (if any)",
" * to push t back onto. Same -1 sentinel as sl_worker_run_loop's own",
" * (which passes its own slot_idx straight through, unchanged) and",
" * program.c's one-off call for main's own top-level task (passes -1",
" * literally, since that thread never has a real slot). */",
"static void sl_worker_after_switch(sl_task *t, long slot_idx) {",
"    if (t->preempted) {",
"        /* Tier 11 seventh slice: t's sl_ctx_switch has already safely",
"         * completed by the time we're running here (this IS the code",
"         * that ran right after that switch), so t->rsp is guaranteed",
"         * valid -- now it's safe to make t discoverable again. Push",
"         * BEFORE clearing sl_rt_current_task, not after: t stays",
"         * reachable via this thread's own task_slot (which dereferences",
"         * sl_rt_current_task, still == t here) for the whole push, so",
"         * it's in >=1 of the collector's three root sources at every",
"         * instant -- clearing first would open exactly the zero-source",
"         * window sl_task_resume's own comment above describes. */",
"        t->preempted = 0;",
"        /* Deliberately does NOT clear t->async_preempted here, and that",
"         * asymmetry with t->preempted just above is the whole point --",
"         * an earlier version of this slice did clear it here and thereby",
"         * silently disabled sl_gc_collect's conservative scan",
"         * (runtime_gc.c) entirely, which is the ONLY thing covering the",
"         * alloc-to-store gap async preemption opens. The two flags",
"         * answer different questions. t->preempted asks 'which of",
"         * sl_worker_after_switch's three branches should run', and is",
"         * consumed right here, so clearing it here is correct.",
"         * t->async_preempted asks 'is the suspension this task is about",
"         * to sit in an ASYNC one, i.e. taken at an arbitrary instruction",
"         * boundary rather than at a compiler-placed safepoint' -- and",
"         * its one and only reader is the run-queue walk, which runs",
"         * strictly LATER, while t sits queued. Clearing it here, one",
"         * line before sl_runq_push, meant every task on that queue was",
"         * observed with the flag already 0: measured directly by",
"         * counting the walk's own conservative-scan branch under",
"         * concurrent_compute, 0 hits out of ~390 queued tasks walked per",
"         * collection, versus 23-30 once the clear moved to where it",
"         * belongs. The flag is retired instead by sl_preempt_yield",
"         * (runtime_sched.c), on RESUME -- the instant the async",
"         * suspension it describes actually ends. See there for the full",
"         * story and the concrete corruption this reinstates cover for. */",
"        /* Tier 11 stretch (work-stealing): pushes to THIS worker's own",
"         * local queue when it has one, for locality -- a task giving up",
"         * its own time slice naturally continues on the same worker",
"         * that was just running it, unless some other, now-idle worker",
"         * steals it in the meantime. Falls back to the shared overflow",
"         * queue at slot_idx == -1 (main's own original OS thread),",
"         * exactly like sl_task_submit's own identical fallback. */",
"        sl_runq_push_raw(slot_idx >= 0 ? &sl_worker_runq[slot_idx]",
"                                        : &sl_global_runq,",
"                          t); /* _raw, NOT the bracketed",
"            sl_runq_push -- its bracket would target t itself here (this",
"            branch deliberately leaves sl_rt_current_task == t across the",
"            push, see above), and its closing sl_rt_preempt_enable() would",
"            then run AFTER t is dequeue-able, i.e. potentially after",
"            another worker has already finished and free()d t. See",
"            sl_runq_push's own comment for the deadlock that root-caused",
"            this. No protection is lost: this code runs on the worker's",
"            native stack, which sl_preempt_handler's stack-range veto",
"            already rejects unconditionally. */",
"        sl_rt_current_task = &sl_rt_task_storage; /* the LAST thing this",
"            branch does, and deliberately not a dereference of t: after",
"            the push above, t may already be running, finished, and freed",
"            on another worker. */",
"        return;",
"    }",
"    if (t->parked) {",
"        t->parked = 0;",
"        pthread_mutex_t *mu = t->park_mu;",
"        t->park_mu = NULL;",
"        sl_rt_current_task = &sl_rt_task_storage; /* MUST happen before",
"            the unlock below, not after: the registry's task_slot",
"            dereferences through sl_rt_current_task at any time,",
"            including immediately after mu is unlocked and some OTHER",
"            thread could already be resuming t. */",
"        if (mu) pthread_mutex_unlock(mu);",
"        return;",
"    }",
"    sl_rt_current_task = &sl_rt_task_storage; /* MUST happen before",
"        the frees below, not after -- same reasoning as the parked",
"        case above. */",
"    void *raw = t->raw_base;",
"    free(raw);",
"    free(t);",
"}",
"",
"/* Fixed-capacity worker array -- generous, not sized to any real",
" * machine's core count; sl_pool_start's own floor/sysconf logic",
" * (further down) is what actually decides how many of these get",
" * used. Declared here, ahead of sl_worker_run_loop -- moved up from",
" * its original spot next to sl_pool_start specifically so",
" * sl_worker_run_loop (the first real user of sl_pool_slots) has both",
" * SL_POOL_MAX_WORKERS and the slot type available at its own",
" * definition site, same ordering reason as every other forward-",
" * declaration in this codebase. SL_POOL_MAX_WORKERS itself now lives",
" * in runtime_core.c (Tier 11 stretch: work-stealing) -- sl_worker_runq[]",
" * needs it at ITS OWN definition site, well before this file is",
" * emitted; this file just uses the macro, doesn't redefine it. */",
"static pthread_t sl_pool_workers[SL_POOL_MAX_WORKERS];",
"",
"/* Tier 11 eighth slice (async preemption): the 'current occupant'",
" * table -- lets the ticker thread (below) discover which task each",
" * worker is CURRENTLY running, something nothing before this slice",
" * needed (sl_rt_current_task is thread-local, only readable from a",
" * worker's own thread). .tid is written by each worker itself, once,",
" * as literally its first action -- BEFORE it ever touches .cur --",
" * closing a real startup race an early design review caught: if the",
" * pool-starting thread wrote .tid instead, after pthread_create",
" * returns, a freshly-started worker could begin dispatching (setting",
" * its own .cur) before .tid was populated, letting the ticker",
" * pthread_kill an uninitialized pthread_t. .cur is set by",
" * sl_worker_run_loop right where run_start_ns is already reset (a",
" * fresh dispatch, a resume-from-park, and a resume-from-preemption-",
" * yield all funnel through that one line), and cleared right after",
" * sl_worker_after_switch returns -- an idle worker's slot always",
" * reads NULL, so the ticker never targets a worker with nothing",
" * running on it. */",
"typedef struct sl_pool_slot {",
"    _Atomic(pthread_t) tid;",
"    _Atomic(sl_task *) cur;",
"} sl_pool_slot;",
"static sl_pool_slot sl_pool_slots[SL_POOL_MAX_WORKERS];",
"",
"/* Tier 11 eighth slice: a genuine use-after-free the atomic .cur field",
" * alone cannot close, found only by tracing concurrent_compute's own",
" * crashes down to it (many other fixes in this same slice narrowed but",
" * never eliminated its crash rate, because this bug is unrelated to",
" * any of them). sl_worker_after_switch's own 'normal completion'",
" * branch (below) calls free(t->raw_base) and free(t) directly, and the",
" * ticker thread (further down) doesn't just read .cur to decide",
" * whether to act -- it DEREFERENCES the sl_task it names",
" * (t->run_start_ns, t->async_preempt_pending) before ever sending a",
" * signal. Clearing .cur to NULL before free(t) (see",
" * sl_worker_run_loop's own comment) only removes ONE interleaving --",
" * the ticker reading .cur AFTER the clear sees NULL correctly -- it",
" * does nothing about the ticker having ALREADY read a valid, non-NULL",
" * t a moment earlier and now being mid-dereference of it while this",
" * thread concurrently frees it. Nothing about the async-preemption",
" * VETO (sl_preempt_handler's stack-range check) touches this either:",
" * that veto only protects against a wrongly-REDIRECTED preemption, not",
" * against the ticker's own plain memory read racing a free(). This",
" * mutex serializes the two: the ticker holds it across each slot's own",
" * read-then-dereference-then-signal-decision (below), and",
" * sl_worker_run_loop holds it across clearing .cur through",
" * sl_worker_after_switch's own return (which is where the free, when",
" * it happens, actually happens) -- so a completing task's struct is",
" * never freed while the ticker could still be looking at it, and the",
" * ticker never sees a torn read. Held only briefly by either side (a",
" * few field accesses, no syscalls except pthread_kill, called AFTER",
" * this lock is released -- see the ticker's own comment), so",
" * contention is not expected to matter at this pool's scale. */",
"static pthread_mutex_t sl_pool_slots_mu = PTHREAD_MUTEX_INITIALIZER;",
"",
"/* slot_idx: this thread's index into sl_pool_slots, or -1 -- the",
" * latter for main's own original OS thread, which also reaches this",
" * function (program.c, once main's top-level task itself parks and",
" * this thread joins the general worker loop) but is NOT one of",
" * sl_pool_workers[] and has no real slot. Tier 11 eighth slice's own",
" * scope note: the async-preemption ticker only ever targets",
" * sl_pool_workers[] threads, so a task that happens to run on main's",
" * original thread stays cooperative-preemption-only -- -1 skips the",
" * occupant-table writes below entirely rather than indexing with a",
" * meaningless value, the direct expression of that same scope",
" * decision in code, not a workaround for it. */",
"static void sl_worker_run_loop(long slot_idx) {",
"    for (;;) {",
"        /* checkin BEFORE touching the queue at all -- as long as",
"         * nothing between two checkin calls itself yields a checkin/ack",
"         * opportunity, no collection can reach quiescence (let alone",
"         * mark phase) while this thread is anywhere inside the",
"         * pop+assign stretch below, regardless of what it's doing. This",
"         * makes pop+assign atomic with respect to collections by",
"         * construction, not by narrowing a window -- see",
"         * sl_runq_pop_blocking's own comment for the empirically-found",
"         * race this closes (Tier 11 plan). */",
"        sl_rt_gc_checkin();",
"        /* Tier 11 stretch (work-stealing): a real pool worker (slot_idx",
"         * >= 0) tries its own local queue, then the global overflow",
"         * queue, then steals from other workers, before a bounded wait",
"         * -- see sl_pool_pop_or_steal's own comment. Main's own original",
"         * OS thread (slot_idx == -1) has no local queue of its own and",
"         * keeps using sl_runq_pop_blocking(&sl_global_runq) directly,",
"         * unchanged -- the same scope note as every other -1 special",
"         * case in this file: it was never meant to have one. */",
"        sl_task *t = slot_idx >= 0 ? sl_pool_pop_or_steal(slot_idx)",
"                                    : sl_runq_pop_blocking(&sl_global_runq);",
"        if (t) sl_rt_current_task = t;",
"        if (!t) break; /* shutdown */",
"        /* Tier 11 seventh slice: fresh quantum clock for every dispatch",
"         * -- a fresh submit, a resume-from-park, AND (new) a resume-from-",
"         * preemption-yield all funnel through this one line, so",
"         * sl_rt_maybe_yield's run_start_ns comparison always measures",
"         * this stint, never a stale one from before the last switch-out. */",
"        t->run_start_ns = sl_rt_monotonic_ns();",
"        /* Tier 11 eighth slice: publish t as this slot's occupant right",
"         * where run_start_ns is already reset -- a fresh submit, a",
"         * resume-from-park, and a resume-from-preemption-yield all",
"         * funnel through this one line, so the ticker's own quantum",
"         * check (mirroring sl_rt_maybe_yield's) is always measuring",
"         * this exact stint. release: must be visible to the ticker",
"         * thread (a different thread entirely) before any signal based",
"         * on seeing it could land. */",
"        if (slot_idx >= 0)",
"            atomic_store_explicit(&sl_pool_slots[slot_idx].cur, t, memory_order_release);",
"        sl_ctx_switch(&sl_rt_native_rsp, t->rsp);",
"        /* resumes here once t either finishes or parks */",
"        /* Tier 11 eighth slice: .cur cleared BEFORE sl_worker_after_switch,",
"         * not after, AND both now held under sl_pool_slots_mu (its own",
"         * comment above has the full story) -- sl_worker_after_switch's",
"         * own 'normal completion' branch calls free(t) directly, and the",
"         * ticker thread dereferences whatever .cur names before ever",
"         * deciding to signal, not just checks it for non-NULL. Clearing",
"         * .cur earlier alone only narrows that race; the mutex is what",
"         * actually closes it, by making 'the ticker reads and",
"         * dereferences .cur for this slot' and 'this thread clears .cur",
"         * and (maybe) frees t' mutually exclusive. Safe to hold across",
"         * the WHOLE sl_worker_after_switch call, not just the free: that",
"         * function never itself reads .cur, only t (its own parameter)",
"         * and sl_rt_current_task, so nothing about holding the lock",
"         * slightly longer than strictly required changes what it does. */",
"        if (slot_idx >= 0) {",
"            pthread_mutex_lock(&sl_pool_slots_mu);",
"            atomic_store_explicit(&sl_pool_slots[slot_idx].cur, NULL, memory_order_release);",
"            sl_worker_after_switch(t, slot_idx);",
"            pthread_mutex_unlock(&sl_pool_slots_mu);",
"        } else {",
"            sl_worker_after_switch(t, slot_idx);",
"        }",
"    }",
"}",
"",
"static void *sl_worker_loop(void *arg) {",
"    long slot_idx = (long)(intptr_t)arg;",
"    /* Tier 11 stretch (work-stealing): this thread's own copy, for",
"     * sl_task_submit to read -- see sl_rt_my_slot_idx's own comment",
"     * above. Set alongside .tid, before anything else runs on this",
"     * thread; no ordering hazard with the .tid publish just below,",
"     * since nothing reads sl_rt_my_slot_idx from any OTHER thread. */",
"    sl_rt_my_slot_idx = slot_idx;",
"    /* Tier 11 eighth slice: this worker's OWN first action, before",
"     * sl_gc_register_thread or anything else -- see sl_pool_slots' own",
"     * comment for the startup race this ordering closes. */",
"    atomic_store_explicit(&sl_pool_slots[slot_idx].tid, pthread_self(), memory_order_release);",
"    sl_gc_register_thread();",
"    sl_worker_run_loop(slot_idx);",
"    sl_gc_unregister_thread(); /* this loop can only be left via",
"        shutdown, at which point this OS thread is about to exit for",
"        good -- omitting this would leave a registry node pointing at",
"        TLS about to be torn down. */",
"    return NULL;",
"}",
"",
"/* Tier 11 eighth slice, rollout step 3: the real signal handler --",
" * replaces step 2's temporary do-nothing placeholder. Transplanted",
" * from the validated standalone spike (Tier 11 plan, 'Spike findings'),",
" * with all four fixes that spike's own two review passes required:",
" * (1) the stack-range veto (is the interrupted sp actually on t's OWN",
" * stack? sl_rt_current_task being non-NULL does not by itself prove",
" * this -- there is a genuine, if tiny, window between a scheduler",
" * assigning sl_rt_current_task = t and the dispatch's own sl_ctx_switch",
" * actually running, reproduced directly in the spike as a real crash",
" * before this check existed); (2) the trampoline-range veto (never",
" * re-preempt the trampoline's own code, independent of",
" * preempt_disable_depth -- the spike's own Bug 1, a counter-based",
" * bracket alone provably cannot close the release-to-jmp tail); (3) the",
" * preempt_disable_depth check itself (never preempt while t holds one",
" * of the runtime's own internal locks or is mid-transition); (4) a",
" * fresh quantum re-check (don't trust the ticker's possibly-stale",
" * snapshot). No locks taken anywhere in this function -- the only",
" * risky work (pushing onto the run queue) happens later, in",
" * sl_preempt_yield, from ordinary post-sigreturn code, not from",
" * signal-handler context at all. */",
"static void sl_preempt_handler(int sig, siginfo_t *si, void *uctx_raw) {",
"    (void)sig; (void)si;",
"    sl_task *t = sl_rt_current_task;",
"    if (!t) return; /* signal landed on a thread with no active task",
"        (main's original OS thread before its own task ever dispatches,",
"        or -- defensively -- the timer/reactor/signal threads, though",
"        the ticker never targets those) */",
"    atomic_store_explicit(&t->async_preempt_pending, 0, memory_order_relaxed);",
"    /* clearing pending unconditionally, before either veto below,",
"       matters: if it stayed set, the ticker's own dedup check would",
"       permanently skip this task forever, silently going dormant for",
"       the rest of the run rather than just missing this one attempt. */",
"    ucontext_t *uctx = (ucontext_t *)uctx_raw;",
"#if defined(__x86_64__)",
"    uintptr_t pc0 = (uintptr_t)uctx->uc_mcontext->__ss.__rip;",
"    uintptr_t sp0 = (uintptr_t)uctx->uc_mcontext->__ss.__rsp;",
"#elif defined(__aarch64__)",
"    uintptr_t pc0 = (uintptr_t)__darwin_arm_thread_state64_get_pc(uctx->uc_mcontext->__ss);",
"    uintptr_t sp0 = (uintptr_t)uctx->uc_mcontext->__ss.__sp;",
"#endif",
"    if (sp0 < (uintptr_t)t->stack_base ||",
"        sp0 >= (uintptr_t)t->stack_base + t->stack_size) {",
"        return; /* not genuinely running on t's own stack right now --",
"            see the spike's own Bug 2 (main comment above) for the",
"            concrete failure this closes */",
"    }",
"    if (pc0 >= (uintptr_t)sl_preempt_trampoline_entry &&",
"        pc0 < (uintptr_t)sl_preempt_trampoline_end) {",
"        return; /* never re-preempt the trampoline's own code */",
"    }",
"    if (atomic_load_explicit(&t->preempt_disable_depth, memory_order_acquire) != 0)",
"        return;",
"    if (sl_rt_monotonic_ns() - t->run_start_ns < SL_PREEMPT_QUANTUM_NS)",
"        return; /* re-validate fresh -- don't trust the ticker's",
"            possibly-stale snapshot */",
"    /* Close the re-entrancy window starting HERE, not at",
"       sl_task_yield_now's own entry -- too late, leaves the handler-",
"       return-through-trampoline-prologue stretch unguarded. Decremented",
"       by the trampoline's own tail (the 'lock decl' against the",
"       pointer sl_preempt_get_disable_depth_ptr returns), as the last",
"       possible register-safe instant before its final jmp. */",
"    atomic_fetch_add_explicit(&t->preempt_disable_depth, 1, memory_order_acq_rel);",
"    t->async_orig_pc = (void *)pc0;",
"#if defined(__x86_64__)",
"    uctx->uc_mcontext->__ss.__rip = (uintptr_t)sl_preempt_trampoline_entry;",
"#elif defined(__aarch64__)",
"    __darwin_arm_thread_state64_set_pc_fptr(uctx->uc_mcontext->__ss,",
"                                             sl_preempt_trampoline_entry);",
"#endif",
"}",
"",
"/* Ticker thread: mirrors sl_time_thread/sl_reactor_thread/",
" * sl_sig_thread's own dedicated-pthread shape. Every 2ms, for each",
" * occupied slot whose run_start_ns looks past SL_PREEMPT_QUANTUM_NS",
" * (cooperative v1's existing tunable, runtime_core.c -- reused, not",
" * duplicated) AND sl_global_runq_count > 0 (the same 'is anyone",
" * actually waiting' gate sl_rt_maybe_yield already uses), sends",
" * SIGUSR1 to that slot's tid, once per outstanding attempt",
" * (async_preempt_pending dedups). Never registered with the GC --",
" * same reasoning as sl_reactor_thread's own (pkg_net/runtime_net.c):",
" * it never drives a task and never touches a GC-scanned field, only",
" * plain atomics on sl_pool_slots and sl_task.async_preempt_pending/",
" * run_start_ns. */",
"static void *sl_preempt_ticker_thread(void *arg) {",
"    (void)arg;",
"    struct timespec interval;",
"    interval.tv_sec = 0;",
"    interval.tv_nsec = 2000000; /* 2ms */",
"    for (;;) {",
"        nanosleep(&interval, NULL);",
"        if (atomic_load_explicit(&sl_global_runq_count, memory_order_relaxed) == 0)",
"            continue;",
"        long long now = sl_rt_monotonic_ns();",
"        for (int i = 0; i < SL_POOL_MAX_WORKERS; i++) {",
"            /* Tier 11 eighth slice: held across the read of .cur AND",
"             * every dereference of the sl_task it names -- see",
"             * sl_pool_slots_mu's own comment above for the use-after-free",
"             * this closes (a completing task's own free(t), racing this",
"             * exact read-then-dereference sequence, not just a plain",
"             * non-NULL check). Released before pthread_kill: that's a",
"             * syscall, and by this point every field this loop needed",
"             * has already been safely read (tid included) -- nothing",
"             * left to protect. */",
"            pthread_mutex_lock(&sl_pool_slots_mu);",
"            sl_task *t = atomic_load_explicit(&sl_pool_slots[i].cur, memory_order_acquire);",
"            if (!t) { pthread_mutex_unlock(&sl_pool_slots_mu); continue; }",
"            if (now - t->run_start_ns < SL_PREEMPT_QUANTUM_NS) {",
"                pthread_mutex_unlock(&sl_pool_slots_mu);",
"                continue;",
"            }",
"            if (atomic_load_explicit(&t->async_preempt_pending, memory_order_relaxed)) {",
"                pthread_mutex_unlock(&sl_pool_slots_mu);",
"                continue;",
"            }",
"            atomic_store_explicit(&t->async_preempt_pending, 1, memory_order_relaxed);",
"            pthread_t tid = atomic_load_explicit(&sl_pool_slots[i].tid, memory_order_acquire);",
"            pthread_mutex_unlock(&sl_pool_slots_mu);",
"            pthread_kill(tid, SIGUSR1);",
"        }",
"    }",
"    return NULL;",
"}",
"",
"static void sl_preempt_ticker_start(void) {",
"    struct sigaction sa;",
"    memset(&sa, 0, sizeof(sa));",
"    /* Tier 11 eighth slice, rollout step 3: the real handler now, not",
"       step 2's placeholder -- SA_SIGINFO for the ucontext_t access it",
"       needs to read/rewrite an interrupted task's saved PC. No",
"       SA_ONSTACK: the handler itself never runs on an alternate stack",
"       (confirmed sound by the second review) -- it inspects/rewrites",
"       the interrupted context and returns immediately; the trampoline",
"       that does the real work runs later, as ordinary code, after a",
"       genuine sigreturn, on the task's own real stack. */",
"    sa.sa_sigaction = sl_preempt_handler;",
"    sa.sa_flags = SA_SIGINFO;",
"    sigemptyset(&sa.sa_mask);",
"    if (sigaction(SIGUSR1, &sa, NULL) != 0) {",
"        fprintf(stderr, \"slang: failed to install preempt handler\\n\");",
"        exit(1);",
"    }",
"    pthread_t th;",
"    if (pthread_create(&th, NULL, sl_preempt_ticker_thread, NULL) != 0) {",
"        fprintf(stderr, \"slang: failed to start preempt ticker\\n\");",
"        exit(1);",
"    }",
"}",
"",
"/* Called once, from main(), before any user code (which might 'spawn')",
" * starts running. Sizes the pool via sysconf(_SC_NPROCESSORS_ONLN),",
" * floored at 8: tests/proc_shutdown already has two simultaneously-",
" * BLOCKING spawned tasks today, and net's TLS handshake / time.sleep's",
" * getaddrinfo call still block whichever OS thread calls them (plain",
" * TCP net.* itself now parks, Tier 11 sixth slice), so a low floor",
" * (sysconf can legitimately return 1, e.g. in a constrained container)",
" * is a live risk to an existing test, not a hypothetical one. This is",
" * an explicit stopgap, not a real fix.",
" *",
" * Tier 11 sixth slice: no longer takes a block_signals parameter --",
" * SIGTERM/SIGINT are now blocked exactly ONCE, at the very top of",
" * main() (program.c), before any thread (including this pool's own",
" * workers) is ever created, so every subsequently-created thread",
" * inherits the blocked mask automatically via normal pthread_create",
" * semantics. Only the dedicated signal thread (pkg_proc/runtime.c)",
" * ever has these signals unblocked, via its own sigwait() call --",
" * replaces the old 'exactly one thread stays unblocked' scheme",
" * entirely, see that file's own comments. */",
"static void sl_pool_start(void) {",
"    long n = sysconf(_SC_NPROCESSORS_ONLN);",
"    if (n < 8) n = 8;",
"    if (n > SL_POOL_MAX_WORKERS) n = SL_POOL_MAX_WORKERS;",
"",
"    /* Tier 11 stretch (work-stealing): explicitly initialize each",
"     * worker's own local run queue's mutex/condvar, and publish the",
"     * worker count, BEFORE any worker thread is created -- both load-",
"     * bearing, not just tidy ordering. Explicit init: on Darwin,",
"     * PTHREAD_MUTEX_INITIALIZER/PTHREAD_COND_INITIALIZER are NOT",
"     * all-zero-bytes (they embed a nonzero signature libpthread checks),",
"     * so sl_worker_runq[]'s own static zero-initialization does NOT",
"     * produce validly-usable mutexes/condvars here, unlike on Linux/",
"     * glibc where zero happens to work by coincidence -- locking one",
"     * unintialized would be undefined behavior, not merely unsafe in",
"     * some abstract sense. Publish-before-create: POSIX guarantees",
"     * pthread_create synchronizes-with the new thread's own start, so",
"     * a plain, non-atomic sl_pool_num_workers written here is",
"     * guaranteed visible to every worker with no fence needed -- the",
"     * exact same reasoning sl_pool_workers[]'s own sizing already",
"     * relies on, just extended to this new variable. */",
"    for (long i = 0; i < n; i++) {",
"        pthread_mutex_init(&sl_worker_runq[i].mu, NULL);",
"        pthread_cond_init(&sl_worker_runq[i].not_empty, NULL);",
"    }",
"    sl_pool_num_workers = n;",
"",
"    for (long i = 0; i < n; i++) {",
"        if (pthread_create(&sl_pool_workers[i], NULL, sl_worker_loop,",
"                            (void *)(intptr_t)i) != 0) {",
"            fprintf(stderr, \"slang: failed to start worker pool\\n\");",
"            exit(1);",
"        }",
"    }",
"    sl_preempt_ticker_start();",
"}",
"",
};

const int RUNTIME_POOL_LEN = sizeof(RUNTIME_POOL) / sizeof(RUNTIME_POOL[0]);
