/* Tier 11, first slice: growable-stack tasks on a hand-rolled context
 * switch -- see the array's own header comment (emitted into the
 * generated program) for the full picture. main() and sl_task_submit
 * (runtime_pool.c, third slice) both call sl_task_stack_init to
 * actually run on one of these buffers; sl_rt_safepoint_enter
 * (runtime_core.c) is what triggers sl_task_stack_grow. */

#include "internal.h"

const char *RUNTIME_SCHED[] = {
"/* Tier 11, first slice: growable-stack tasks on a hand-rolled",
" * context switch. main() and every spawned pthread now run their own",
" * body on a task-owned buffer (sl_task_stack_init below) instead of",
" * directly on the OS-provided thread stack, and sl_rt_safepoint_enter",
" * (runtime_core.c) grows that buffer on demand -- still exactly one",
" * task per OS thread, created and torn down with the thread itself;",
" * no scheduler, no second task, no parking. Full design writeup and",
" * the standalone spike that validated this mechanism (context switch",
" * + grow-and-relocate, both single- and multi-threaded, plus a",
" * negative control) live in the Tier 11 plan; see todo.md's Tier 11",
" * entry for the pointer once that's written up there.",
" *",
" * The x86_64 path was validated directly (150+ spike runs, ASan-",
" * free-poisoning UAF check, a negative control proving the frame-",
" * pointer-chain fix is load-bearing). The arm64 path was written",
" * from the AAPCS64 spec and cross-assembly/disassembly-verified",
" * (encoding matches this design exactly) but has NOT run on real",
" * arm64 hardware -- flagged here, not silently assumed correct.",
" * Unlike x86_64 System V (no callee-saved XMM registers at all,",
" * which is why the x86_64 switch below touches no FP/SSE state),",
" * AAPCS64 requires d8-d15 preserved across a call, so the arm64",
" * switch saves/restores them -- a real ABI divergence, not an",
" * oversight to bring in line with the x86_64 file.",
" *",
" * Darwin (Mach-O) mangles C-linkage symbols with a leading",
" * underscore; Linux (ELF) does not -- the asm below emits the",
" * matching symbol name for whichever this build targets, so the",
" * plain `sl_ctx_switch`/`sl_ctx_trampoline` C declarations below",
" * resolve correctly either way. */",
"",
"#if defined(__x86_64__)",
"#if defined(__APPLE__)",
"__asm__(",
    "\".text\\n\"",
    "\".globl _sl_ctx_switch\\n\"",
    "\".p2align 4\\n\"",
    "\"_sl_ctx_switch:\\n\"",
    "\"    push %rbp\\n\"",
    "\"    push %rbx\\n\"",
    "\"    push %r12\\n\"",
    "\"    push %r13\\n\"",
    "\"    push %r14\\n\"",
    "\"    push %r15\\n\"",
    "\"    mov  %rsp, (%rdi)\\n\"",
    "\"    mov  %rsi, %rsp\\n\"",
    "\"    pop  %r15\\n\"",
    "\"    pop  %r14\\n\"",
    "\"    pop  %r13\\n\"",
    "\"    pop  %r12\\n\"",
    "\"    pop  %rbx\\n\"",
    "\"    pop  %rbp\\n\"",
    "\"    ret\\n\"",
    "\".globl _sl_ctx_trampoline\\n\"",
    "\".p2align 4\\n\"",
    "\"_sl_ctx_trampoline:\\n\"",
    "\"    mov  %r12, %rdi\\n\"",
    "\"    call *%r13\\n\"",
    "\"    ud2\\n\"",
");",
"#else",
"__asm__(",
    "\".text\\n\"",
    "\".globl sl_ctx_switch\\n\"",
    "\".p2align 4\\n\"",
    "\"sl_ctx_switch:\\n\"",
    "\"    push %rbp\\n\"",
    "\"    push %rbx\\n\"",
    "\"    push %r12\\n\"",
    "\"    push %r13\\n\"",
    "\"    push %r14\\n\"",
    "\"    push %r15\\n\"",
    "\"    mov  %rsp, (%rdi)\\n\"",
    "\"    mov  %rsi, %rsp\\n\"",
    "\"    pop  %r15\\n\"",
    "\"    pop  %r14\\n\"",
    "\"    pop  %r13\\n\"",
    "\"    pop  %r12\\n\"",
    "\"    pop  %rbx\\n\"",
    "\"    pop  %rbp\\n\"",
    "\"    ret\\n\"",
    "\".globl sl_ctx_trampoline\\n\"",
    "\".p2align 4\\n\"",
    "\"sl_ctx_trampoline:\\n\"",
    "\"    mov  %r12, %rdi\\n\"",
    "\"    call *%r13\\n\"",
    "\"    ud2\\n\"",
");",
"#endif",
"#elif defined(__aarch64__)",
"#if defined(__APPLE__)",
"__asm__(",
    "\".text\\n\"",
    "\".globl _sl_ctx_switch\\n\"",
    "\".p2align 2\\n\"",
    "\"_sl_ctx_switch:\\n\"",
    "\"    stp x19, x20, [sp, #-16]!\\n\"",
    "\"    stp x21, x22, [sp, #-16]!\\n\"",
    "\"    stp x23, x24, [sp, #-16]!\\n\"",
    "\"    stp x25, x26, [sp, #-16]!\\n\"",
    "\"    stp x27, x28, [sp, #-16]!\\n\"",
    "\"    stp d8,  d9,  [sp, #-16]!\\n\"",
    "\"    stp d10, d11, [sp, #-16]!\\n\"",
    "\"    stp d12, d13, [sp, #-16]!\\n\"",
    "\"    stp d14, d15, [sp, #-16]!\\n\"",
    "\"    stp x29, x30, [sp, #-16]!\\n\"",
    "\"    mov x9, sp\\n\"",
    "\"    str x9, [x0]\\n\"",
    "\"    mov sp, x1\\n\"",
    "\"    ldp x29, x30, [sp], #16\\n\"",
    "\"    ldp d14, d15, [sp], #16\\n\"",
    "\"    ldp d12, d13, [sp], #16\\n\"",
    "\"    ldp d10, d11, [sp], #16\\n\"",
    "\"    ldp d8,  d9,  [sp], #16\\n\"",
    "\"    ldp x27, x28, [sp], #16\\n\"",
    "\"    ldp x25, x26, [sp], #16\\n\"",
    "\"    ldp x23, x24, [sp], #16\\n\"",
    "\"    ldp x21, x22, [sp], #16\\n\"",
    "\"    ldp x19, x20, [sp], #16\\n\"",
    "\"    ret\\n\"",
    "\".globl _sl_ctx_trampoline\\n\"",
    "\".p2align 2\\n\"",
    "\"_sl_ctx_trampoline:\\n\"",
    "\"    mov x0, x20\\n\"",
    "\"    blr x19\\n\"",
    "\"    brk #1\\n\"",
");",
"#else",
"__asm__(",
    "\".text\\n\"",
    "\".globl sl_ctx_switch\\n\"",
    "\".p2align 2\\n\"",
    "\"sl_ctx_switch:\\n\"",
    "\"    stp x19, x20, [sp, #-16]!\\n\"",
    "\"    stp x21, x22, [sp, #-16]!\\n\"",
    "\"    stp x23, x24, [sp, #-16]!\\n\"",
    "\"    stp x25, x26, [sp, #-16]!\\n\"",
    "\"    stp x27, x28, [sp, #-16]!\\n\"",
    "\"    stp d8,  d9,  [sp, #-16]!\\n\"",
    "\"    stp d10, d11, [sp, #-16]!\\n\"",
    "\"    stp d12, d13, [sp, #-16]!\\n\"",
    "\"    stp d14, d15, [sp, #-16]!\\n\"",
    "\"    stp x29, x30, [sp, #-16]!\\n\"",
    "\"    mov x9, sp\\n\"",
    "\"    str x9, [x0]\\n\"",
    "\"    mov sp, x1\\n\"",
    "\"    ldp x29, x30, [sp], #16\\n\"",
    "\"    ldp d14, d15, [sp], #16\\n\"",
    "\"    ldp d12, d13, [sp], #16\\n\"",
    "\"    ldp d10, d11, [sp], #16\\n\"",
    "\"    ldp d8,  d9,  [sp], #16\\n\"",
    "\"    ldp x27, x28, [sp], #16\\n\"",
    "\"    ldp x25, x26, [sp], #16\\n\"",
    "\"    ldp x23, x24, [sp], #16\\n\"",
    "\"    ldp x21, x22, [sp], #16\\n\"",
    "\"    ldp x19, x20, [sp], #16\\n\"",
    "\"    ret\\n\"",
    "\".globl sl_ctx_trampoline\\n\"",
    "\".p2align 2\\n\"",
    "\"sl_ctx_trampoline:\\n\"",
    "\"    mov x0, x20\\n\"",
    "\"    blr x19\\n\"",
    "\"    brk #1\\n\"",
");",
"#endif",
"#else",
"#error \"sl_ctx_switch: unsupported architecture (only x86_64 and aarch64 have a runtime_sched.c backend)\"",
"#endif",
"",
"void sl_ctx_switch(void **old_rsp_slot, void *new_rsp);",
"void sl_ctx_trampoline(void);",
"",
"/* sl_task itself is defined earlier, in RUNTIME[] (runtime_core.c) --",
" * sl_rt_safepoint_enter/exit need its complete type at their own",
" * definition site, which is emitted well before this file. See the",
" * comment there for the full reasoning; everything below just USES",
" * sl_task, it doesn't redefine it. */",
"",
"/* Saved-register block layout, low address (= the saved rsp) to",
" * high, exactly mirroring sl_ctx_switch's own push order in",
" * reverse -- see ctx_x86_64.s / ctx_arm64.s spike headers for the",
" * full derivation. SAVED_FP_OFF is where a fresh (or currently",
" * suspended) task's own frame-pointer register sits within this",
" * block; the grow-and-relocate frame-pointer-chain walk below",
" * seeds from exactly this offset. Architecture-specific, not a",
" * port bug: x86_64's push-based layout puts it at +40 (6",
" * registers before it); arm64's stp-pair layout puts it at +0",
" * (pushed last, into the first pair popped).",
" *",
" * SL_CTX_BLOCK_SIZE is the total save-block size sl_ctx_make must",
" * reserve when synthesizing a fresh context below. */",
"#if defined(__x86_64__)",
"#define SAVED_FP_OFF 40",
"#define SL_CTX_BLOCK_SIZE 56 /* 7 slots x 8 bytes */",
"#elif defined(__aarch64__)",
"#define SAVED_FP_OFF 0",
"#define SL_CTX_BLOCK_SIZE 160 /* 10 stp pairs x 16 bytes */",
"#endif",
"",
"/* Prime a fresh context: t->stack_base/stack_size must already be",
" * set. On first switch-in, entry(arg) starts running on this",
" * task's own stack; entry must never return. */",
"static void sl_ctx_make(sl_task *t, void (*entry)(void *), void *arg) {",
"    uintptr_t top = ((uintptr_t)t->stack_base + t->stack_size) &",
"                    ~(uintptr_t)15;",
"#if defined(__x86_64__)",
"    /* low->high: r15, r14, r13, r12, rbx, rbp, return_address --",
"     * r13/r12 smuggle entry/arg through to sl_ctx_trampoline (still",
"     * hold their synthesized values immediately after the pop",
"     * sequence's implicit ret lands there). rbp=NULL terminates",
"     * the frame-pointer-chain walk at task entry. */",
"    void **sp = (void **)(top - SL_CTX_BLOCK_SIZE);",
"    sp[0] = NULL;              /* r15 */",
"    sp[1] = NULL;              /* r14 */",
"    sp[2] = (void *)entry;     /* r13 */",
"    sp[3] = arg;               /* r12 */",
"    sp[4] = NULL;              /* rbx */",
"    sp[5] = NULL;              /* rbp -- terminates fp-chain walk */",
"    sp[6] = (void *)sl_ctx_trampoline; /* return address */",
"    t->rsp = sp;",
"#elif defined(__aarch64__)",
"    /* x19/x20 smuggle entry/arg through to sl_ctx_trampoline (same",
"     * trick, arm64's callee-saved GPRs in place of r13/r12); x29=0",
"     * terminates the frame-pointer-chain walk; x30 is what sl_ctx_",
"     * switch's own `ret` (br x30) jumps to on first resume. */",
"    unsigned char *base = (unsigned char *)(top - SL_CTX_BLOCK_SIZE);",
"    void **slot = (void **)base;",
"    slot[0] = NULL;                     /* x29 (fp) */",
"    slot[1] = (void *)sl_ctx_trampoline; /* x30 (lr) */",
"    for (int i = 2; i < 18; i++) slot[i] = NULL; /* d14..x22, unused */",
"    slot[18] = (void *)entry; /* x19 */",
"    slot[19] = arg;           /* x20 */",
"    t->rsp = base;",
"#endif",
"}",
"",
"static void *sl_task_translate(void *ptr, void *old_base, size_t old_size,",
"                              void *new_base, size_t new_size) {",
"    uintptr_t p = (uintptr_t)ptr;",
"    uintptr_t ob = (uintptr_t)old_base;",
"    if (!ptr || p < ob || p >= ob + old_size) return ptr;",
"    /* Anchor at the buffer's TOP, not its base -- the stack grows",
"     * downward, and the guard check (SL_TASK_GUARD_MARGIN, defined",
"     * with sl_task in RUNTIME[]) measures distance from the base, so",
"     * a base-anchored translation would leave that distance",
"     * unchanged, create zero headroom, and regrow infinitely on the",
"     * very next check. See the plan's design section for the full",
"     * derivation -- this was a real bug caught in review before",
"     * implementation, not a guess. */",
"    uintptr_t depth_from_old_top = (ob + old_size) - p;",
"    uintptr_t nb = (uintptr_t)new_base;",
"    return (void *)((nb + new_size) - depth_from_old_top);",
"}",
"",
"static _Thread_local unsigned char sl_grower_stack[65536]; /* MUST stay",
"    _Thread_local: spawn already creates genuinely concurrent OS",
"    threads today, and two tasks on two different threads can grow",
"    at overlapping times -- a shared scratch stack would let them",
"    corrupt each other's in-flight relocation state. Caught in",
"    review before implementation, and separately reproduced as a",
"    reliable (30/30) crash in the spike's own negative control.",
"    */",
"static _Thread_local void *sl_grower_rsp;",
"",
"/* sl_rt_native_rsp is defined earlier, in RUNTIME[] (runtime_core.c) --",
" * sl_rt_error needs it at its own definition site, well before this",
" * file is emitted. See the comment there for the full reasoning;",
" * everything below just uses it, it doesn't redefine it. */",
"",
"static void sl_task_grower_entry(void *arg) {",
"    sl_task *t = (sl_task *)arg;",
"    void *old_base = t->stack_base;",
"    void *old_raw = t->raw_base;",
"    size_t old_size = t->stack_size;",
"    void *old_rsp = t->rsp;",
"",
"    size_t new_size = old_size * 2;",
"    void *raw = malloc(new_size + 16);",
"    if (!raw) { sl_rt_error(\"out of memory growing task stack\", 0, 0); }",
"    void *new_base = (void *)(((uintptr_t)raw + 15) & ~(uintptr_t)15);",
"",
"    /* Copy the ENTIRE old buffer to the END of the new one -- never",
"     * just the live range above rsp: this is what keeps the x86_64",
"     * red zone (up to 128 bytes below rsp a leaf frame may have used",
"     * without moving rsp) correct for free. Load-bearing, not",
"     * incidental. */",
"    memcpy((char *)new_base + (new_size - old_size), old_base, old_size);",
"",
"    /* translate the safepoint chain */",
"    for (sl_safepoint *sp = t->safepoint_top; sp; sp = sp->prev) {",
"        sl_safepoint *new_sp = (sl_safepoint *)sl_task_translate(",
"            sp, old_base, old_size, new_base, new_size);",
"        new_sp->prev = (sl_safepoint *)sl_task_translate(",
"            sp->prev, old_base, old_size, new_base, new_size);",
"        new_sp->roots = (void **)sl_task_translate(",
"            sp->roots, old_base, old_size, new_base, new_size);",
"    }",
"    t->safepoint_top = (sl_safepoint *)sl_task_translate(",
"        t->safepoint_top, old_base, old_size, new_base, new_size);",
"",
"    /* translate the frame-pointer chain -- a SECOND, independent",
"     * structural chain a raw memcpy alone leaves dangling: every",
"     * saved-fp except the outermost would otherwise still point",
"     * into the just-freed old buffer, corrupted lazily and",
"     * silently as each caller frame returns and reloads through",
"     * it. See SAVED_FP_OFF above for why this offset is",
"     * architecture-specific. */",
"    void *old_fp = *(void **)((char *)old_rsp + SAVED_FP_OFF);",
"    while (old_fp && (uintptr_t)old_fp >= (uintptr_t)old_base &&",
"          (uintptr_t)old_fp < (uintptr_t)old_base + old_size) {",
"        void *new_fp = sl_task_translate(old_fp, old_base, old_size,",
"                                         new_base, new_size);",
"        void *old_next_fp = *(void **)old_fp;",
"        void *new_next_fp = sl_task_translate(old_next_fp, old_base,",
"                                              old_size, new_base, new_size);",
"        *(void **)new_fp = new_next_fp;",
"        old_fp = old_next_fp;",
"    }",
"",
"    t->rsp = sl_task_translate(old_rsp, old_base, old_size, new_base,",
"                               new_size);",
"",
"    free(old_raw); /* NOT old_base -- see sl_task's own raw_base field",
"                       comment (runtime_core.c) for why these can",
"                       differ */",
"    t->stack_base = new_base;",
"    t->raw_base = raw;",
"    t->stack_size = new_size;",
"    t->grows_seen++;",
"",
"    sl_ctx_switch(&sl_grower_rsp, t->rsp);",
"    fprintf(stderr, \"slang: internal error: grower context resumed \"",
"                    \"after switching back -- unreachable\\n\");",
"    abort(); /* genuinely unreachable -- a can't-happen guard, never",
"                routed through sl_rt_error's panic-recovery machinery */",
"}",
"",
"/* Growth switches to a dedicated grower context (its own small",
" * scratch stack) rather than growing in place, because a running C",
" * frame's own stack cannot be moved out from under itself in",
" * portable C -- see the plan's design section for the full",
" * reasoning. Called from sl_rt_safepoint_enter (runtime_core.c),",
" * forward-declared there since this definition comes much later. */",
"static void sl_task_stack_grow(sl_task *t) {",
"    uintptr_t top = ((uintptr_t)sl_grower_stack + sizeof(sl_grower_stack)) &",
"                    ~(uintptr_t)15;",
"#if defined(__x86_64__)",
"    void **sp = (void **)(top - SL_CTX_BLOCK_SIZE);",
"    sp[0] = NULL;",
"    sp[1] = NULL;",
"    sp[2] = (void *)sl_task_grower_entry;",
"    sp[3] = t;",
"    sp[4] = NULL;",
"    sp[5] = NULL;",
"    sp[6] = (void *)sl_ctx_trampoline;",
"    sl_grower_rsp = sp;",
"#elif defined(__aarch64__)",
"    unsigned char *base = (unsigned char *)(top - SL_CTX_BLOCK_SIZE);",
"    void **slot = (void **)base;",
"    slot[0] = NULL;",
"    slot[1] = (void *)sl_ctx_trampoline;",
"    for (int i = 2; i < 18; i++) slot[i] = NULL;",
"    slot[18] = (void *)sl_task_grower_entry;",
"    slot[19] = t;",
"    sl_grower_rsp = base;",
"#endif",
"    sl_ctx_switch(&t->rsp, sl_grower_rsp);",
"    /* resumes here once the grower switches back, i.e. after the",
"     * grow has fully completed and t->rsp/stack_base/stack_size are",
"     * already updated */",
"}",
"",
"/* Small on purpose -- 'start small... never a fixed ceiling', per",
" * todo.md's Tier 11 entry -- and deliberately much smaller than the",
" * OS's own default thread stack (which main()/spawn used exclusively",
" * before this): most of the room a program needs now comes from",
" * growing on demand instead of being reserved unconditionally up",
" * front for every task whether it needs it or not. */",
"#define SL_TASK_INITIAL_STACK_SIZE 65536",
"",
"/* Allocate t's stack buffer and prime it to start running entry(arg)",
" * on first switch-in -- called once, by main() (right after",
" * sl_gc_register_thread() has pointed sl_rt_current_task at t) and by",
" * sl_task_submit (runtime_pool.c, for a brand new task t that is NOT",
" * yet -- and may never become -- the calling thread's own current",
" * task). Tier 11 third slice: OOM here is a direct exit, not routed",
" * through sl_rt_error -- the caller's own sl_rt_current_task is not",
" * necessarily t (sl_task_submit calls this for a task some OTHER",
" * context is about to enqueue), so sl_rt_error's panic-switch-back",
" * would abandon the WRONG task and leave the failed submission's own",
" * sl_rt_active_spawns increment (stmt.c's call site) orphaned, never",
" * decremented. Matches sl_gc_set_grow/sl_gc_set_rebuild's own existing",
" * OOM convention (runtime_gc.c). */",
"static void sl_task_stack_init(sl_task *t, void (*entry)(void *), void *arg) {",
"    t->stack_size = SL_TASK_INITIAL_STACK_SIZE;",
"    void *raw = malloc(t->stack_size + 16);",
"    if (!raw) {",
"        fprintf(stderr, \"slang: out of memory allocating task stack\\n\");",
"        exit(1);",
"    }",
"    t->raw_base = raw;",
"    t->stack_base = (void *)(((uintptr_t)raw + 15) & ~(uintptr_t)15);",
"    sl_ctx_make(t, entry, arg);",
"}",
"",
};

const int RUNTIME_SCHED_LEN = sizeof(RUNTIME_SCHED) / sizeof(RUNTIME_SCHED[0]);
