/* Split out of the original monolithic codegen.c -- see
 * internal.h for the shared CG state and cross-file API. */

#include "internal.h"

/* ---- native 'json' package runtime (emitted on demand) ----
 * A generic parse tree (sl_json_val) plus a fixed set of scalar
 * dec/enc helpers is embedded unconditionally when json is imported;
 * per-type decode/encode functions for struct/opt/list/map[str,_]
 * are generated separately by src/codegen/json.c (emit_json_codecs)
 * and reference these helpers by name. */

const char *JSON_RUNTIME[] = {
    "#include <stdarg.h>",
    "",
    "/* ---- json: generic parse tree ---- */",
    "",
    "typedef enum { SL_JV_NULL, SL_JV_BOOL, SL_JV_NUM, SL_JV_STR, SL_JV_ARR, SL_JV_OBJ } sl_jv_kind;",
    "typedef struct sl_json_val sl_json_val;",
    "struct sl_json_val {",
    "    sl_jv_kind kind;",
    "    union {",
    "        bool b;",
    "        double num;",
    "        char *str;",
    "        struct { sl_json_val **items; long long len; } arr;",
    "        struct { char **keys; sl_json_val **vals; long long len; } obj;",
    "    } as;",
    "};",
    "",
    "#define SL_JSON_MAX_DEPTH 512",
    "",
    "typedef struct {",
    "    const char *s;",
    "    long long len;",
    "    long long pos;",
    "    long long depth;",
    "    char *err;",
    "} sl_jparser;",
    "",
    "static void sl_jerr(sl_jparser *p, const char *fmt, ...) {",
    "    if (p->err) return;",
    "    char buf[256];",
    "    va_list ap;",
    "    va_start(ap, fmt);",
    "    vsnprintf(buf, sizeof(buf), fmt, ap);",
    "    va_end(ap);",
    "    char *m = (char *)GC_malloc(strlen(buf) + 32);",
    "    snprintf(m, strlen(buf) + 32, \"%s (at byte %lld)\", buf, p->pos);",
    "    p->err = m;",
    "}",
    "",
    "static int sl_jpeek(sl_jparser *p) {",
    "    return p->pos < p->len ? (unsigned char)p->s[p->pos] : -1;",
    "}",
    "static int sl_jnext(sl_jparser *p) {",
    "    return p->pos < p->len ? (unsigned char)p->s[p->pos++] : -1;",
    "}",
    "static void sl_jskip_ws(sl_jparser *p) {",
    "    while (p->pos < p->len) {",
    "        char c = p->s[p->pos];",
    "        if (c == ' ' || c == '\\t' || c == '\\n' || c == '\\r') p->pos++;",
    "        else break;",
    "    }",
    "}",
    "",
    "static sl_json_val *sl_jv_new(sl_jv_kind k) {",
    "    sl_json_val *v = (sl_json_val *)GC_malloc(sizeof(sl_json_val));",
    "    v->kind = k;",
    "    return v;",
    "}",
    "",
    "static sl_json_val *sl_jparse_value(sl_jparser *p);",
    "",
    "static int sl_hexval(int c) {",
    "    if (c >= '0' && c <= '9') return c - '0';",
    "    if (c >= 'a' && c <= 'f') return c - 'a' + 10;",
    "    if (c >= 'A' && c <= 'F') return c - 'A' + 10;",
    "    return -1;",
    "}",
    "",
    "static int sl_jparse_hex4(sl_jparser *p) {",
    "    int v = 0;",
    "    for (int i = 0; i < 4; i++) {",
    "        int c = sl_jnext(p);",
    "        int h = sl_hexval(c);",
    "        if (h < 0) { sl_jerr(p, \"invalid \\\\u escape\"); return -1; }",
    "        v = (v << 4) | h;",
    "    }",
    "    return v;",
    "}",
    "",
    "static void sl_utf8_append(char **buf, long long *len, long long *cap, long cp) {",
    "    if (*len + 4 > *cap) {",
    "        *cap = (*cap ? *cap * 2 : 64);",
    "        *buf = (char *)GC_realloc(*buf, (size_t)*cap);",
    "    }",
    "    unsigned char *o = (unsigned char *)*buf + *len;",
    "    if (cp < 0x80) {",
    "        o[0] = (unsigned char)cp;",
    "        *len += 1;",
    "    } else if (cp < 0x800) {",
    "        o[0] = (unsigned char)(0xC0 | (cp >> 6));",
    "        o[1] = (unsigned char)(0x80 | (cp & 0x3F));",
    "        *len += 2;",
    "    } else if (cp < 0x10000) {",
    "        o[0] = (unsigned char)(0xE0 | (cp >> 12));",
    "        o[1] = (unsigned char)(0x80 | ((cp >> 6) & 0x3F));",
    "        o[2] = (unsigned char)(0x80 | (cp & 0x3F));",
    "        *len += 3;",
    "    } else {",
    "        o[0] = (unsigned char)(0xF0 | (cp >> 18));",
    "        o[1] = (unsigned char)(0x80 | ((cp >> 12) & 0x3F));",
    "        o[2] = (unsigned char)(0x80 | ((cp >> 6) & 0x3F));",
    "        o[3] = (unsigned char)(0x80 | (cp & 0x3F));",
    "        *len += 4;",
    "    }",
    "}",
    "",
    "static char *sl_jparse_string_raw(sl_jparser *p) {",
    "    char *buf = NULL;",
    "    long long len = 0, cap = 0;",
    "    for (;;) {",
    "        if (p->pos >= p->len) { sl_jerr(p, \"unterminated string\"); return NULL; }",
    "        int c = sl_jnext(p);",
    "        if (c == '\"') break;",
    "        if (c == '\\\\') {",
    "            int e = sl_jnext(p);",
    "            switch (e) {",
    "            case '\"': sl_utf8_append(&buf, &len, &cap, '\"'); break;",
    "            case '\\\\': sl_utf8_append(&buf, &len, &cap, '\\\\'); break;",
    "            case '/': sl_utf8_append(&buf, &len, &cap, '/'); break;",
    "            case 'b': sl_utf8_append(&buf, &len, &cap, '\\b'); break;",
    "            case 'f': sl_utf8_append(&buf, &len, &cap, '\\f'); break;",
    "            case 'n': sl_utf8_append(&buf, &len, &cap, '\\n'); break;",
    "            case 'r': sl_utf8_append(&buf, &len, &cap, '\\r'); break;",
    "            case 't': sl_utf8_append(&buf, &len, &cap, '\\t'); break;",
    "            case 'u': {",
    "                int cp = sl_jparse_hex4(p);",
    "                if (cp < 0) return NULL;",
    "                if (cp >= 0xD800 && cp <= 0xDBFF) {",
    "                    if (sl_jnext(p) != '\\\\' || sl_jnext(p) != 'u') {",
    "                        sl_jerr(p, \"unpaired UTF-16 surrogate\");",
    "                        return NULL;",
    "                    }",
    "                    int lo = sl_jparse_hex4(p);",
    "                    if (lo < 0) return NULL;",
    "                    if (lo < 0xDC00 || lo > 0xDFFF) {",
    "                        sl_jerr(p, \"invalid low surrogate\");",
    "                        return NULL;",
    "                    }",
    "                    long full = 0x10000 + ((cp - 0xD800) << 10) + (lo - 0xDC00);",
    "                    sl_utf8_append(&buf, &len, &cap, full);",
    "                } else if (cp >= 0xDC00 && cp <= 0xDFFF) {",
    "                    sl_jerr(p, \"unpaired UTF-16 surrogate\");",
    "                    return NULL;",
    "                } else {",
    "                    sl_utf8_append(&buf, &len, &cap, cp);",
    "                }",
    "                break;",
    "            }",
    "            default:",
    "                sl_jerr(p, \"invalid escape '\\\\%c'\", e >= 32 && e < 127 ? e : '?');",
    "                return NULL;",
    "            }",
    "        } else if (c < 0x20) {",
    "            sl_jerr(p, \"control character in string\");",
    "            return NULL;",
    "        } else {",
    "            sl_utf8_append(&buf, &len, &cap, c);",
    "        }",
    "    }",
    "    sl_utf8_append(&buf, &len, &cap, 0);",
    "    return buf ? buf : GC_strdup(\"\");",
    "}",
    "",
    "static sl_json_val *sl_jparse_string(sl_jparser *p) {",
    "    char *s = sl_jparse_string_raw(p);",
    "    if (!s) return NULL;",
    "    sl_json_val *v = sl_jv_new(SL_JV_STR);",
    "    v->as.str = s;",
    "    return v;",
    "}",
    "",
    "static sl_json_val *sl_jparse_number(sl_jparser *p) {",
    "    long long start = p->pos;",
    "    if (sl_jpeek(p) == '-') sl_jnext(p);",
    "    if (sl_jpeek(p) == '0') {",
    "        sl_jnext(p);",
    "    } else if (sl_jpeek(p) >= '1' && sl_jpeek(p) <= '9') {",
    "        while (sl_jpeek(p) >= '0' && sl_jpeek(p) <= '9') sl_jnext(p);",
    "    } else {",
    "        sl_jerr(p, \"invalid number\");",
    "        return NULL;",
    "    }",
    "    if (sl_jpeek(p) == '.') {",
    "        sl_jnext(p);",
    "        if (!(sl_jpeek(p) >= '0' && sl_jpeek(p) <= '9')) {",
    "            sl_jerr(p, \"invalid number: expected digit after '.'\");",
    "            return NULL;",
    "        }",
    "        while (sl_jpeek(p) >= '0' && sl_jpeek(p) <= '9') sl_jnext(p);",
    "    }",
    "    if (sl_jpeek(p) == 'e' || sl_jpeek(p) == 'E') {",
    "        sl_jnext(p);",
    "        if (sl_jpeek(p) == '+' || sl_jpeek(p) == '-') sl_jnext(p);",
    "        if (!(sl_jpeek(p) >= '0' && sl_jpeek(p) <= '9')) {",
    "            sl_jerr(p, \"invalid number: expected digit in exponent\");",
    "            return NULL;",
    "        }",
    "        while (sl_jpeek(p) >= '0' && sl_jpeek(p) <= '9') sl_jnext(p);",
    "    }",
    "    long long n = p->pos - start;",
    "    char *tmp = (char *)GC_malloc(n + 1);",
    "    memcpy(tmp, p->s + start, (size_t)n);",
    "    tmp[n] = 0;",
    "    sl_json_val *v = sl_jv_new(SL_JV_NUM);",
    "    v->as.num = strtod(tmp, NULL);",
    "    return v;",
    "}",
    "",
    "static sl_json_val *sl_jparse_array(sl_jparser *p) {",
    "    if (++p->depth > SL_JSON_MAX_DEPTH) {",
    "        sl_jerr(p, \"maximum nesting depth (%d) exceeded\", SL_JSON_MAX_DEPTH);",
    "        return NULL;",
    "    }",
    "    sl_json_val *v = sl_jv_new(SL_JV_ARR);",
    "    v->as.arr.items = NULL;",
    "    v->as.arr.len = 0;",
    "    long long cap = 0;",
    "    sl_jskip_ws(p);",
    "    if (sl_jpeek(p) == ']') { sl_jnext(p); p->depth--; return v; }",
    "    for (;;) {",
    "        sl_jskip_ws(p);",
    "        sl_json_val *item = sl_jparse_value(p);",
    "        if (!item) { p->depth--; return NULL; }",
    "        if (v->as.arr.len >= cap) {",
    "            cap = cap ? cap * 2 : 4;",
    "            v->as.arr.items = (sl_json_val **)GC_realloc(v->as.arr.items, (size_t)cap * sizeof(sl_json_val *));",
    "        }",
    "        v->as.arr.items[v->as.arr.len++] = item;",
    "        sl_jskip_ws(p);",
    "        int c = sl_jnext(p);",
    "        if (c == ',') continue;",
    "        if (c == ']') break;",
    "        sl_jerr(p, \"expected ',' or ']' in array\");",
    "        p->depth--;",
    "        return NULL;",
    "    }",
    "    p->depth--;",
    "    return v;",
    "}",
    "",
    "static sl_json_val *sl_jparse_object(sl_jparser *p) {",
    "    if (++p->depth > SL_JSON_MAX_DEPTH) {",
    "        sl_jerr(p, \"maximum nesting depth (%d) exceeded\", SL_JSON_MAX_DEPTH);",
    "        return NULL;",
    "    }",
    "    sl_json_val *v = sl_jv_new(SL_JV_OBJ);",
    "    v->as.obj.keys = NULL;",
    "    v->as.obj.vals = NULL;",
    "    v->as.obj.len = 0;",
    "    long long cap = 0;",
    "    sl_jskip_ws(p);",
    "    if (sl_jpeek(p) == '}') { sl_jnext(p); p->depth--; return v; }",
    "    for (;;) {",
    "        sl_jskip_ws(p);",
    "        if (sl_jpeek(p) != '\"') {",
    "            sl_jerr(p, \"expected string key in object\");",
    "            p->depth--;",
    "            return NULL;",
    "        }",
    "        sl_jnext(p);",
    "        char *key = sl_jparse_string_raw(p);",
    "        if (!key) { p->depth--; return NULL; }",
    "        sl_jskip_ws(p);",
    "        if (sl_jnext(p) != ':') {",
    "            sl_jerr(p, \"expected ':' after object key\");",
    "            p->depth--;",
    "            return NULL;",
    "        }",
    "        sl_jskip_ws(p);",
    "        sl_json_val *val = sl_jparse_value(p);",
    "        if (!val) { p->depth--; return NULL; }",
    "        if (v->as.obj.len >= cap) {",
    "            cap = cap ? cap * 2 : 4;",
    "            v->as.obj.keys = (char **)GC_realloc(v->as.obj.keys, (size_t)cap * sizeof(char *));",
    "            v->as.obj.vals = (sl_json_val **)GC_realloc(v->as.obj.vals, (size_t)cap * sizeof(sl_json_val *));",
    "        }",
    "        v->as.obj.keys[v->as.obj.len] = key;",
    "        v->as.obj.vals[v->as.obj.len] = val;",
    "        v->as.obj.len++;",
    "        sl_jskip_ws(p);",
    "        int c = sl_jnext(p);",
    "        if (c == ',') continue;",
    "        if (c == '}') break;",
    "        sl_jerr(p, \"expected ',' or '}' in object\");",
    "        p->depth--;",
    "        return NULL;",
    "    }",
    "    p->depth--;",
    "    return v;",
    "}",
    "",
    "static int sl_jmatch_lit(sl_jparser *p, const char *lit) {",
    "    long long n = (long long)strlen(lit);",
    "    if (p->pos + n > p->len) return 0;",
    "    if (memcmp(p->s + p->pos, lit, (size_t)n) != 0) return 0;",
    "    p->pos += n;",
    "    return 1;",
    "}",
    "",
    "static sl_json_val *sl_jparse_value(sl_jparser *p) {",
    "    sl_jskip_ws(p);",
    "    int c = sl_jpeek(p);",
    "    if (c < 0) { sl_jerr(p, \"unexpected end of input\"); return NULL; }",
    "    if (c == '\"') { sl_jnext(p); return sl_jparse_string(p); }",
    "    if (c == '{') { sl_jnext(p); return sl_jparse_object(p); }",
    "    if (c == '[') { sl_jnext(p); return sl_jparse_array(p); }",
    "    if (c == '-' || (c >= '0' && c <= '9')) return sl_jparse_number(p);",
    "    if (c == 't') {",
    "        if (!sl_jmatch_lit(p, \"true\")) { sl_jerr(p, \"invalid literal\"); return NULL; }",
    "        sl_json_val *v = sl_jv_new(SL_JV_BOOL); v->as.b = true; return v;",
    "    }",
    "    if (c == 'f') {",
    "        if (!sl_jmatch_lit(p, \"false\")) { sl_jerr(p, \"invalid literal\"); return NULL; }",
    "        sl_json_val *v = sl_jv_new(SL_JV_BOOL); v->as.b = false; return v;",
    "    }",
    "    if (c == 'n') {",
    "        if (!sl_jmatch_lit(p, \"null\")) { sl_jerr(p, \"invalid literal\"); return NULL; }",
    "        return sl_jv_new(SL_JV_NULL);",
    "    }",
    "    sl_jerr(p, \"unexpected character '%c'\", c >= 32 && c < 127 ? c : '?');",
    "    return NULL;",
    "}",
    "",
    "static sl_json_val *sl_json_parse(const char *s, long long len, char **errmsg) {",
    "    sl_jparser p = { s, len, 0, 0, NULL };",
    "    sl_json_val *v = sl_jparse_value(&p);",
    "    if (!v) { *errmsg = p.err; return NULL; }",
    "    sl_jskip_ws(&p);",
    "    if (p.pos != p.len) {",
    "        sl_jerr(&p, \"trailing garbage after JSON value\");",
    "        *errmsg = p.err;",
    "        return NULL;",
    "    }",
    "    *errmsg = NULL;",
    "    return v;",
    "}",
    "",
    "/* ---- json: struct-object field lookup ---- */",
    "",
    "static sl_json_val *sl_json_obj_get(sl_json_val *v, const char *key) {",
    "    for (long long i = 0; i < v->as.obj.len; i++)",
    "        if (!strcmp(v->as.obj.keys[i], key))",
    "            return v->as.obj.vals[i];",
    "    return NULL;",
    "}",
    "",
    "static const char *sl_json_kind_name(sl_json_val *v) {",
    "    switch (v->kind) {",
    "    case SL_JV_NULL: return \"null\";",
    "    case SL_JV_BOOL: return \"a boolean\";",
    "    case SL_JV_NUM:  return \"a number\";",
    "    case SL_JV_STR:  return \"a string\";",
    "    case SL_JV_ARR:  return \"an array\";",
    "    case SL_JV_OBJ:  return \"an object\";",
    "    }",
    "    return \"a value\";",
    "}",
    "",
    "/* ---- json: error message helpers ---- */",
    "",
    "static char *sl_json_errf(const char *fmt, ...) {",
    "    char buf[256];",
    "    va_list ap;",
    "    va_start(ap, fmt);",
    "    vsnprintf(buf, sizeof(buf), fmt, ap);",
    "    va_end(ap);",
    "    return GC_strdup(buf);",
    "}",
    "",
    "static char *sl_json_wrap_err(const char *ctx, char *inner) {",
    "    size_t n = strlen(ctx) + strlen(inner) + 4;",
    "    char *m = (char *)GC_malloc(n);",
    "    snprintf(m, n, \"%s: %s\", ctx, inner);",
    "    return m;",
    "}",
    "",
    "/* ---- json: scalar decode helpers ---- */",
    "",
    "static bool sl_json_dec_num(sl_json_val *v, double *out, char **err) {",
    "    if (v->kind != SL_JV_NUM) {",
    "        *err = sl_json_errf(\"expected a number, got %s\", sl_json_kind_name(v));",
    "        return false;",
    "    }",
    "    *out = v->as.num;",
    "    return true;",
    "}",
    "",
    "static bool sl_json_dec_bool(sl_json_val *v, bool *out, char **err) {",
    "    if (v->kind != SL_JV_BOOL) {",
    "        *err = sl_json_errf(\"expected a boolean, got %s\", sl_json_kind_name(v));",
    "        return false;",
    "    }",
    "    *out = v->as.b;",
    "    return true;",
    "}",
    "",
    "static bool sl_json_dec_str(sl_json_val *v, const char **out, char **err) {",
    "    if (v->kind != SL_JV_STR) {",
    "        *err = sl_json_errf(\"expected a string, got %s\", sl_json_kind_name(v));",
    "        return false;",
    "    }",
    "    *out = v->as.str;",
    "    return true;",
    "}",
    "",
    "/* Casting an out-of-range double to long long is undefined behavior,",
    " * so the magnitude check must come BEFORE any cast -- never after,",
    " * and never combined into the same expression as one. */",
    "#define SL_JSON_INT_DEC(NAME, T, LO, HI)                                    \\",
    "    static bool NAME(sl_json_val *v, T *out, char **err) {                  \\",
    "        double d;                                                           \\",
    "        if (!sl_json_dec_num(v, &d, err)) return false;                     \\",
    "        if (d < -9223372036854775808.0 || d >= 9223372036854775808.0) {     \\",
    "            *err = sl_json_errf(\"value %g out of range\", d);                \\",
    "            return false;                                                  \\",
    "        }                                                                   \\",
    "        long long ll = (long long)d;                                        \\",
    "        if ((double)ll != d) {                                              \\",
    "            *err = sl_json_errf(\"expected an integer, got %g\", d);          \\",
    "            return false;                                                  \\",
    "        }                                                                   \\",
    "        if (ll < (long long)(LO) || ll > (long long)(HI)) {                 \\",
    "            *err = sl_json_errf(\"value %lld out of range\", ll);             \\",
    "            return false;                                                  \\",
    "        }                                                                   \\",
    "        *out = (T)ll;                                                       \\",
    "        return true;                                                        \\",
    "    }",
    "",
    "SL_JSON_INT_DEC(sl_json_dec_i8, int8_t, INT8_MIN, INT8_MAX)",
    "SL_JSON_INT_DEC(sl_json_dec_i16, int16_t, INT16_MIN, INT16_MAX)",
    "SL_JSON_INT_DEC(sl_json_dec_i32, int32_t, INT32_MIN, INT32_MAX)",
    "SL_JSON_INT_DEC(sl_json_dec_u8, uint8_t, 0, UINT8_MAX)",
    "SL_JSON_INT_DEC(sl_json_dec_u16, uint16_t, 0, UINT16_MAX)",
    "SL_JSON_INT_DEC(sl_json_dec_u32, uint32_t, 0, UINT32_MAX)",
    "",
    "static bool sl_json_dec_i64(sl_json_val *v, int64_t *out, char **err) {",
    "    double d;",
    "    if (!sl_json_dec_num(v, &d, err)) return false;",
    "    if (d < -9223372036854775808.0 || d >= 9223372036854775808.0) {",
    "        *err = sl_json_errf(\"value %g out of range for i64\", d);",
    "        return false;",
    "    }",
    "    long long ll = (long long)d;",
    "    if ((double)ll != d) {",
    "        *err = sl_json_errf(\"expected an integer, got %g\", d);",
    "        return false;",
    "    }",
    "    *out = (int64_t)ll;",
    "    return true;",
    "}",
    "",
    "static bool sl_json_dec_u64(sl_json_val *v, uint64_t *out, char **err) {",
    "    double d;",
    "    if (!sl_json_dec_num(v, &d, err)) return false;",
    "    if (d < 0) {",
    "        *err = sl_json_errf(\"expected a non-negative integer, got %g\", d);",
    "        return false;",
    "    }",
    "    if (d >= 18446744073709551616.0) {",
    "        *err = sl_json_errf(\"value %g out of range for u64\", d);",
    "        return false;",
    "    }",
    "    unsigned long long ull = (unsigned long long)d;",
    "    if ((double)ull != d) {",
    "        *err = sl_json_errf(\"expected an integer, got %g\", d);",
    "        return false;",
    "    }",
    "    *out = (uint64_t)ull;",
    "    return true;",
    "}",
    "",
    "static bool sl_json_dec_f32(sl_json_val *v, float *out, char **err) {",
    "    double d;",
    "    if (!sl_json_dec_num(v, &d, err)) return false;",
    "    *out = (float)d;",
    "    return true;",
    "}",
    "",
    "static bool sl_json_dec_f64(sl_json_val *v, double *out, char **err) {",
    "    return sl_json_dec_num(v, out, err);",
    "}",
    "",
    "/* ---- json: output string builder ---- */",
    "",
    "typedef struct { char *data; long long len, cap; } sl_json_sb;",
    "",
    "static void sl_json_sb_init(sl_json_sb *sb) {",
    "    sb->data = NULL;",
    "    sb->len = 0;",
    "    sb->cap = 0;",
    "}",
    "",
    "static void sl_json_sb_append_n(sl_json_sb *sb, const char *s, long long n) {",
    "    if (sb->len + n + 1 > sb->cap) {",
    "        long long cap = sb->cap ? sb->cap * 2 : 64;",
    "        while (cap < sb->len + n + 1) cap *= 2;",
    "        sb->data = (char *)GC_realloc(sb->data, (size_t)cap);",
    "        sb->cap = cap;",
    "    }",
    "    memcpy(sb->data + sb->len, s, (size_t)n);",
    "    sb->len += n;",
    "    sb->data[sb->len] = 0;",
    "}",
    "",
    "static void sl_json_sb_append(sl_json_sb *sb, const char *s) {",
    "    sl_json_sb_append_n(sb, s, (long long)strlen(s));",
    "}",
    "",
    "/* ---- json: scalar encode helpers ---- */",
    "",
    "static void sl_json_enc_str(const char *s, sl_json_sb *out) {",
    "    sl_json_sb_append_n(out, \"\\\"\", 1);",
    "    for (const unsigned char *p = (const unsigned char *)s; *p; p++) {",
    "        switch (*p) {",
    "        case '\"':  sl_json_sb_append(out, \"\\\\\\\"\"); break;",
    "        case '\\\\': sl_json_sb_append(out, \"\\\\\\\\\"); break;",
    "        case '\\n': sl_json_sb_append(out, \"\\\\n\"); break;",
    "        case '\\r': sl_json_sb_append(out, \"\\\\r\"); break;",
    "        case '\\t': sl_json_sb_append(out, \"\\\\t\"); break;",
    "        case '\\b': sl_json_sb_append(out, \"\\\\b\"); break;",
    "        case '\\f': sl_json_sb_append(out, \"\\\\f\"); break;",
    "        default:",
    "            if (*p < 0x20) {",
    "                char buf[8];",
    "                snprintf(buf, sizeof(buf), \"\\\\u%04x\", *p);",
    "                sl_json_sb_append(out, buf);",
    "            } else {",
    "                char c = (char)*p;",
    "                sl_json_sb_append_n(out, &c, 1);",
    "            }",
    "        }",
    "    }",
    "    sl_json_sb_append_n(out, \"\\\"\", 1);",
    "}",
    "",
    "static void sl_json_enc_i64(long long v, sl_json_sb *out) {",
    "    char buf[32];",
    "    snprintf(buf, sizeof(buf), \"%lld\", v);",
    "    sl_json_sb_append(out, buf);",
    "}",
    "",
    "static void sl_json_enc_u64(unsigned long long v, sl_json_sb *out) {",
    "    char buf[32];",
    "    snprintf(buf, sizeof(buf), \"%llu\", v);",
    "    sl_json_sb_append(out, buf);",
    "}",
    "",
    "static void sl_json_enc_f64(double v, sl_json_sb *out) {",
    "    char buf[64];",
    "    snprintf(buf, sizeof(buf), \"%g\", v);",
    "    sl_json_sb_append(out, buf);",
    "}",
    "",
    "static void sl_json_enc_bool(bool v, sl_json_sb *out) {",
    "    sl_json_sb_append(out, v ? \"true\" : \"false\");",
    "}",
    "",
    "static void sl_json_enc_null(sl_json_sb *out) {",
    "    sl_json_sb_append(out, \"null\");",
    "}",
    "",
    "/* ---- json: map iteration helpers (sl_map is defined earlier in",
    " * RUNTIME; these read its fields directly, in insertion order) ---- */",
    "",
    "static const char *sl_json_map_key_at(sl_map *m, long long i) {",
    "    long long slot = m->order[i];",
    "    return *(const char **)(m->keys + (size_t)slot * m->ksz);",
    "}",
    "",
    "static void *sl_json_map_val_at(sl_map *m, long long i) {",
    "    long long slot = m->order[i];",
    "    return m->vals + (size_t)slot * m->vsz;",
    "}",
};

const int JSON_RUNTIME_LEN = sizeof(JSON_RUNTIME) / sizeof(JSON_RUNTIME[0]);
