/* Split out of the original monolithic codegen.c -- see
 * internal.h for the shared CG state and cross-file API. */

#include "internal.h"


/* ------------------------------------------------------------------ */
/* Program-level generation                                            */
/* ------------------------------------------------------------------ */

/* The runtime embedded into every generated program. Kept as plain C
 * source lines so it reads exactly like hand-written code. Split into
 * two arrays: this one (prelude through sl_rt_error) is emitted first;
 * RUNTIME_CONTAINERS (chan/bytes/arr/map/strings, defined below) is
 * emitted after RUNTIME_GC (runtime_gc.c) since those containers now
 * allocate through sl_gc_alloc, which RUNTIME_GC defines. */
const char *RUNTIME[] = {
    "#include <stdio.h>",
    "#include <stdlib.h>",
    "#include <string.h>",
    "#include <stdbool.h>",
    "#include <stdint.h>",
    "#include <stdatomic.h>",
    "#include <pthread.h>",
    "",
    "/* ---- slang runtime ---- */",
    "",
    "/* set once, at the very top of main(); every spawned task's",
    " * trampoline runs with the default (0) value, so runtime errors",
    " * can tell 'the main task' apart from 'a spawned task' and",
    " * isolate a spawned task's failure instead of killing everyone */",
    "static _Thread_local int sl_rt_is_main_thread = 0;",
    "",
    "/* number of 'spawn'ed tasks currently running -- incremented right",
    " * before pthread_create, decremented once the task's function",
    " * returns OR (via sl_rt_error below) panics; proc.active_tasks()",
    " * reads this so a shutting-down program can wait out in-flight",
    " * work instead of dropping it. Maintained unconditionally whenever",
    " * 'spawn' is used, whether or not the program imports 'proc'. */",
    "static atomic_llong sl_rt_active_spawns = 0;",
    "",
    "static void sl_rt_active_spawns_inc(void) {",
    "    atomic_fetch_add(&sl_rt_active_spawns, 1);",
    "}",
    "",
    "static void sl_rt_active_spawns_dec(void) {",
    "    atomic_fetch_sub(&sl_rt_active_spawns, 1);",
    "}",
    "",
    "/* Tier 10: a lexically-scoped chain of GC root lists, one per",
    " * currently in-flight call-site safepoint on this thread (the",
    " * same 'handle stack' shape OCaml's C FFI CAMLparam/CAMLlocal",
    " * uses). Walked by the collector (runtime_gc.c) via each",
    " * registered thread's own copy of this pointer. _Thread_local like",
    " * sl_rt_is_main_thread above, so every OS thread (main, the worker",
    " * pool, any spawn trampoline) gets its own independent, correctly",
    " * zero-initialized chain for free. */",
    "typedef struct sl_safepoint {",
    "    struct sl_safepoint *prev;",
    "    void **roots;",
    "    int nroots;",
    "} sl_safepoint;",
    "",
    "static _Thread_local sl_safepoint *sl_rt_safepoint_top = NULL;",
    "",
    "static inline void sl_rt_gc_checkin(void); /* runtime_gc.c, forward here */",
    "",
    "/* sl_rt_gc_checkin() runs *after* this frame is linked into the",
    " * chain, not before: every call-site bracket builds its complete",
    " * roots array -- already-evaluated temps included -- before this",
    " * function is even called, so a collection that ran before sp were",
    " * linked in would not yet find those temps reachable through",
    " * anything. Checking in only once sp is live closes that gap; the",
    " * cost is that a collection can run one bracket-entry later than a",
    " * naive 'checkin first' placement would, which is harmless (nothing",
    " * before this point could have allocated on top of an unrooted",
    " * value -- that's the entire point of building the array first). */",
    "static inline void sl_rt_safepoint_enter(sl_safepoint *sp, void **roots,",
    "                                         int nroots) {",
    "    sp->roots = roots;",
    "    sp->nroots = nroots;",
    "    sp->prev = sl_rt_safepoint_top;",
    "    sl_rt_safepoint_top = sp;",
    "    sl_rt_gc_checkin();",
    "}",
    "",
    "static inline void sl_rt_safepoint_exit(void) {",
    "    sl_rt_safepoint_top = sl_rt_safepoint_top->prev;",
    "}",
    "",
    "static void sl_rt_error(const char *msg, long long a, long long b) {",
    "    if (!sl_rt_is_main_thread) {",
    "        fprintf(stderr,",
    "                \"slang: task panicked: %s (index %lld, length %lld)\\n\",",
    "                msg, a, b);",
    "        sl_rt_active_spawns_dec();",
    "        pthread_exit(NULL);",
    "    }",
    "    fprintf(stderr, \"slang runtime error: %s (index %lld, length %lld)\\n\",",
    "            msg, a, b);",
    "    exit(1);",
    "}",
    "",
};

const int RUNTIME_LEN = sizeof(RUNTIME) / sizeof(RUNTIME[0]);

/* chan[T]/bytes/[T]/map[K]V/strings: the four fixed heap-object shapes
 * plus string helpers. Emitted after RUNTIME_GC (runtime_gc.c), which
 * this array depends on for sl_gc_alloc/sl_gc_realloc/sl_gc_mark, and
 * after which every codegen-generated struct/opt/result/spawn-shape
 * tracer follows (program.c's emission order). Every allocation here
 * either has no inner pointers (traced as NULL) or is one of these four
 * containers, each carrying its own element/key/value "is this slot a
 * GC pointer" flag(s) set at construction and consulted by its own
 * trace function -- see the design plan for why arrays/maps/chans never
 * need per-element-type-specialized tracers: every GC-tracked slang
 * type is represented as exactly one C pointer, so an element slot is
 * always either "one pointer to mark" or "no pointer," a single bool
 * per container instance. */
const char *RUNTIME_CONTAINERS[] = {
    "/* ---- chan[T]: bounded, thread-safe queue for 'spawn'ed tasks ---- */",
    "",
    "typedef struct {",
    "    unsigned char *buf;",
    "    size_t elemsz;",
    "    int cap, head, count, closed;",
    "    int elem_is_ptr;",
    "    pthread_mutex_t mu;",
    "    pthread_cond_t not_empty;",
    "    pthread_cond_t not_full;",
    "} sl_chan;",
    "",
    "static void sl_gc_trace_chan(void *p, void (*mark)(void *)) {",
    "    sl_chan *c = (sl_chan *)p;",
    "    if (!c->buf) return;",
    "    mark(c->buf);",
    "    if (!c->elem_is_ptr) return;",
    "    for (int i = 0; i < c->cap; i++)",
    "        mark(*(void **)(c->buf + (size_t)i * c->elemsz));",
    "}",
    "",
    "static sl_chan *sl_chan_new(size_t elemsz, int cap, int elem_is_ptr) {",
    "    if (cap < 1) cap = 1;",
    "    sl_chan *c = (sl_chan *)sl_gc_alloc(sizeof(sl_chan), sl_gc_trace_chan);",
    "    c->buf = (unsigned char *)sl_gc_alloc(elemsz * (size_t)cap, NULL);",
    "    c->elemsz = elemsz;",
    "    c->cap = cap;",
    "    c->head = 0;",
    "    c->count = 0;",
    "    c->closed = 0;",
    "    c->elem_is_ptr = elem_is_ptr;",
    "    pthread_mutex_init(&c->mu, NULL);",
    "    pthread_cond_init(&c->not_empty, NULL);",
    "    pthread_cond_init(&c->not_full, NULL);",
    "    return c;",
    "}",
    "",
    "static void sl_chan_send(sl_chan *c, const void *val) {",
    "    pthread_mutex_lock(&c->mu);",
    "    while (c->count == c->cap && !c->closed) {",
    "        sl_rt_gc_blocked = 1;",
    "        pthread_cond_wait(&c->not_full, &c->mu);",
    "        sl_rt_gc_blocked = 0;",
    "        sl_rt_gc_checkin();",
    "    }",
    "    if (c->closed) {",
    "        pthread_mutex_unlock(&c->mu);",
    "        sl_rt_error(\"send on closed channel\", 0, 0);",
    "        return;",
    "    }",
    "    int tail = (c->head + c->count) % c->cap;",
    "    memcpy(c->buf + (size_t)tail * c->elemsz, val, c->elemsz);",
    "    c->count++;",
    "    pthread_cond_signal(&c->not_empty);",
    "    pthread_mutex_unlock(&c->mu);",
    "}",
    "",
    "/* returns 1 with *out populated, or 0 if closed and drained empty */",
    "static int sl_chan_recv(sl_chan *c, void *out) {",
    "    pthread_mutex_lock(&c->mu);",
    "    while (c->count == 0 && !c->closed) {",
    "        sl_rt_gc_blocked = 1;",
    "        pthread_cond_wait(&c->not_empty, &c->mu);",
    "        sl_rt_gc_blocked = 0;",
    "        sl_rt_gc_checkin();",
    "    }",
    "    if (c->count == 0) {",
    "        pthread_mutex_unlock(&c->mu);",
    "        return 0;",
    "    }",
    "    memcpy(out, c->buf + (size_t)c->head * c->elemsz, c->elemsz);",
    "    c->head = (c->head + 1) % c->cap;",
    "    c->count--;",
    "    pthread_cond_signal(&c->not_full);",
    "    pthread_mutex_unlock(&c->mu);",
    "    return 1;",
    "}",
    "",
    "static void sl_chan_close(sl_chan *c) {",
    "    pthread_mutex_lock(&c->mu);",
    "    c->closed = 1;",
    "    pthread_cond_broadcast(&c->not_empty);",
    "    pthread_cond_broadcast(&c->not_full);",
    "    pthread_mutex_unlock(&c->mu);",
    "}",
    "",
    "/* ---- bytes: length-prefixed, binary-safe sequences ---- */",
    "",
    "typedef struct { long long len; unsigned char *ptr; } sl_bytes;",
    "",
    "static void sl_gc_trace_bytes(void *p, void (*mark)(void *)) {",
    "    mark(((sl_bytes *)p)->ptr);",
    "}",
    "",
    "static sl_bytes *sl_bytes_new(const unsigned char *p, long long n) {",
    "    sl_bytes *b = (sl_bytes *)sl_gc_alloc(sizeof(sl_bytes), sl_gc_trace_bytes);",
    "    b->len = n;",
    "    b->ptr = (unsigned char *)sl_gc_alloc((size_t)(n > 0 ? n : 1), NULL);",
    "    if (n > 0) memcpy(b->ptr, p, (size_t)n);",
    "    return b;",
    "}",
    "",
    "static int sl_bytes_at(sl_bytes *b, long long i) {",
    "    if (i < 0 || i >= b->len)",
    "        sl_rt_error(\"byte index out of bounds\", i, b->len);",
    "    return (int)b->ptr[i];",
    "}",
    "",
    "static void sl_bytes_set(sl_bytes *b, long long i, unsigned char v) {",
    "    if (i < 0 || i >= b->len)",
    "        sl_rt_error(\"byte index out of bounds\", i, b->len);",
    "    b->ptr[i] = v;",
    "}",
    "",
    "static sl_bytes *sl_bytes_concat(sl_bytes *a, sl_bytes *b) {",
    "    sl_bytes *r = (sl_bytes *)sl_gc_alloc(sizeof(sl_bytes), sl_gc_trace_bytes);",
    "    r->len = a->len + b->len;",
    "    r->ptr = (unsigned char *)sl_gc_alloc((size_t)(r->len > 0 ? r->len : 1), NULL);",
    "    if (a->len) memcpy(r->ptr, a->ptr, (size_t)a->len);",
    "    if (b->len) memcpy(r->ptr + a->len, b->ptr, (size_t)b->len);",
    "    return r;",
    "}",
    "",
    "static sl_bytes *sl_bytes_slice(sl_bytes *b, long long s, long long e) {",
    "    if (s < 0) s = 0;",
    "    if (e > b->len) e = b->len;",
    "    if (e < s) e = s;",
    "    sl_bytes *r = (sl_bytes *)sl_gc_alloc(sizeof(sl_bytes), sl_gc_trace_bytes);",
    "    r->len = e - s;",
    "    r->ptr = (unsigned char *)sl_gc_alloc((size_t)(r->len > 0 ? r->len : 1), NULL);",
    "    if (r->len) memcpy(r->ptr, b->ptr + s, (size_t)r->len);",
    "    return r;",
    "}",
    "",
    "static int sl_bytes_eq(sl_bytes *a, sl_bytes *b) {",
    "    if (a->len != b->len) return 0;",
    "    return a->len == 0 || memcmp(a->ptr, b->ptr, (size_t)a->len) == 0;",
    "}",
    "",
    "static char *sl_str_from_bytes(sl_bytes *b) {",
    "    char *p = (char *)sl_gc_alloc((size_t)b->len + 1, NULL);",
    "    if (b->len) memcpy(p, b->ptr, (size_t)b->len);",
    "    p[b->len] = 0;",
    "    return p;",
    "}",
    "",
    "static sl_bytes *sl_bytes_from_str(const char *s) {",
    "    return sl_bytes_new((const unsigned char *)s, (long long)strlen(s));",
    "}",
    "",
    "static sl_bytes *sl_to_le(unsigned long long v) {",
    "    unsigned char buf[8];",
    "    for (int i = 0; i < 8; i++)",
    "        buf[i] = (unsigned char)((v >> (8 * i)) & 0xff);",
    "    return sl_bytes_new(buf, 8);",
    "}",
    "",
    "static sl_bytes *sl_to_be(unsigned long long v) {",
    "    unsigned char buf[8];",
    "    for (int i = 0; i < 8; i++)",
    "        buf[7 - i] = (unsigned char)((v >> (8 * i)) & 0xff);",
    "    return sl_bytes_new(buf, 8);",
    "}",
    "",
    "static unsigned long long sl_from_le(sl_bytes *b) {",
    "    if (b->len != 8)",
    "        sl_rt_error(\"from_le expects exactly 8 bytes\", b->len, 8);",
    "    unsigned long long v = 0;",
    "    for (int i = 7; i >= 0; i--) v = (v << 8) | b->ptr[i];",
    "    return v;",
    "}",
    "",
    "static unsigned long long sl_from_be(sl_bytes *b) {",
    "    if (b->len != 8)",
    "        sl_rt_error(\"from_be expects exactly 8 bytes\", b->len, 8);",
    "    unsigned long long v = 0;",
    "    for (int i = 0; i < 8; i++) v = (v << 8) | b->ptr[i];",
    "    return v;",
    "}",
    "",
    "/* ---- growable arrays over GC memory ---- */",
    "",
    "typedef struct {",
    "    long long len, cap;",
    "    unsigned char *data; /* elements stored inline */",
    "    size_t esz;          /* element size in bytes */",
    "    int elem_is_ptr;",
    "} sl_arr;",
    "",
    "static void sl_gc_trace_arr(void *p, void (*mark)(void *)) {",
    "    sl_arr *a = (sl_arr *)p;",
    "    if (!a->data) return;",
    "    mark(a->data);",
    "    if (!a->elem_is_ptr) return;",
    "    for (long long i = 0; i < a->len; i++)",
    "        mark(*(void **)(a->data + (size_t)i * a->esz));",
    "}",
    "",
    "static sl_arr *sl_arr_new(size_t esz, int elem_is_ptr) {",
    "    sl_arr *a = (sl_arr *)sl_gc_alloc(sizeof(sl_arr), sl_gc_trace_arr);",
    "    a->len = 0;",
    "    a->cap = 0;",
    "    a->data = NULL;",
    "    a->esz = esz;",
    "    a->elem_is_ptr = elem_is_ptr;",
    "    return a;",
    "}",
    "",
    "static void sl_arr_reserve(sl_arr *a, long long need) {",
    "    if (need <= a->cap) return;",
    "    long long cap = a->cap ? a->cap : 8;",
    "    while (cap < need) cap *= 2;",
    "    a->data = (unsigned char *)sl_gc_realloc(a->data, (size_t)cap * a->esz);",
    "    a->cap = cap;",
    "}",
    "",
    "static void *sl_arr_get(sl_arr *a, long long i, size_t esz) {",
    "    if (esz != a->esz)",
    "        sl_rt_error(\"internal: element size mismatch\", (long long)esz,",
    "                    (long long)a->esz);",
    "    if (i < 0 || i >= a->len)",
    "        sl_rt_error(\"list index out of bounds\", i, a->len);",
    "    return a->data + (size_t)i * esz;",
    "}",
    "",
    "static void sl_arr_push(sl_arr *a, void *val, size_t esz) {",
    "    if (esz != a->esz)",
    "        sl_rt_error(\"internal: element size mismatch\", (long long)esz,",
    "                    (long long)a->esz);",
    "    sl_arr_reserve(a, a->len + 1);",
    "    memcpy(a->data + (size_t)a->len * esz, val, esz);",
    "    a->len++;",
    "}",
    "",
    "static void *sl_arr_pop(sl_arr *a, size_t esz) {",
    "    if (esz != a->esz)",
    "        sl_rt_error(\"internal: element size mismatch\", (long long)esz,",
    "                    (long long)a->esz);",
    "    if (a->len == 0) sl_rt_error(\"pop from empty list\", 0, 0);",
    "    a->len--;",
    "    return a->data + (size_t)a->len * esz;",
    "}",
    "",
    "static sl_arr *sl_arr_from(void *buf, long long n, size_t esz, int elem_is_ptr) {",
    "    sl_arr *a = sl_arr_new(esz, elem_is_ptr);",
    "    sl_arr_reserve(a, n);",
    "    if (n > 0) memcpy(a->data, buf, (size_t)n * esz);",
    "    a->len = n;",
    "    return a;",
    "}",
    "",
    "static sl_arr *sl_arr_slice(sl_arr *a, long long s, long long e) {",
    "    if (s < 0) s = 0;",
    "    if (e > a->len) e = a->len;",
    "    if (e < s) e = s;",
    "    sl_arr *r = sl_arr_new(a->esz, a->elem_is_ptr);",
    "    sl_arr_reserve(r, e - s);",
    "    if (e > s)",
    "        memcpy(r->data, a->data + (size_t)s * a->esz,",
    "               (size_t)(e - s) * a->esz);",
    "    r->len = e - s;",
    "    return r;",
    "}",
    "",
    "static sl_arr *sl_arr_concat(sl_arr *a, sl_arr *b) {",
    "    if (a->esz != b->esz)",
    "        sl_rt_error(\"cannot concatenate lists of different element types\",",
    "                    (long long)a->esz, (long long)b->esz);",
    "    sl_arr *r = sl_arr_new(a->esz, a->elem_is_ptr);",
    "    sl_arr_reserve(r, a->len + b->len);",
    "    if (a->len) memcpy(r->data, a->data, (size_t)a->len * a->esz);",
    "    if (b->len)",
    "        memcpy(r->data + (size_t)a->len * a->esz, b->data,",
    "               (size_t)b->len * b->esz);",
    "    r->len = a->len + b->len;",
    "    return r;",
    "}",
    "",
    "/* ---- maps: open-addressing hash tables over GC memory ---- */",
    "",
    "typedef struct {",
    "    long long count, cap;",
    "    size_t ksz, vsz;",
    "    int kstr;            /* keys are NUL-terminated strings */",
    "    int key_is_ptr, val_is_ptr;",
    "    unsigned char *keys; /* cap slots */",
    "    unsigned char *vals; /* cap slots */",
    "    unsigned char *state;/* 1 = occupied */",
    "    long long *order;    /* occupied slot indices, insertion order */",
    "} sl_map;",
    "",
    "static void sl_gc_trace_map(void *p, void (*mark)(void *)) {",
    "    sl_map *m = (sl_map *)p;",
    "    if (m->keys) mark(m->keys);",
    "    if (m->vals) mark(m->vals);",
    "    if (m->state) mark(m->state);",
    "    if (m->order) mark(m->order);",
    "    if (!m->key_is_ptr && !m->val_is_ptr) return;",
    "    for (long long i = 0; i < m->count; i++) {",
    "        long long slot = m->order[i];",
    "        if (m->key_is_ptr)",
    "            mark(*(void **)(m->keys + (size_t)slot * m->ksz));",
    "        if (m->val_is_ptr)",
    "            mark(*(void **)(m->vals + (size_t)slot * m->vsz));",
    "    }",
    "}",
    "",
    "static unsigned long long sl_hash_bytes(const unsigned char *p, size_t n) {",
    "    unsigned long long h = 1469598103934665603ULL;",
    "    for (size_t i = 0; i < n; i++) { h ^= p[i]; h *= 1099511628211ULL; }",
    "    return h;",
    "}",
    "",
    "static unsigned long long sl_hash_str(const char *s) {",
    "    unsigned long long h = 1469598103934665603ULL;",
    "    for (; *s; s++) { h ^= (unsigned char)*s; h *= 1099511628211ULL; }",
    "    return h;",
    "}",
    "",
    "static sl_map *sl_map_new(size_t ksz, size_t vsz, int kstr,",
    "                           int key_is_ptr, int val_is_ptr) {",
    "    sl_map *m = (sl_map *)sl_gc_alloc(sizeof(sl_map), sl_gc_trace_map);",
    "    m->count = 0;",
    "    m->cap = 8;",
    "    m->ksz = ksz;",
    "    m->vsz = vsz;",
    "    m->kstr = kstr;",
    "    m->key_is_ptr = key_is_ptr;",
    "    m->val_is_ptr = val_is_ptr;",
    "    m->keys = (unsigned char *)sl_gc_alloc(8 * ksz, NULL);",
    "    m->vals = (unsigned char *)sl_gc_alloc(8 * vsz, NULL);",
    "    m->state = (unsigned char *)sl_gc_alloc(8, NULL);",
    "    m->order = (long long *)sl_gc_alloc(8 * sizeof(long long), NULL);",
    "    return m;",
    "}",
    "",
    "/* Probe for a key: returns its slot if present, or -(slot)-1 for",
    " * the first empty slot where it could be inserted. */",
    "static long long sl_map_probe(sl_map *m, const void *k,",
    "                              unsigned long long h) {",
    "    long long mask = m->cap - 1;",
    "    long long i = (long long)(h & (unsigned long long)mask);",
    "    for (;;) {",
    "        if (!m->state[i])",
    "            return -i - 1;",
    "        void *kk = m->keys + (size_t)i * m->ksz;",
    "        int eq = m->kstr",
    "                    ? !strcmp(*(const char **)kk, *(const char *const *)k)",
    "                    : memcmp(kk, k, m->ksz) == 0;",
    "        if (eq)",
    "            return i;",
    "        i = (i + 1) & mask;",
    "    }",
    "}",
    "",
    "static void sl_map_grow(sl_map *m) {",
    "    long long old_cap = m->cap;",
    "    unsigned char *ok = m->keys, *ov = m->vals;",
    "    unsigned char *ost = m->state;",
    "    long long ocount = m->count;",
    "    long long *oorder = m->order;",
    "    m->cap = old_cap * 2;",
    "    m->count = 0;",
    "    m->keys = (unsigned char *)sl_gc_alloc((size_t)m->cap * m->ksz, NULL);",
    "    m->vals = (unsigned char *)sl_gc_alloc((size_t)m->cap * m->vsz, NULL);",
    "    m->state = (unsigned char *)sl_gc_alloc((size_t)m->cap, NULL);",
    "    m->order = (long long *)sl_gc_alloc((size_t)m->cap * sizeof(long long), NULL);",
    "    (void)ost;",
    "    /* reinsert in insertion order so iteration stays deterministic */",
    "    for (long long i = 0; i < ocount; i++) {",
    "        long long slot = oorder[i];",
    "        void *k = ok + (size_t)slot * m->ksz;",
    "        void *v = ov + (size_t)slot * m->vsz;",
    "        unsigned long long h = m->kstr",
    "                                  ? sl_hash_str(*(const char **)k)",
    "                                  : sl_hash_bytes((const unsigned char *)k,",
    "                                                  m->ksz);",
    "        long long s = -sl_map_probe(m, k, h) - 1;",
    "        memcpy(m->keys + (size_t)s * m->ksz, k, m->ksz);",
    "        memcpy(m->vals + (size_t)s * m->vsz, v, m->vsz);",
    "        m->state[s] = 1;",
    "        m->order[m->count++] = s;",
    "    }",
    "}",
    "",
    "static void sl_map_put(sl_map *m, const void *k, const void *v) {",
    "    unsigned long long h = m->kstr",
    "                              ? sl_hash_str(*(const char *const *)k)",
    "                              : sl_hash_bytes((const unsigned char *)k,",
    "                                              m->ksz);",
    "    if ((m->count + 1) * 4 >= m->cap * 3)",
    "        sl_map_grow(m);",
    "    long long s = sl_map_probe(m, k, h);",
    "    if (s >= 0) {",
    "        memcpy(m->vals + (size_t)s * m->vsz, v, m->vsz);",
    "        return;",
    "    }",
    "    s = -s - 1;",
    "    memcpy(m->keys + (size_t)s * m->ksz, k, m->ksz);",
    "    memcpy(m->vals + (size_t)s * m->vsz, v, m->vsz);",
    "    m->state[s] = 1;",
    "    m->order[m->count++] = s;",
    "}",
    "",
    "static void *sl_map_get(sl_map *m, const void *k) {",
    "    unsigned long long h = m->kstr",
    "                              ? sl_hash_str(*(const char *const *)k)",
    "                              : sl_hash_bytes((const unsigned char *)k,",
    "                                              m->ksz);",
    "    long long s = sl_map_probe(m, k, h);",
    "    if (s < 0)",
    "        return NULL;",
    "    return m->vals + (size_t)s * m->vsz;",
    "}",
    "",
    "static int sl_map_has(sl_map *m, const void *k) {",
    "    return sl_map_get(m, k) != NULL;",
    "}",
    "",
    "static void sl_map_del(sl_map *m, const void *k) {",
    "    unsigned long long h = m->kstr",
    "                              ? sl_hash_str(*(const char *const *)k)",
    "                              : sl_hash_bytes((const unsigned char *)k,",
    "                                              m->ksz);",
    "    long long s = sl_map_probe(m, k, h);",
    "    if (s < 0)",
    "        return;",
    "    m->state[s] = 0;",
    "    for (long long i = 0; i < m->count; i++) {",
    "        if (m->order[i] == s) {",
    "            memmove(m->order + i, m->order + i + 1,",
    "                    (size_t)(m->count - i - 1) * sizeof(long long));",
    "            break;",
    "        }",
    "    }",
    "    m->count--;",
    "}",
    "",
    "/* ---- strings ---- */",
    "",
    "static char *sl_strdup(const char *s) {",
    "    size_t n = strlen(s) + 1;",
    "    char *p = (char *)sl_gc_alloc(n, NULL);",
    "    memcpy(p, s, n);",
    "    return p;",
    "}",
    "",
    "static char *sl_str_concat(const char *a, const char *b) {",
    "    size_t la = strlen(a), lb = strlen(b);",
    "    char *p = (char *)sl_gc_alloc(la + lb + 1, NULL);",
    "    memcpy(p, a, la);",
    "    memcpy(p + la, b, lb);",
    "    p[la + lb] = 0;",
    "    return p;",
    "}",
    "",
    "static char *sl_str_from_int(long long v) {",
    "    char buf[32];",
    "    snprintf(buf, sizeof(buf), \"%lld\", v);",
    "    return sl_strdup(buf);",
    "}",
    "",
    "static char *sl_str_from_uint(unsigned long long v) {",
    "    char buf[32];",
    "    snprintf(buf, sizeof(buf), \"%llu\", v);",
    "    return sl_strdup(buf);",
    "}",
    "",
    "static char *sl_str_from_float(double v) {",
    "    char buf[64];",
    "    snprintf(buf, sizeof(buf), \"%g\", v);",
    "    return sl_strdup(buf);",
    "}",
    "",
    "static char *sl_str_from_bool(bool v) {",
    "    return sl_strdup(v ? \"true\" : \"false\");",
    "}",
    "",
    "/* ---- user program ---- */",
    "",
};

const int RUNTIME_CONTAINERS_LEN =
    sizeof(RUNTIME_CONTAINERS) / sizeof(RUNTIME_CONTAINERS[0]);
