/* Split out of the original monolithic codegen.c -- see
 * internal.h for the shared CG state and cross-file API. */

#include "internal.h"


/* ------------------------------------------------------------------ */
/* Program-level generation                                            */
/* ------------------------------------------------------------------ */

/* The runtime embedded into every generated program. Kept as plain C
 * source lines so it reads exactly like hand-written code. Split into
 * two arrays: this one (prelude through sl_rt_error) is emitted first;
 * RUNTIME_CONTAINERS (chan/bytes/arr/map/strings, defined below) is
 * emitted after RUNTIME_GC (runtime_gc.c) since those containers now
 * allocate through sl_gc_alloc, which RUNTIME_GC defines. */
const char *RUNTIME[] = {
    "#include <stdio.h>",
    "#include <stdlib.h>",
    "#include <string.h>",
    "#include <stdbool.h>",
    "#include <stdint.h>",
    "#include <stdatomic.h>",
    "#include <pthread.h>",
    "#include <signal.h>",
    "#include <unistd.h>",
    "#include <time.h>", /* Tier 11 seventh slice: sl_rt_monotonic_ns needs it */
    "",
    "/* ---- slang runtime ---- */",
    "",
    "/* number of 'spawn'ed tasks currently running -- incremented right",
    " * before pthread_create, decremented once the task's function",
    " * returns OR (via sl_rt_error below) panics; proc.active_tasks()",
    " * reads this so a shutting-down program can wait out in-flight",
    " * work instead of dropping it. Maintained unconditionally whenever",
    " * 'spawn' is used, whether or not the program imports 'proc'. */",
    "static atomic_llong sl_rt_active_spawns = 0;",
    "",
    "static void sl_rt_active_spawns_inc(void) {",
    "    atomic_fetch_add(&sl_rt_active_spawns, 1);",
    "}",
    "",
    "static void sl_rt_active_spawns_dec(void) {",
    "    atomic_fetch_sub(&sl_rt_active_spawns, 1);",
    "}",
    "",
    "/* Tier 11 sixth slice: set by the dedicated signal thread",
    " * (pkg_proc/runtime.c, only exists if 'proc' is imported) once a",
    " * real SIGTERM/SIGINT arrives via sigwait(); read by",
    " * proc.shutdown_requested() and by the reactor's own park loop",
    " * (pkg_net/runtime_net.c) to abort accept/recv/dial waits. Defined",
    " * here, unconditionally, rather than in pkg_proc/runtime.c where it",
    " * conceptually belongs, for the same ordering reason as everything",
    " * else in this array: pkg_net's own runtime is emitted BEFORE",
    " * pkg_proc's (see emit_native_runtime, program.c), so a program",
    " * importing 'net' without 'proc' still needs this symbol to exist",
    " * at NET_RUNTIME's own emission point -- it simply never becomes 1",
    " * in that case, since only the signal thread ever sets it, and that",
    " * thread only exists when 'proc' is imported. A real _Atomic int,",
    " * not the old volatile sig_atomic_t: that type was only required",
    " * because the flag used to be touched from inside an actual",
    " * async-signal-handler context (sigaction-based); sigwait()-based",
    " * delivery runs as ordinary code in a normal thread, so no",
    " * async-signal-safety constraint applies here anymore. */",
    "static _Atomic int sl_rt_shutdown_flag = 0;",
    "",
    "/* Tier 11 sixth slice: a single, always-defined hook the signal",
    " * thread calls unconditionally (checking for NULL) on shutdown, so",
    " * it can nudge whichever parking primitives need an early wake --",
    " * today only the reactor (pkg_net/runtime_net.c, which sets this to",
    " * its own nudge function in sl_reactor_start if 'net' is imported).",
    " * A program can import 'proc' without 'net' at all, in which case",
    " * pkg_net's own symbols are never emitted -- the signal thread",
    " * cannot reference them directly without a compile error in that",
    " * case, hence this indirection instead of a direct call. */",
    "static void (*sl_rt_shutdown_hook)(void) = NULL;",
    "",
    "/* Tier 10: a lexically-scoped chain of GC root lists, one per",
    " * currently in-flight call-site safepoint on this thread (the",
    " * same 'handle stack' shape OCaml's C FFI CAMLparam/CAMLlocal",
    " * uses). Walked by the collector (runtime_gc.c) via each",
    " * registered thread's own copy of this pointer. _Thread_local, so",
    " * every OS thread (main, the worker pool) gets its own independent,",
    " * correctly zero-initialized chain for free. */",
    "typedef struct sl_safepoint {",
    "    struct sl_safepoint *prev;",
    "    void **roots;",
    "    int nroots;",
    "} sl_safepoint;",
    "",
    "/* Tier 11 first slice: the struct that will eventually be a real",
    " * scheduled task (src/codegen/runtime_sched.c has the rest of that",
    " * machinery -- context switch, growable stack, grow-and-relocate).",
    " * Defined here rather than there because sl_rt_safepoint_enter/exit",
    " * just below need sl_task's COMPLETE type at their own definition",
    " * site (they dereference ->safepoint_top), and runtime_sched.c is",
    " * emitted much later (after RUNTIME_GC and RUNTIME_CONTAINERS) --",
    " * a plain ordering requirement, not a change of ownership. For this",
    " * slice every OS thread (main, each spawned pthread) still gets",
    " * exactly one sl_task, created and torn down with the thread itself",
    " * (see sl_gc_register_thread, runtime_gc.c) -- no scheduler, no",
    " * second task, nothing behaviorally different from before. */",
    "typedef struct sl_task {",
    "    void *stack_base;   /* 16-byte-aligned usable base -- may NOT be",
    "                           what malloc() actually returned; see",
    "                           raw_base below */",
    "    void *raw_base;     /* the actual malloc() return value for the",
    "                           current stack_base -- free() THIS, never",
    "                           stack_base directly. malloc() isn't",
    "                           guaranteed by the C standard to already",
    "                           return 16-aligned memory (it happens to,",
    "                           on this machine's allocator, which is",
    "                           exactly why freeing stack_base looked fine",
    "                           in testing without actually being",
    "                           correct) */",
    "    size_t stack_size;",
    "    void *rsp;",
    "    struct sl_safepoint *safepoint_top;",
    "    int grows_seen;",
    "    struct sl_task *next;    /* run-queue link, runtime_pool.c */",
    "    void *entry_arg;         /* the task's own entry-fn argument --",
    "                                rooted directly by the collector while",
    "                                queued (a not-yet-started task's",
    "                                safepoint chain is empty), and by the",
    "                                task's own chain once it starts",
    "                                running normally. See runtime_pool.c",
    "                                and sl_gc_collect's run-queue walk",
    "                                (runtime_gc.c) for both halves. */",
    "    int is_main;             /* Tier 11 fourth slice: task-scoped (not",
    "                                thread-scoped) replacement for the old",
    "                                sl_rt_is_main_thread -- set once, only",
    "                                for main()'s own top-level task. A",
    "                                _Thread_local flag was safe only as",
    "                                long as main's OS thread could never",
    "                                run any task but its own; once it can",
    "                                park (chan_send/recv) and its thread",
    "                                joins the worker pool afterward, that",
    "                                stopped being true -- sl_rt_error",
    "                                below reads this per-TASK instead. */",
    "    int parked;              /* set by sl_task_park (runtime_pool.c)",
    "                                right before switching out; read and",
    "                                cleared by sl_worker_after_switch",
    "                                right after switching back in. */",
    "    pthread_mutex_t *park_mu; /* the mutex sl_worker_after_switch must",
    "                                unlock, once, immediately after the",
    "                                switch is safely complete -- NULL if",
    "                                not currently parked. */",
    "    struct sl_task *parked_next; /* sl_parked_tasks linkage -- kept",
    "                                separate from `next` above, since a",
    "                                parked task is on BOTH a primitive-",
    "                                specific wait list (via `next`, e.g.",
    "                                a channel's own send/recv_waiters) AND",
    "                                this global GC registry (via this",
    "                                field) at the same time. */",
    "    long long sleep_deadline_ns; /* Tier 11 fifth slice: monotonic-ns",
    "                                absolute wake time -- meaningful only",
    "                                while this task is linked into",
    "                                sl_time_sleepers (pkg_time/runtime.c)",
    "                                via `next`, exactly like park_mu is",
    "                                meaningful only while parked. */",
    "    long long run_start_ns;  /* Tier 11 seventh slice (cooperative",
    "                                preemption): monotonic time this task's",
    "                                CURRENT stint on an OS thread began --",
    "                                set fresh by whoever switches INTO this",
    "                                task (sl_worker_run_loop's normal",
    "                                dispatch, and main's own one-off",
    "                                switch-in, program.c), covering a fresh",
    "                                submit, a resume-from-park, AND a",
    "                                resume-from-preemption-yield uniformly. */",
    "    unsigned long yield_check_counter; /* sampling counter for",
    "                                sl_rt_maybe_yield -- see there. Per-task,",
    "                                not per-thread, so it travels correctly",
    "                                with a task that migrates OS threads. */",
    "    int preempted;           /* set by sl_task_yield_now (runtime_pool.c)",
    "                                right before switching out; read and",
    "                                cleared by sl_worker_after_switch right",
    "                                after switching back in -- same shape as",
    "                                `parked` above, but mutually exclusive",
    "                                with it: sl_task_park and",
    "                                sl_task_yield_now are the only setters",
    "                                of either flag, and neither can be",
    "                                in flight while the other runs (both",
    "                                only ever execute as the one currently-",
    "                                running task's own code, on its own",
    "                                OS thread, one at a time). */",
    "} sl_task;",
    "",
    "/* Tier 11 second slice: the scheduler's own run queue. Defined here,",
    " * not in runtime_pool.c where the rest of the pool machinery lives,",
    " * for the same ordering reason as sl_task itself above --",
    " * sl_gc_collect's own run-queue walk (runtime_gc.c, rooting every",
    " * queued task's entry_arg) needs the complete type and the",
    " * sl_global_runq variable both visible at its own definition site,",
    " * well before RUNTIME_POOL is emitted. runtime_pool.c's own content",
    " * just uses these, it doesn't redefine them. */",
    "typedef struct sl_runq {",
    "    sl_task *head, *tail;",
    "    pthread_mutex_t mu;",
    "    pthread_cond_t not_empty;",
    "    int shutdown;",
    "} sl_runq;",
    "static sl_runq sl_global_runq = {",
    "    .mu = PTHREAD_MUTEX_INITIALIZER,",
    "    .not_empty = PTHREAD_COND_INITIALIZER,",
    "};",
    "",
    "/* Tier 11 seventh slice: a relaxed, heuristic-only count of tasks",
    " * currently sitting on sl_global_runq -- NOT used for any correctness",
    " * decision, only to answer 'is anyone else waiting for a worker right",
    " * now' from sl_rt_maybe_yield without taking q->mu on every checkpoint.",
    " * An unsynchronized peek at q->head itself would be a real, TSan-",
    " * flagged data race (concurrent unlocked read vs. locked writes); this",
    " * sidesteps that with a properly-synchronized atomic instead. Updated,",
    " * under q->mu (already held at both call sites), by sl_runq_push/",
    " * sl_runq_pop_blocking (runtime_pool.c) -- exhaustive: those two",
    " * functions are the only places a task ever enters or leaves this",
    " * queue (sl_runq_shutdown does not drain it). A stale read here is",
    " * harmless either way -- worst case, a spurious skipped or attempted",
    " * yield, never a correctness issue -- so relaxed ordering is",
    " * appropriate; nothing else is synchronized through this variable. */",
    "static _Atomic int sl_global_runq_count = 0;",
    "",
    "/* Tier 11 fourth slice: the global parked-task GC registry. A parked",
    " * task (chan_send/recv, this slice; net/time, later) is reachable",
    " * from neither a registered thread's task_slot (the worker that",
    " * parked it reassigns that back to its own idle sentinel) nor the",
    " * run queue (it's on some primitive's own wait list instead, e.g. a",
    " * channel's send/recv_waiters) -- without this, its roots are simply",
    " * never marked. Declared here, not in runtime_pool.c where the rest",
    " * of the park/resume machinery lives, for the same ordering reason",
    " * as sl_global_runq itself just above: sl_gc_collect needs the",
    " * complete picture at its own definition site, well before",
    " * RUNTIME_POOL is emitted. Guarded by sl_gc_mu. */",
    "static sl_task *sl_parked_tasks = NULL;",
    "",
    "/* sl_rt_current_task->safepoint_top is now the one live chain (it",
    " * replaces what used to be a bare _Thread_local sl_safepoint*",
    " * variable) -- sl_rt_task_storage is that thread's own sl_task,",
    " * zeroed and pointed to by sl_rt_current_task inside",
    " * sl_gc_register_thread() before any safepoint bracket can run.",
    " * Both are _Thread_local for exactly the reason the old variable",
    " * was: every OS thread (main, the worker pool, any spawn",
    " * trampoline) gets its own independent, correctly zero-initialized",
    " * copy for free. */",
    "static _Thread_local sl_task sl_rt_task_storage;",
    "static _Thread_local sl_task *sl_rt_current_task = NULL;",
    "",
    "/* Where main()/each worker (runtime_pool.c) saves its own",
    " * OS-provided-stack context before switching onto a task's buffer --",
    " * one shared slot per OS thread, since only ever one such switch-in",
    " * is in flight per thread at a time. Defined here (moved up from",
    " * runtime_sched.c, Tier 11 third slice) because sl_rt_error below",
    " * needs it at its own definition site, well before RUNTIME_SCHED is",
    " * emitted -- same ordering reason as sl_task itself above. */",
    "static _Thread_local void *sl_rt_native_rsp;",
    "",
    "static inline void sl_rt_gc_checkin(void); /* runtime_gc.c, forward here */",
    "static void sl_task_stack_grow(sl_task *t); /* runtime_sched.c, forward here */",
    "void sl_ctx_switch(void **old_rsp_slot, void *new_rsp); /* runtime_sched.c,",
    "    forward here for the same reason -- sl_rt_error below needs it at",
    "    its own definition site; defined for real, in assembly, still in",
    "    RUNTIME_SCHED. */",
    "static void sl_task_park(pthread_mutex_t *held_mu); /* runtime_pool.c,",
    "    forward here -- sl_chan_send/recv (RUNTIME_CONTAINERS, emitted",
    "    right after this file) call it directly, but it's defined for",
    "    real in RUNTIME_POOL, emitted last. */",
    "static void sl_task_resume(sl_task *t); /* runtime_pool.c, forward here,",
    "    same reason. */",
    "static void sl_task_yield_now(void); /* runtime_pool.c, forward here --",
    "    Tier 11 seventh slice (cooperative preemption): sl_rt_maybe_yield",
    "    below calls it directly, but it's defined for real in RUNTIME_POOL,",
    "    same reason as sl_task_park/sl_task_resume just above. */",
    "",
    "/* Empirically validated in the standalone spike (not a guess): 2048",
    " * produced a real, intermittent (~10-15% of runs) stack overflow;",
    " * 8192 was robust across 150+ runs. Defined here (not next to",
    " * sl_task_stack_grow's own definition in runtime_sched.c) because",
    " * sl_rt_safepoint_enter needs it at its own definition site, same",
    " * ordering reason as sl_task itself above. */",
    "#define SL_TASK_GUARD_MARGIN 8192",
    "",
    "/* Tier 11 seventh slice (cooperative preemption v1): tunable, not yet",
    " * empirically tuned beyond a reasonable starting guess (matching Go's",
    " * own ~10ms pre-1.14 preemption granularity, halved for a smaller,",
    " * more latency-sensitive pool). SL_PREEMPT_SAMPLE_MASK bounds the",
    " * steady-state cost of a hot loop's checkpoint to one increment plus",
    " * one branch for 1023 of every 1024 visits -- only the 1-in-1024",
    " * sample pays for a clock_gettime call. */",
    "#define SL_PREEMPT_QUANTUM_NS 5000000LL",
    "#define SL_PREEMPT_SAMPLE_MASK 1023UL",
    "",
    "/* Not gated on 'time' being imported -- spawn/loops are core language",
    " * features, so this must exist unconditionally. Mirrors pkg_time's own",
    " * sl_time_mono exactly; duplicated rather than shared cross-package for",
    " * the same reason sl_rt_shutdown_hook exists as an indirection instead",
    " * of a direct call -- a program can use spawn/loops without importing",
    " * time at all. */",
    "static inline long long sl_rt_monotonic_ns(void) {",
    "    struct timespec ts;",
    "    clock_gettime(CLOCK_MONOTONIC, &ts);",
    "    return (long long)ts.tv_sec * 1000000000LL + ts.tv_nsec;",
    "}",
    "",
    "/* Tier 11 seventh slice (cooperative preemption v1): the one shared",
    " * checkpoint every safepoint of any kind now funnels through -- a",
    " * call-site or back-edge bracket that has at least one live GC root",
    " * (via sl_rt_safepoint_enter below, in the SAME relative position its",
    " * guard-margin-check-then-checkin tail always occupied), AND a loop",
    " * back-edge with NO live GC roots, which never opens a bracket at all",
    " * (stmt.c's emit_backedge_enter calls this directly, unconditionally,",
    " * for ST_WHILE/ST_FOR specifically -- see that file's own comment for",
    " * why ST_FOR_IN is deliberately excluded from that direct call).",
    " * Ordering within this function is load-bearing exactly the way it",
    " * was before extraction: the guard-margin probe must run after sp is",
    " * already linked into the chain (when called from safepoint_enter --",
    " * see the comment there), and sl_rt_gc_checkin() must run after the",
    " * guard-margin probe, so a collection never lands mid-grow. The new",
    " * preemption sample-check runs last, after both -- a task must never",
    " * be mid-grow or mid-collection-checkin when it decides to yield. */",
    "static inline void sl_rt_maybe_yield(void) {",
    "    sl_task *t = sl_rt_current_task;",
    "    {",
    "        char sl_rt_stack_probe;",
    "        if ((uintptr_t)&sl_rt_stack_probe - (uintptr_t)t->stack_base <",
    "            SL_TASK_GUARD_MARGIN)",
    "            sl_task_stack_grow(t);",
    "    }",
    "    sl_rt_gc_checkin();",
    "    /* Sampled, not checked every visit: bounds the steady-state cost",
    "     * of a hot loop's checkpoint to one increment + one branch for",
    "     * 1023 of every 1024 visits -- see SL_PREEMPT_SAMPLE_MASK's own",
    "     * comment. yield_check_counter lives on the TASK, not the thread,",
    "     * so it travels correctly if this task migrates OS threads. */",
    "    if ((++t->yield_check_counter & SL_PREEMPT_SAMPLE_MASK) != 0)",
    "        return;",
    "    long long now = sl_rt_monotonic_ns();",
    "    if (now - t->run_start_ns < SL_PREEMPT_QUANTUM_NS)",
    "        return;",
    "    if (atomic_load_explicit(&sl_global_runq_count, memory_order_relaxed) == 0)",
    "        return; /* no one waiting for a worker -- yielding here is pure",
    "                    overhead with no fairness benefit */",
    "    sl_task_yield_now();",
    "}",
    "",
    "/* sl_rt_gc_checkin() (now reached via sl_rt_maybe_yield) runs *after*",
    " * this frame is linked into the chain, not before: every call-site",
    " * bracket builds its complete roots array -- already-evaluated temps",
    " * included -- before this function is even called, so a collection",
    " * that ran before sp were linked in would not yet find those temps",
    " * reachable through anything. Checking in only once sp is live closes",
    " * that gap; the cost is that a collection can run one bracket-entry",
    " * later than a naive 'checkin first' placement would, which is",
    " * harmless (nothing before this point could have allocated on top of",
    " * an unrooted value -- that's the entire point of building the array",
    " * first). sp/roots are raw addresses into the caller's own (soon-to-",
    " * be-relocated-if-we-grow) stack frame, received as plain pointer",
    " * PARAMETERS -- once linked into the chain via the assignments below,",
    " * sl_task_stack_grow's own chain walk (inside sl_rt_maybe_yield) reads",
    " * and fixes them up correctly (same mechanism as the collector's own",
    " * root scan); the sp/roots C parameters themselves must never be",
    " * dereferenced again after a grow, and nothing below does -- only",
    " * sl_rt_current_task->safepoint_top (itself correctly translated) is",
    " * read from here on. wrap_safepoint (core.c) never writes back",
    " * through &_sl_spN/_sl_spN_roots after this call either, confirmed",
    " * directly before wiring this in. */",
    "static inline void sl_rt_safepoint_enter(sl_safepoint *sp, void **roots,",
    "                                         int nroots) {",
    "    sp->roots = roots;",
    "    sp->nroots = nroots;",
    "    sp->prev = sl_rt_current_task->safepoint_top;",
    "    sl_rt_current_task->safepoint_top = sp;",
    "    sl_rt_maybe_yield();",
    "}",
    "",
    "static inline void sl_rt_safepoint_exit(void) {",
    "    sl_rt_current_task->safepoint_top = sl_rt_current_task->safepoint_top->prev;",
    "}",
    "",
    "/* Tier 11 third slice: a panicking spawned task no longer ends its",
    " * OS thread (pthread_exit) -- under the worker pool, that thread is",
    " * meant to keep running future queued tasks. Instead the panic path",
    " * abandons this task exactly the way a normal completion already",
    " * does: switch back to whatever sl_rt_native_rsp holds (the worker",
    " * loop, runtime_pool.c), same argument order as every other",
    " * 'switch out of the current task' call already in the codebase",
    " * (%s_entry's own normal-completion switch, sl_task_stack_grow's",
    " * switch back into a relocated task). Safe from a call-stack-",
    " * unwinding standpoint for the same reason pthread_exit already",
    " * was: no runtime-internal lock is ever held across a point where a",
    " * user-triggered panic can fire -- abandoning the intervening C",
    " * frames without running any cleanup for them is exactly what",
    " * already happened before, just via a different mechanism. */",
    "static void sl_rt_error(const char *msg, long long a, long long b) {",
    "    if (!sl_rt_current_task->is_main) {",
    "        fprintf(stderr,",
    "                \"slang: task panicked: %s (index %lld, length %lld)\\n\",",
    "                msg, a, b);",
    "        sl_rt_active_spawns_dec();",
    "        sl_ctx_switch(&sl_rt_current_task->rsp, sl_rt_native_rsp);",
    "        fprintf(stderr,",
    "                \"slang: internal error: task resumed after panic \"",
    "                \"switch-back\\n\");",
    "        abort(); /* genuinely unreachable -- a can't-happen guard, not",
    "                    routed back through this same panic machinery */",
    "    }",
    "    fprintf(stderr, \"slang runtime error: %s (index %lld, length %lld)\\n\",",
    "            msg, a, b);",
    "    exit(1);",
    "}",
    "",
};

const int RUNTIME_LEN = sizeof(RUNTIME) / sizeof(RUNTIME[0]);

/* chan[T]/bytes/[T]/map[K]V/strings: the four fixed heap-object shapes
 * plus string helpers. Emitted after RUNTIME_GC (runtime_gc.c), which
 * this array depends on for sl_gc_alloc/sl_gc_realloc/sl_gc_mark, and
 * after which every codegen-generated struct/opt/result/spawn-shape
 * tracer follows (program.c's emission order). Every allocation here
 * either has no inner pointers (traced as NULL) or is one of these four
 * containers, each carrying its own element/key/value "is this slot a
 * GC pointer" flag(s) set at construction and consulted by its own
 * trace function -- see the design plan for why arrays/maps/chans never
 * need per-element-type-specialized tracers: every GC-tracked slang
 * type is represented as exactly one C pointer, so an element slot is
 * always either "one pointer to mark" or "no pointer," a single bool
 * per container instance. */
const char *RUNTIME_CONTAINERS[] = {
    "/* ---- chan[T]: bounded, thread-safe queue for 'spawn'ed tasks ---- */",
    "",
    "typedef struct {",
    "    unsigned char *buf;",
    "    size_t elemsz;",
    "    int cap, head, count, closed;",
    "    int elem_is_ptr;",
    "    pthread_mutex_t mu;",
    "    sl_task *send_waiters, *send_waiters_tail; /* Tier 11 fourth slice:",
    "        tasks parked waiting for buffer space, oldest first -- replaces",
    "        the old not_full condvar. A plain singly-linked list via",
    "        sl_task.next (push-to-tail/pop-from-head): a task is never on",
    "        a channel's wait list and the run queue at the same time, so",
    "        reusing that field is safe. */",
    "    sl_task *recv_waiters, *recv_waiters_tail; /* same, for tasks",
    "        parked waiting for data -- replaces the old not_empty condvar */",
    "} sl_chan;",
    "",
    "static void sl_gc_trace_chan(void *p, void (*mark)(void *)) {",
    "    sl_chan *c = (sl_chan *)p;",
    "    if (!c->buf) return;",
    "    mark(c->buf);",
    "    if (!c->elem_is_ptr) return;",
    "    for (int i = 0; i < c->cap; i++)",
    "        mark(*(void **)(c->buf + (size_t)i * c->elemsz));",
    "}",
    "",
    "static sl_chan *sl_chan_new(size_t elemsz, int cap, int elem_is_ptr) {",
    "    if (cap < 1) cap = 1;",
    "    sl_chan *c = (sl_chan *)sl_gc_alloc(sizeof(sl_chan), sl_gc_trace_chan);",
    "    c->buf = (unsigned char *)sl_gc_alloc(elemsz * (size_t)cap, NULL);",
    "    c->elemsz = elemsz;",
    "    c->cap = cap;",
    "    c->head = 0;",
    "    c->count = 0;",
    "    c->closed = 0;",
    "    c->elem_is_ptr = elem_is_ptr;",
    "    pthread_mutex_init(&c->mu, NULL);",
    "    return c;",
    "}",
    "",
    "static void sl_chan_wl_push(sl_task **head, sl_task **tail, sl_task *t) {",
    "    t->next = NULL;",
    "    if (*tail) (*tail)->next = t; else *head = t;",
    "    *tail = t;",
    "}",
    "static sl_task *sl_chan_wl_pop(sl_task **head, sl_task **tail) {",
    "    sl_task *t = *head;",
    "    if (t) { *head = t->next; if (!*head) *tail = NULL; }",
    "    return t;",
    "}",
    "",
    "/* Tier 11 fourth slice: chan_send/chan_recv now PARK a blocked task",
    " * (sl_task_park/sl_task_resume, runtime_pool.c) instead of blocking",
    " * the OS thread on a condvar -- the worker that was running the",
    " * blocked task goes back to servicing the run queue instead of",
    " * sitting idle. A woken waiter re-locks c->mu and re-checks the loop",
    " * condition itself, exactly like the old condvar-signal-then-",
    " * recheck did -- it is never handed a value directly, just told a",
    " * value (or a close) MIGHT now be available. No GC-checkin",
    " * bookkeeping is needed in this loop anymore either: a parked task",
    " * holds no OS thread hostage at all (unlike the old blocked-condvar",
    " * model), so it can never make the collector's quiescence wait wait",
    " * on it -- sl_task_park itself does not call sl_rt_gc_checkin(); the",
    " * very next checkin the now-freed OS thread reaches is",
    " * sl_worker_run_loop's own, immediately after re-entering its loop.",
    " * See the Tier 11 plan for the full design and the two critical bugs",
    " * (a lost-wakeup race, and main()'s own top-level task having no",
    " * dispatch loop to resume into) a dedicated review pass found before",
    " * any of this was implemented. */",
    "static void sl_chan_send(sl_chan *c, const void *val) {",
    "    pthread_mutex_lock(&c->mu);",
    "    while (c->count == c->cap && !c->closed) {",
    "        sl_chan_wl_push(&c->send_waiters, &c->send_waiters_tail, sl_rt_current_task);",
    "        sl_task_park(&c->mu); /* leaves c->mu locked across the switch --",
    "            see sl_task_park's own comment (runtime_pool.c) for why */",
    "        pthread_mutex_lock(&c->mu); /* re-acquire before re-checking */",
    "    }",
    "    if (c->closed) {",
    "        pthread_mutex_unlock(&c->mu);",
    "        sl_rt_error(\"send on closed channel\", 0, 0);",
    "        return;",
    "    }",
    "    int tail = (c->head + c->count) % c->cap;",
    "    memcpy(c->buf + (size_t)tail * c->elemsz, val, c->elemsz);",
    "    c->count++;",
    "    if (c->recv_waiters) {",
    "        sl_task *w = sl_chan_wl_pop(&c->recv_waiters, &c->recv_waiters_tail);",
    "        sl_task_resume(w);",
    "    }",
    "    pthread_mutex_unlock(&c->mu);",
    "}",
    "",
    "/* returns 1 with *out populated, or 0 if closed and drained empty */",
    "static int sl_chan_recv(sl_chan *c, void *out) {",
    "    pthread_mutex_lock(&c->mu);",
    "    while (c->count == 0 && !c->closed) {",
    "        sl_chan_wl_push(&c->recv_waiters, &c->recv_waiters_tail, sl_rt_current_task);",
    "        sl_task_park(&c->mu);",
    "        pthread_mutex_lock(&c->mu);",
    "    }",
    "    if (c->count == 0) {",
    "        pthread_mutex_unlock(&c->mu);",
    "        return 0;",
    "    }",
    "    memcpy(out, c->buf + (size_t)c->head * c->elemsz, c->elemsz);",
    "    c->head = (c->head + 1) % c->cap;",
    "    c->count--;",
    "    if (c->send_waiters) {",
    "        sl_task *w = sl_chan_wl_pop(&c->send_waiters, &c->send_waiters_tail);",
    "        sl_task_resume(w);",
    "    }",
    "    pthread_mutex_unlock(&c->mu);",
    "    return 1;",
    "}",
    "",
    "static void sl_chan_close(sl_chan *c) {",
    "    pthread_mutex_lock(&c->mu);",
    "    c->closed = 1;",
    "    sl_task *w;",
    "    while ((w = sl_chan_wl_pop(&c->recv_waiters, &c->recv_waiters_tail)))",
    "        sl_task_resume(w);",
    "    while ((w = sl_chan_wl_pop(&c->send_waiters, &c->send_waiters_tail)))",
    "        sl_task_resume(w);",
    "    pthread_mutex_unlock(&c->mu);",
    "}",
    "",
    "/* ---- bytes: length-prefixed, binary-safe sequences ---- */",
    "",
    "typedef struct { long long len; unsigned char *ptr; } sl_bytes;",
    "",
    "static void sl_gc_trace_bytes(void *p, void (*mark)(void *)) {",
    "    mark(((sl_bytes *)p)->ptr);",
    "}",
    "",
    "static sl_bytes *sl_bytes_new(const unsigned char *p, long long n) {",
    "    sl_bytes *b = (sl_bytes *)sl_gc_alloc(sizeof(sl_bytes), sl_gc_trace_bytes);",
    "    b->len = n;",
    "    b->ptr = (unsigned char *)sl_gc_alloc((size_t)(n > 0 ? n : 1), NULL);",
    "    if (n > 0) memcpy(b->ptr, p, (size_t)n);",
    "    return b;",
    "}",
    "",
    "static int sl_bytes_at(sl_bytes *b, long long i) {",
    "    if (i < 0 || i >= b->len)",
    "        sl_rt_error(\"byte index out of bounds\", i, b->len);",
    "    return (int)b->ptr[i];",
    "}",
    "",
    "static void sl_bytes_set(sl_bytes *b, long long i, unsigned char v) {",
    "    if (i < 0 || i >= b->len)",
    "        sl_rt_error(\"byte index out of bounds\", i, b->len);",
    "    b->ptr[i] = v;",
    "}",
    "",
    "static sl_bytes *sl_bytes_concat(sl_bytes *a, sl_bytes *b) {",
    "    sl_bytes *r = (sl_bytes *)sl_gc_alloc(sizeof(sl_bytes), sl_gc_trace_bytes);",
    "    r->len = a->len + b->len;",
    "    r->ptr = (unsigned char *)sl_gc_alloc((size_t)(r->len > 0 ? r->len : 1), NULL);",
    "    if (a->len) memcpy(r->ptr, a->ptr, (size_t)a->len);",
    "    if (b->len) memcpy(r->ptr + a->len, b->ptr, (size_t)b->len);",
    "    return r;",
    "}",
    "",
    "static sl_bytes *sl_bytes_slice(sl_bytes *b, long long s, long long e) {",
    "    if (s < 0) s = 0;",
    "    if (e > b->len) e = b->len;",
    "    if (e < s) e = s;",
    "    sl_bytes *r = (sl_bytes *)sl_gc_alloc(sizeof(sl_bytes), sl_gc_trace_bytes);",
    "    r->len = e - s;",
    "    r->ptr = (unsigned char *)sl_gc_alloc((size_t)(r->len > 0 ? r->len : 1), NULL);",
    "    if (r->len) memcpy(r->ptr, b->ptr + s, (size_t)r->len);",
    "    return r;",
    "}",
    "",
    "static int sl_bytes_eq(sl_bytes *a, sl_bytes *b) {",
    "    if (a->len != b->len) return 0;",
    "    return a->len == 0 || memcmp(a->ptr, b->ptr, (size_t)a->len) == 0;",
    "}",
    "",
    "static char *sl_str_from_bytes(sl_bytes *b) {",
    "    char *p = (char *)sl_gc_alloc((size_t)b->len + 1, NULL);",
    "    if (b->len) memcpy(p, b->ptr, (size_t)b->len);",
    "    p[b->len] = 0;",
    "    return p;",
    "}",
    "",
    "static sl_bytes *sl_bytes_from_str(const char *s) {",
    "    return sl_bytes_new((const unsigned char *)s, (long long)strlen(s));",
    "}",
    "",
    "static sl_bytes *sl_to_le(unsigned long long v) {",
    "    unsigned char buf[8];",
    "    for (int i = 0; i < 8; i++)",
    "        buf[i] = (unsigned char)((v >> (8 * i)) & 0xff);",
    "    return sl_bytes_new(buf, 8);",
    "}",
    "",
    "static sl_bytes *sl_to_be(unsigned long long v) {",
    "    unsigned char buf[8];",
    "    for (int i = 0; i < 8; i++)",
    "        buf[7 - i] = (unsigned char)((v >> (8 * i)) & 0xff);",
    "    return sl_bytes_new(buf, 8);",
    "}",
    "",
    "static unsigned long long sl_from_le(sl_bytes *b) {",
    "    if (b->len != 8)",
    "        sl_rt_error(\"from_le expects exactly 8 bytes\", b->len, 8);",
    "    unsigned long long v = 0;",
    "    for (int i = 7; i >= 0; i--) v = (v << 8) | b->ptr[i];",
    "    return v;",
    "}",
    "",
    "static unsigned long long sl_from_be(sl_bytes *b) {",
    "    if (b->len != 8)",
    "        sl_rt_error(\"from_be expects exactly 8 bytes\", b->len, 8);",
    "    unsigned long long v = 0;",
    "    for (int i = 0; i < 8; i++) v = (v << 8) | b->ptr[i];",
    "    return v;",
    "}",
    "",
    "/* ---- growable arrays over GC memory ---- */",
    "",
    "typedef struct {",
    "    long long len, cap;",
    "    unsigned char *data; /* elements stored inline */",
    "    size_t esz;          /* element size in bytes */",
    "    int elem_is_ptr;",
    "} sl_arr;",
    "",
    "static void sl_gc_trace_arr(void *p, void (*mark)(void *)) {",
    "    sl_arr *a = (sl_arr *)p;",
    "    if (!a->data) return;",
    "    mark(a->data);",
    "    if (!a->elem_is_ptr) return;",
    "    for (long long i = 0; i < a->len; i++)",
    "        mark(*(void **)(a->data + (size_t)i * a->esz));",
    "}",
    "",
    "static sl_arr *sl_arr_new(size_t esz, int elem_is_ptr) {",
    "    sl_arr *a = (sl_arr *)sl_gc_alloc(sizeof(sl_arr), sl_gc_trace_arr);",
    "    a->len = 0;",
    "    a->cap = 0;",
    "    a->data = NULL;",
    "    a->esz = esz;",
    "    a->elem_is_ptr = elem_is_ptr;",
    "    return a;",
    "}",
    "",
    "static void sl_arr_reserve(sl_arr *a, long long need) {",
    "    if (need <= a->cap) return;",
    "    long long cap = a->cap ? a->cap : 8;",
    "    while (cap < need) cap *= 2;",
    "    a->data = (unsigned char *)sl_gc_realloc(a->data, (size_t)cap * a->esz);",
    "    a->cap = cap;",
    "}",
    "",
    "static void *sl_arr_get(sl_arr *a, long long i, size_t esz) {",
    "    if (esz != a->esz)",
    "        sl_rt_error(\"internal: element size mismatch\", (long long)esz,",
    "                    (long long)a->esz);",
    "    if (i < 0 || i >= a->len)",
    "        sl_rt_error(\"list index out of bounds\", i, a->len);",
    "    return a->data + (size_t)i * esz;",
    "}",
    "",
    "static void sl_arr_push(sl_arr *a, void *val, size_t esz) {",
    "    if (esz != a->esz)",
    "        sl_rt_error(\"internal: element size mismatch\", (long long)esz,",
    "                    (long long)a->esz);",
    "    sl_arr_reserve(a, a->len + 1);",
    "    memcpy(a->data + (size_t)a->len * esz, val, esz);",
    "    a->len++;",
    "}",
    "",
    "static void *sl_arr_pop(sl_arr *a, size_t esz) {",
    "    if (esz != a->esz)",
    "        sl_rt_error(\"internal: element size mismatch\", (long long)esz,",
    "                    (long long)a->esz);",
    "    if (a->len == 0) sl_rt_error(\"pop from empty list\", 0, 0);",
    "    a->len--;",
    "    return a->data + (size_t)a->len * esz;",
    "}",
    "",
    "static sl_arr *sl_arr_from(void *buf, long long n, size_t esz, int elem_is_ptr) {",
    "    sl_arr *a = sl_arr_new(esz, elem_is_ptr);",
    "    sl_arr_reserve(a, n);",
    "    if (n > 0) memcpy(a->data, buf, (size_t)n * esz);",
    "    a->len = n;",
    "    return a;",
    "}",
    "",
    "static sl_arr *sl_arr_slice(sl_arr *a, long long s, long long e) {",
    "    if (s < 0) s = 0;",
    "    if (e > a->len) e = a->len;",
    "    if (e < s) e = s;",
    "    sl_arr *r = sl_arr_new(a->esz, a->elem_is_ptr);",
    "    sl_arr_reserve(r, e - s);",
    "    if (e > s)",
    "        memcpy(r->data, a->data + (size_t)s * a->esz,",
    "               (size_t)(e - s) * a->esz);",
    "    r->len = e - s;",
    "    return r;",
    "}",
    "",
    "static sl_arr *sl_arr_concat(sl_arr *a, sl_arr *b) {",
    "    if (a->esz != b->esz)",
    "        sl_rt_error(\"cannot concatenate lists of different element types\",",
    "                    (long long)a->esz, (long long)b->esz);",
    "    sl_arr *r = sl_arr_new(a->esz, a->elem_is_ptr);",
    "    sl_arr_reserve(r, a->len + b->len);",
    "    if (a->len) memcpy(r->data, a->data, (size_t)a->len * a->esz);",
    "    if (b->len)",
    "        memcpy(r->data + (size_t)a->len * a->esz, b->data,",
    "               (size_t)b->len * b->esz);",
    "    r->len = a->len + b->len;",
    "    return r;",
    "}",
    "",
    "/* ---- maps: open-addressing hash tables over GC memory ---- */",
    "",
    "typedef struct {",
    "    long long count, cap;",
    "    size_t ksz, vsz;",
    "    int kstr;            /* keys are NUL-terminated strings */",
    "    int key_is_ptr, val_is_ptr;",
    "    unsigned char *keys; /* cap slots */",
    "    unsigned char *vals; /* cap slots */",
    "    unsigned char *state;/* 1 = occupied */",
    "    long long *order;    /* occupied slot indices, insertion order */",
    "} sl_map;",
    "",
    "static void sl_gc_trace_map(void *p, void (*mark)(void *)) {",
    "    sl_map *m = (sl_map *)p;",
    "    if (m->keys) mark(m->keys);",
    "    if (m->vals) mark(m->vals);",
    "    if (m->state) mark(m->state);",
    "    if (m->order) mark(m->order);",
    "    if (!m->key_is_ptr && !m->val_is_ptr) return;",
    "    for (long long i = 0; i < m->count; i++) {",
    "        long long slot = m->order[i];",
    "        if (m->key_is_ptr)",
    "            mark(*(void **)(m->keys + (size_t)slot * m->ksz));",
    "        if (m->val_is_ptr)",
    "            mark(*(void **)(m->vals + (size_t)slot * m->vsz));",
    "    }",
    "}",
    "",
    "static unsigned long long sl_hash_bytes(const unsigned char *p, size_t n) {",
    "    unsigned long long h = 1469598103934665603ULL;",
    "    for (size_t i = 0; i < n; i++) { h ^= p[i]; h *= 1099511628211ULL; }",
    "    return h;",
    "}",
    "",
    "static unsigned long long sl_hash_str(const char *s) {",
    "    unsigned long long h = 1469598103934665603ULL;",
    "    for (; *s; s++) { h ^= (unsigned char)*s; h *= 1099511628211ULL; }",
    "    return h;",
    "}",
    "",
    "static sl_map *sl_map_new(size_t ksz, size_t vsz, int kstr,",
    "                           int key_is_ptr, int val_is_ptr) {",
    "    sl_map *m = (sl_map *)sl_gc_alloc(sizeof(sl_map), sl_gc_trace_map);",
    "    m->count = 0;",
    "    m->cap = 8;",
    "    m->ksz = ksz;",
    "    m->vsz = vsz;",
    "    m->kstr = kstr;",
    "    m->key_is_ptr = key_is_ptr;",
    "    m->val_is_ptr = val_is_ptr;",
    "    m->keys = (unsigned char *)sl_gc_alloc(8 * ksz, NULL);",
    "    m->vals = (unsigned char *)sl_gc_alloc(8 * vsz, NULL);",
    "    m->state = (unsigned char *)sl_gc_alloc(8, NULL);",
    "    m->order = (long long *)sl_gc_alloc(8 * sizeof(long long), NULL);",
    "    return m;",
    "}",
    "",
    "/* Probe for a key: returns its slot if present, or -(slot)-1 for",
    " * the first empty slot where it could be inserted. */",
    "static long long sl_map_probe(sl_map *m, const void *k,",
    "                              unsigned long long h) {",
    "    long long mask = m->cap - 1;",
    "    long long i = (long long)(h & (unsigned long long)mask);",
    "    for (;;) {",
    "        if (!m->state[i])",
    "            return -i - 1;",
    "        void *kk = m->keys + (size_t)i * m->ksz;",
    "        int eq = m->kstr",
    "                    ? !strcmp(*(const char **)kk, *(const char *const *)k)",
    "                    : memcmp(kk, k, m->ksz) == 0;",
    "        if (eq)",
    "            return i;",
    "        i = (i + 1) & mask;",
    "    }",
    "}",
    "",
    "static void sl_map_grow(sl_map *m) {",
    "    long long old_cap = m->cap;",
    "    unsigned char *ok = m->keys, *ov = m->vals;",
    "    unsigned char *ost = m->state;",
    "    long long ocount = m->count;",
    "    long long *oorder = m->order;",
    "    m->cap = old_cap * 2;",
    "    m->count = 0;",
    "    m->keys = (unsigned char *)sl_gc_alloc((size_t)m->cap * m->ksz, NULL);",
    "    m->vals = (unsigned char *)sl_gc_alloc((size_t)m->cap * m->vsz, NULL);",
    "    m->state = (unsigned char *)sl_gc_alloc((size_t)m->cap, NULL);",
    "    m->order = (long long *)sl_gc_alloc((size_t)m->cap * sizeof(long long), NULL);",
    "    (void)ost;",
    "    /* reinsert in insertion order so iteration stays deterministic */",
    "    for (long long i = 0; i < ocount; i++) {",
    "        long long slot = oorder[i];",
    "        void *k = ok + (size_t)slot * m->ksz;",
    "        void *v = ov + (size_t)slot * m->vsz;",
    "        unsigned long long h = m->kstr",
    "                                  ? sl_hash_str(*(const char **)k)",
    "                                  : sl_hash_bytes((const unsigned char *)k,",
    "                                                  m->ksz);",
    "        long long s = -sl_map_probe(m, k, h) - 1;",
    "        memcpy(m->keys + (size_t)s * m->ksz, k, m->ksz);",
    "        memcpy(m->vals + (size_t)s * m->vsz, v, m->vsz);",
    "        m->state[s] = 1;",
    "        m->order[m->count++] = s;",
    "    }",
    "}",
    "",
    "static void sl_map_put(sl_map *m, const void *k, const void *v) {",
    "    unsigned long long h = m->kstr",
    "                              ? sl_hash_str(*(const char *const *)k)",
    "                              : sl_hash_bytes((const unsigned char *)k,",
    "                                              m->ksz);",
    "    if ((m->count + 1) * 4 >= m->cap * 3)",
    "        sl_map_grow(m);",
    "    long long s = sl_map_probe(m, k, h);",
    "    if (s >= 0) {",
    "        memcpy(m->vals + (size_t)s * m->vsz, v, m->vsz);",
    "        return;",
    "    }",
    "    s = -s - 1;",
    "    memcpy(m->keys + (size_t)s * m->ksz, k, m->ksz);",
    "    memcpy(m->vals + (size_t)s * m->vsz, v, m->vsz);",
    "    m->state[s] = 1;",
    "    m->order[m->count++] = s;",
    "}",
    "",
    "static void *sl_map_get(sl_map *m, const void *k) {",
    "    unsigned long long h = m->kstr",
    "                              ? sl_hash_str(*(const char *const *)k)",
    "                              : sl_hash_bytes((const unsigned char *)k,",
    "                                              m->ksz);",
    "    long long s = sl_map_probe(m, k, h);",
    "    if (s < 0)",
    "        return NULL;",
    "    return m->vals + (size_t)s * m->vsz;",
    "}",
    "",
    "static int sl_map_has(sl_map *m, const void *k) {",
    "    return sl_map_get(m, k) != NULL;",
    "}",
    "",
    "static void sl_map_del(sl_map *m, const void *k) {",
    "    unsigned long long h = m->kstr",
    "                              ? sl_hash_str(*(const char *const *)k)",
    "                              : sl_hash_bytes((const unsigned char *)k,",
    "                                              m->ksz);",
    "    long long s = sl_map_probe(m, k, h);",
    "    if (s < 0)",
    "        return;",
    "    m->state[s] = 0;",
    "    for (long long i = 0; i < m->count; i++) {",
    "        if (m->order[i] == s) {",
    "            memmove(m->order + i, m->order + i + 1,",
    "                    (size_t)(m->count - i - 1) * sizeof(long long));",
    "            break;",
    "        }",
    "    }",
    "    m->count--;",
    "}",
    "",
    "/* ---- strings ---- */",
    "",
    "static char *sl_strdup(const char *s) {",
    "    size_t n = strlen(s) + 1;",
    "    char *p = (char *)sl_gc_alloc(n, NULL);",
    "    memcpy(p, s, n);",
    "    return p;",
    "}",
    "",
    "static char *sl_str_concat(const char *a, const char *b) {",
    "    size_t la = strlen(a), lb = strlen(b);",
    "    char *p = (char *)sl_gc_alloc(la + lb + 1, NULL);",
    "    memcpy(p, a, la);",
    "    memcpy(p + la, b, lb);",
    "    p[la + lb] = 0;",
    "    return p;",
    "}",
    "",
    "static char *sl_str_from_int(long long v) {",
    "    char buf[32];",
    "    snprintf(buf, sizeof(buf), \"%lld\", v);",
    "    return sl_strdup(buf);",
    "}",
    "",
    "static char *sl_str_from_uint(unsigned long long v) {",
    "    char buf[32];",
    "    snprintf(buf, sizeof(buf), \"%llu\", v);",
    "    return sl_strdup(buf);",
    "}",
    "",
    "static char *sl_str_from_float(double v) {",
    "    char buf[64];",
    "    snprintf(buf, sizeof(buf), \"%g\", v);",
    "    return sl_strdup(buf);",
    "}",
    "",
    "static char *sl_str_from_bool(bool v) {",
    "    return sl_strdup(v ? \"true\" : \"false\");",
    "}",
    "",
    "/* ---- user program ---- */",
    "",
};

const int RUNTIME_CONTAINERS_LEN =
    sizeof(RUNTIME_CONTAINERS) / sizeof(RUNTIME_CONTAINERS[0]);
