// content/index.sl: the demo's single HTML page, served at GET /.

pub fn index_html() -> str {
    let head = "<!DOCTYPE html>\n"
        + "<html lang=\"en\">\n"
        + "<head>\n"
        + "<meta charset=\"UTF-8\">\n"
        + "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
        + "<title>Slang Arcade</title>\n"
        + "<link rel=\"stylesheet\" href=\"/style.css\">\n"
        + "</head>\n"
        + "<body>\n"
        + "<div class=\"wrap\">\n";

    let header = "<header>\n"
        + "  <h1>&#127918; SLANG ARCADE</h1>\n"
        + "  <p class=\"tagline\">A small server-side app written entirely in "
        + "<a href=\"https://github.com/anthropics\" target=\"_blank\" rel=\"noopener\">slang</a> "
        + "&mdash; a statically-typed, garbage-collected language that transpiles to C. "
        + "One process, one binary, no runtime dependencies but libgc.</p>\n"
        + "</header>\n";

    let pulse = "<section class=\"panel\" id=\"pulse\">\n"
        + "  <h2>&#9889; Live Server Pulse</h2>\n"
        + "  <div class=\"stat-grid\">\n"
        + "    <div class=\"stat\"><span class=\"stat-value\" id=\"stat-uptime\">--</span><span class=\"stat-label\">uptime</span></div>\n"
        + "    <div class=\"stat\"><span class=\"stat-value\" id=\"stat-requests\">--</span><span class=\"stat-label\">requests</span></div>\n"
        + "    <div class=\"stat\"><span class=\"stat-value\" id=\"stat-active\">--</span><span class=\"stat-label\">active tasks</span></div>\n"
        + "    <div class=\"stat\"><span class=\"stat-value\" id=\"stat-messages\">--</span><span class=\"stat-label\">wall posts</span></div>\n"
        + "    <div class=\"stat\"><span class=\"stat-value\" id=\"stat-players\">--</span><span class=\"stat-label\">players</span></div>\n"
        + "    <div class=\"stat\"><span class=\"stat-value\" id=\"stat-pid\">--</span><span class=\"stat-label\">pid</span></div>\n"
        + "  </div>\n"
        + "</section>\n";

    let dice = "<section class=\"panel\" id=\"dice\">\n"
        + "  <h2>&#127922; Dice Duel</h2>\n"
        + "  <div class=\"dice-row\">\n"
        + "    <input id=\"dice-name\" type=\"text\" placeholder=\"your name\" maxlength=\"24\">\n"
        + "    <button id=\"roll-btn\" type=\"button\">Roll!</button>\n"
        + "  </div>\n"
        + "  <div class=\"dice-result\">\n"
        + "    <span class=\"die\" id=\"die-a\">?</span>\n"
        + "    <span class=\"die\" id=\"die-b\">?</span>\n"
        + "    <span class=\"dice-total\" id=\"dice-total\"></span>\n"
        + "  </div>\n"
        + "  <p><span class=\"badge\" id=\"double-badge\" hidden>DOUBLES!</span></p>\n"
        + "  <h3>Leaderboard</h3>\n"
        + "  <table class=\"board\">\n"
        + "    <thead><tr><th>player</th><th>best</th><th>rolls</th></tr></thead>\n"
        + "    <tbody id=\"leaderboard-body\"></tbody>\n"
        + "  </table>\n"
        + "</section>\n";

    let guestbook = "<section class=\"panel\" id=\"guestbook\">\n"
        + "  <h2>&#128220; Guestbook Wall</h2>\n"
        + "  <form id=\"msg-form\">\n"
        + "    <input id=\"msg-author\" type=\"text\" placeholder=\"name\" maxlength=\"24\">\n"
        + "    <div class=\"mood-row\" id=\"mood-row\">\n"
        + "      <button type=\"button\" class=\"mood-btn\" data-mood=\"&#128522;\">&#128522;</button>\n"
        + "      <button type=\"button\" class=\"mood-btn\" data-mood=\"&#127881;\">&#127881;</button>\n"
        + "      <button type=\"button\" class=\"mood-btn\" data-mood=\"&#129300;\">&#129300;</button>\n"
        + "      <button type=\"button\" class=\"mood-btn\" data-mood=\"&#128293;\">&#128293;</button>\n"
        + "    </div>\n"
        + "    <textarea id=\"msg-text\" placeholder=\"say something...\" maxlength=\"240\"></textarea>\n"
        + "    <button type=\"submit\">Post</button>\n"
        + "  </form>\n"
        + "  <ul class=\"wall\" id=\"wall\"></ul>\n"
        + "</section>\n";

    let columns = "<div class=\"columns\">\n" + dice + guestbook + "</div>\n";

    let footer = "<footer>\n"
        + "  <p>Powered by slang's <code>net</code> (raw TCP + TLS), "
        + "<code>json</code> (typed encode/decode), <code>proc</code> "
        + "(graceful shutdown &amp; env vars), <code>spawn</code>/"
        + "<code>chan[T]</code> concurrency, package imports, and a tiny "
        + "C library via <code>extern fn</code>. This page and its CSS/JS "
        + "are generated by slang functions &mdash; there's no static file "
        + "server. Source: <code>demo/</code>.</p>\n"
        + "</footer>\n";

    let tail = "</div>\n"
        + "<script src=\"/app.js\"></script>\n"
        + "</body>\n"
        + "</html>\n";

    return head + header + pulse + columns + footer + tail;
}
