// content/script.sl: the demo's client-side JS, served at GET /app.js.
// Plain string concatenation throughout, deliberately avoiding JS
// template literals -- a bare backtick string's ${...} would collide
// with slang's own ${...} string interpolation syntax at the source
// level, and slang's escape set doesn't include a plain backslash
// passthrough, so keeping the embedded JS backslash-free (and
// template-literal-free) sidesteps both problems entirely.

pub fn app_js() -> str {
    let helpers = "function fmtUptime(ms) {\n"
        + "  var s = Math.floor(ms / 1000);\n"
        + "  var m = Math.floor(s / 60);\n"
        + "  s = s % 60;\n"
        + "  if (m > 0) { return m + 'm ' + s + 's'; }\n"
        + "  return s + 's';\n"
        + "}\n"
        + "function getJSON(url) {\n"
        + "  return fetch(url).then(function (r) { return r.json(); });\n"
        + "}\n"
        + "function postJSON(url, body) {\n"
        + "  return fetch(url, {\n"
        + "    method: 'POST',\n"
        + "    headers: { 'Content-Type': 'application/json' },\n"
        + "    body: JSON.stringify(body)\n"
        + "  }).then(function (r) { return r.json(); });\n"
        + "}\n"
        + "function escapeHTML(s) {\n"
        + "  var d = document.createElement('div');\n"
        + "  d.textContent = s;\n"
        + "  return d.innerHTML;\n"
        + "}\n"
        + "var DIE_FACES = ['', String.fromCharCode(9856), String.fromCharCode(9857), "
        + "String.fromCharCode(9858), String.fromCharCode(9859), "
        + "String.fromCharCode(9860), String.fromCharCode(9861)];\n";

    let stats = "function refreshStats() {\n"
        + "  getJSON('/api/stats').then(function (s) {\n"
        + "    document.getElementById('stat-uptime').textContent = fmtUptime(s.uptime_ms);\n"
        + "    document.getElementById('stat-requests').textContent = s.requests;\n"
        + "    document.getElementById('stat-active').textContent = s.active_tasks;\n"
        + "    document.getElementById('stat-messages').textContent = s.message_count;\n"
        + "    document.getElementById('stat-players').textContent = s.player_count;\n"
        + "    document.getElementById('stat-pid').textContent = s.pid;\n"
        + "  }).catch(function () {});\n"
        + "}\n";

    let leaderboard = "function refreshLeaderboard() {\n"
        + "  getJSON('/api/leaderboard').then(function (board) {\n"
        + "    var names = Object.keys(board);\n"
        + "    names.sort(function (a, b) { return board[b].best - board[a].best; });\n"
        + "    var body = document.getElementById('leaderboard-body');\n"
        + "    var html = '';\n"
        + "    for (var i = 0; i < names.length; i++) {\n"
        + "      var p = board[names[i]];\n"
        + "      html += '<tr><td>' + escapeHTML(p.name) + '</td><td>' + p.best + '</td><td>' + p.rolls + '</td></tr>';\n"
        + "    }\n"
        + "    body.innerHTML = html || '<tr><td colspan=\"3\">nobody has rolled yet</td></tr>';\n"
        + "  }).catch(function () {});\n"
        + "}\n";

    let dice = "function doRoll() {\n"
        + "  var nameEl = document.getElementById('dice-name');\n"
        + "  var name = nameEl.value.trim() || 'anon';\n"
        + "  postJSON('/api/roll', { player: name }).then(function (res) {\n"
        + "    document.getElementById('die-a').textContent = DIE_FACES[res.a];\n"
        + "    document.getElementById('die-b').textContent = DIE_FACES[res.b];\n"
        + "    document.getElementById('dice-total').innerHTML = 'total: <b>' + res.total + '</b>';\n"
        + "    document.getElementById('double-badge').hidden = !res.is_double;\n"
        + "    refreshLeaderboard();\n"
        + "  }).catch(function () {});\n"
        + "}\n";

    let wall = "function renderWall(messages) {\n"
        + "  var ul = document.getElementById('wall');\n"
        + "  if (messages.length === 0) {\n"
        + "    ul.innerHTML = '<li>the wall is empty -- say hello!</li>';\n"
        + "    return;\n"
        + "  }\n"
        + "  var html = '';\n"
        + "  for (var i = messages.length - 1; i >= 0; i--) {\n"
        + "    var m = messages[i];\n"
        + "    var mood = m.mood ? (' ' + m.mood) : '';\n"
        + "    var when = new Date(m.at_ms).toLocaleTimeString();\n"
        + "    html += '<li><span class=\"who\">' + escapeHTML(m.author) + mood + '</span>'\n"
        + "      + '<span class=\"when\">' + when + '</span>'\n"
        + "      + '<div class=\"text\">' + escapeHTML(m.text) + '</div></li>';\n"
        + "  }\n"
        + "  ul.innerHTML = html;\n"
        + "}\n"
        + "function refreshWall() {\n"
        + "  getJSON('/api/messages').then(renderWall).catch(function () {});\n"
        + "}\n";

    let wire = "var selectedMood = null;\n"
        + "document.addEventListener('DOMContentLoaded', function () {\n"
        + "  document.getElementById('roll-btn').addEventListener('click', doRoll);\n"
        + "  var moodBtns = document.querySelectorAll('.mood-btn');\n"
        + "  for (var i = 0; i < moodBtns.length; i++) {\n"
        + "    moodBtns[i].addEventListener('click', function (ev) {\n"
        + "      var btn = ev.currentTarget;\n"
        + "      var already = btn.classList.contains('selected');\n"
        + "      for (var j = 0; j < moodBtns.length; j++) { moodBtns[j].classList.remove('selected'); }\n"
        + "      if (already) { selectedMood = null; } else {\n"
        + "        btn.classList.add('selected');\n"
        + "        selectedMood = btn.getAttribute('data-mood');\n"
        + "      }\n"
        + "    });\n"
        + "  }\n"
        + "  document.getElementById('msg-form').addEventListener('submit', function (ev) {\n"
        + "    ev.preventDefault();\n"
        + "    var author = document.getElementById('msg-author').value.trim() || 'anon';\n"
        + "    var text = document.getElementById('msg-text').value.trim();\n"
        + "    if (!text) { return; }\n"
        + "    postJSON('/api/messages', { author: author, text: text, mood: selectedMood })\n"
        + "      .then(function () {\n"
        + "        document.getElementById('msg-text').value = '';\n"
        + "        refreshWall();\n"
        + "        refreshStats();\n"
        + "      }).catch(function () {});\n"
        + "  });\n"
        + "  refreshStats();\n"
        + "  refreshLeaderboard();\n"
        + "  refreshWall();\n"
        + "  setInterval(refreshStats, 1500);\n"
        + "});\n";

    return helpers + stats + leaderboard + dice + wall + wire;
}
