// content/style.sl: the demo's CSS, served at GET /style.css.
// Embedded as a string (slang has no static-file serving -- there's
// no file-I/O builtin exposed to slang programs at all, so the whole
// frontend lives in source, built the same way the compiler embeds
// its own C runtime: chunks of string literal, concatenated).

pub fn style_css() -> str {
    let base = "*, *::before, *::after { box-sizing: border-box; }\n"
        + ":root {\n"
        + "  --bg: #0b0e14;\n"
        + "  --panel: #121722;\n"
        + "  --panel-2: #161d2b;\n"
        + "  --text: #d9e2f2;\n"
        + "  --muted: #7c8aa5;\n"
        + "  --accent: #38f2c0;\n"
        + "  --accent-2: #ff5fb6;\n"
        + "  --accent-3: #ffd166;\n"
        + "  --border: #253049;\n"
        + "}\n"
        + "html, body {\n"
        + "  margin: 0;\n"
        + "  padding: 0;\n"
        + "  background: radial-gradient(circle at 20% -10%, #1a2236 0%, var(--bg) 55%);\n"
        + "  color: var(--text);\n"
        + "  font-family: 'Courier New', ui-monospace, Menlo, monospace;\n"
        + "  min-height: 100vh;\n"
        + "}\n";

    let layout = ".wrap {\n"
        + "  max-width: 980px;\n"
        + "  margin: 0 auto;\n"
        + "  padding: 28px 20px 60px;\n"
        + "}\n"
        + "header { text-align: center; margin-bottom: 28px; }\n"
        + "header h1 {\n"
        + "  font-size: 2.4rem;\n"
        + "  margin: 0 0 8px;\n"
        + "  letter-spacing: 0.08em;\n"
        + "  color: var(--accent);\n"
        + "  text-shadow: 0 0 18px rgba(56, 242, 192, 0.45);\n"
        + "}\n"
        + ".tagline { color: var(--muted); max-width: 560px; margin: 0 auto; line-height: 1.5; }\n"
        + ".tagline a { color: var(--accent-3); }\n"
        + ".columns {\n"
        + "  display: grid;\n"
        + "  grid-template-columns: 1fr 1fr;\n"
        + "  gap: 20px;\n"
        + "  align-items: start;\n"
        + "}\n"
        + "@media (max-width: 760px) {\n"
        + "  .columns { grid-template-columns: 1fr; }\n"
        + "}\n";

    let panel = ".panel {\n"
        + "  background: linear-gradient(180deg, var(--panel) 0%, var(--panel-2) 100%);\n"
        + "  border: 1px solid var(--border);\n"
        + "  border-radius: 14px;\n"
        + "  padding: 20px 22px;\n"
        + "  margin-bottom: 20px;\n"
        + "  box-shadow: 0 10px 30px rgba(0, 0, 0, 0.35);\n"
        + "}\n"
        + ".panel h2 {\n"
        + "  margin-top: 0;\n"
        + "  font-size: 1.1rem;\n"
        + "  letter-spacing: 0.04em;\n"
        + "  border-bottom: 1px dashed var(--border);\n"
        + "  padding-bottom: 10px;\n"
        + "}\n"
        + ".panel h3 {\n"
        + "  font-size: 0.95rem;\n"
        + "  color: var(--muted);\n"
        + "  margin: 18px 0 8px;\n"
        + "  text-transform: uppercase;\n"
        + "  letter-spacing: 0.08em;\n"
        + "}\n";

    let stats = ".stat-grid {\n"
        + "  display: grid;\n"
        + "  grid-template-columns: repeat(auto-fit, minmax(120px, 1fr));\n"
        + "  gap: 12px;\n"
        + "}\n"
        + ".stat {\n"
        + "  background: rgba(56, 242, 192, 0.06);\n"
        + "  border: 1px solid var(--border);\n"
        + "  border-radius: 10px;\n"
        + "  padding: 12px 10px;\n"
        + "  text-align: center;\n"
        + "}\n"
        + ".stat-value {\n"
        + "  display: block;\n"
        + "  font-size: 1.35rem;\n"
        + "  font-weight: bold;\n"
        + "  color: var(--accent);\n"
        + "}\n"
        + ".stat-label {\n"
        + "  display: block;\n"
        + "  margin-top: 4px;\n"
        + "  font-size: 0.72rem;\n"
        + "  color: var(--muted);\n"
        + "  text-transform: uppercase;\n"
        + "  letter-spacing: 0.06em;\n"
        + "}\n";

    let forms = "input[type='text'], textarea {\n"
        + "  width: 100%;\n"
        + "  background: #0d1220;\n"
        + "  border: 1px solid var(--border);\n"
        + "  border-radius: 8px;\n"
        + "  color: var(--text);\n"
        + "  padding: 9px 10px;\n"
        + "  font-family: inherit;\n"
        + "  font-size: 0.92rem;\n"
        + "  margin-bottom: 10px;\n"
        + "}\n"
        + "textarea { min-height: 64px; resize: vertical; }\n"
        + "input[type='text']:focus, textarea:focus {\n"
        + "  outline: none;\n"
        + "  border-color: var(--accent);\n"
        + "  box-shadow: 0 0 0 3px rgba(56, 242, 192, 0.15);\n"
        + "}\n"
        + "button {\n"
        + "  background: var(--accent);\n"
        + "  color: #06110d;\n"
        + "  border: none;\n"
        + "  border-radius: 8px;\n"
        + "  padding: 10px 16px;\n"
        + "  font-weight: bold;\n"
        + "  font-family: inherit;\n"
        + "  cursor: pointer;\n"
        + "  transition: transform 0.08s ease, box-shadow 0.15s ease;\n"
        + "}\n"
        + "button:hover { box-shadow: 0 0 16px rgba(56, 242, 192, 0.55); }\n"
        + "button:active { transform: scale(0.97); }\n";

    let dice = ".dice-row { display: flex; gap: 10px; align-items: flex-start; }\n"
        + ".dice-row input { flex: 1; margin-bottom: 0; }\n"
        + ".dice-result {\n"
        + "  display: flex;\n"
        + "  align-items: center;\n"
        + "  gap: 14px;\n"
        + "  margin: 18px 0 6px;\n"
        + "  min-height: 64px;\n"
        + "}\n"
        + ".die {\n"
        + "  font-size: 3rem;\n"
        + "  line-height: 1;\n"
        + "  color: var(--accent-3);\n"
        + "  text-shadow: 0 0 14px rgba(255, 209, 102, 0.5);\n"
        + "}\n"
        + ".dice-total { font-size: 1.4rem; color: var(--muted); }\n"
        + ".dice-total b { color: var(--text); }\n"
        + ".badge {\n"
        + "  display: inline-block;\n"
        + "  background: var(--accent-2);\n"
        + "  color: #1a0512;\n"
        + "  font-weight: bold;\n"
        + "  padding: 4px 10px;\n"
        + "  border-radius: 999px;\n"
        + "  font-size: 0.8rem;\n"
        + "  letter-spacing: 0.06em;\n"
        + "  box-shadow: 0 0 16px rgba(255, 95, 182, 0.6);\n"
        + "}\n"
        + "table.board { width: 100%; border-collapse: collapse; font-size: 0.88rem; }\n"
        + "table.board th, table.board td {\n"
        + "  text-align: left;\n"
        + "  padding: 6px 8px;\n"
        + "  border-bottom: 1px solid var(--border);\n"
        + "}\n"
        + "table.board th { color: var(--muted); font-weight: normal; text-transform: uppercase; font-size: 0.72rem; }\n";

    let guestbook = ".mood-row { display: flex; gap: 8px; margin-bottom: 10px; }\n"
        + ".mood-btn {\n"
        + "  background: #0d1220;\n"
        + "  border: 1px solid var(--border);\n"
        + "  border-radius: 8px;\n"
        + "  padding: 6px 10px;\n"
        + "  font-size: 1.1rem;\n"
        + "  cursor: pointer;\n"
        + "}\n"
        + ".mood-btn.selected { border-color: var(--accent); background: rgba(56, 242, 192, 0.12); }\n"
        + "ul.wall { list-style: none; padding: 0; margin: 12px 0 0; max-height: 340px; overflow-y: auto; }\n"
        + "ul.wall li {\n"
        + "  border: 1px solid var(--border);\n"
        + "  border-radius: 10px;\n"
        + "  padding: 10px 12px;\n"
        + "  margin-bottom: 10px;\n"
        + "  background: rgba(255, 255, 255, 0.02);\n"
        + "}\n"
        + "ul.wall .who { color: var(--accent-3); font-weight: bold; }\n"
        + "ul.wall .when { color: var(--muted); font-size: 0.75rem; float: right; }\n"
        + "ul.wall .text { margin-top: 4px; line-height: 1.4; }\n";

    let footer = "footer {\n"
        + "  text-align: center;\n"
        + "  color: var(--muted);\n"
        + "  font-size: 0.8rem;\n"
        + "  line-height: 1.6;\n"
        + "  margin-top: 10px;\n"
        + "}\n"
        + "footer code {\n"
        + "  background: rgba(255, 255, 255, 0.06);\n"
        + "  padding: 1px 5px;\n"
        + "  border-radius: 4px;\n"
        + "  color: var(--accent);\n"
        + "}\n";

    return base + layout + panel + stats + forms + dice + guestbook + footer;
}
